In [12]:
# for tag in soup.find_all(string=lambda x: x and 'Domicílio Eletrônico' in x):
#     print(tag)
#     print(tag.parent)
import re
import json
from pathlib import Path
import pandas as pd
from pprint import pprint

In [13]:
def extrair_meio(texto):

    texto = texto.lower()

    if any(x in texto for x in ('advgs', '(P/ Advgs.', 'advgs.', 'advogado')):
        return 'advogado'

    if 'ofício' in texto or 'oficio' in texto:
        return 'oficio'

    if 'mandado' in texto:
        return 'mandado'
    # if 'prazo' in texto:
    #     return 'mandado'

    # if 'ofício' in texto:
    #     return 'oficio'

    if ('aviso de recebimento' in texto or 'juntada de ar' in texto):
        return 'ar'
    # if '(para ' in texto:
    #     return 'pessoal'
    if re.search(r'\bpara\b', texto):
        return 'pessoal'

    return None

def situacao_comunicacao(texto):

    texto = str(texto).lower()

    if 'lido(a)' in texto:
        return 'lida'

    if 'expedido(a)' in texto:
        return 'expedida'

    if 'devolução sem leitura' in texto:
        return 'devolvida_sem_leitura'

    if 'juntada de ar' in texto:
        return 'ar_juntado'

    if 'mandado devolvido' in texto:
        return 'mandado_devolvido'

    if 'mandado assinado' in texto:
        return 'mandado_assinado'

    if 'mandado à disposição' in texto:
        return 'mandado_disponivel'

    if 'solicitada a expedição de mandado' in texto:
        return 'mandado_solicitado'

    return None

def tipo_comunicacao(texto):
    texto = texto.lower()

    if 'citação' in texto:
        return 'citacao'

    if 'intimação' in texto:
        return 'intimacao'

    if 'certidão' in texto:
        return 'certidao'
    if 'juntada de ar' in texto:
        return 'certidao'

    return 'outro'

def expedidas(df):
    expedidas = df[df['situacao_comunicacao'] == 'expedida'].copy()
    expedidas['meio_real'] = expedidas['ato'].apply(extrair_meio)
    return expedidas

def referenciados(df):
    return df[df['observacao'].str.contains('Referente ao evento', case=False, na=False)].copy()

def lidas (df):

    lidas = (df[df['situacao_comunicacao'] == 'lida']).copy()
    # mask_ar = df[df['ato'].str.contains(r'juntada de ar|aviso de recebimento', case=False, na=False)].copy()
    # len(lidas)
    # print(mask_lida.sum())
    # print(mask_ar.sum())
    # return df[mask_lida|mask_ar]
    return lidas
    # return pd.concat([mask_lida, mask_ar]).drop_duplicates()

def chave(df_expedidas, df_lidas):
    df_expedidas['chave'] = (
        df_expedidas['destinatario']
        .str.lower()
        .str.strip()
        + '|'
        + df_expedidas['data_texto']
    )

    df_lidas['chave'] = (
       df_lidas['destinatario']
        .str.lower()
        .str.strip()
        + '|'
        + df_lidas['data_referencia_str']
    )

# print(len(expedidas), len(lidas))

def relacoes(df_expedidas, df_lidas):
    relacoes = df_lidas.merge(
        df_expedidas,
        on=['chave', 'destinatario', 'tipo'],
        suffixes=(
            '_lido',
            '_expedido'
        )
    )
    return relacoes

# def origem(df_relacoes):
#     relacoes['ato_origem'] = relacoes['ato_lido'].str.extract(
#         r'Referente ao evento\s+(.*?)\('
#     )

#     relacoes['data_origem'] = relacoes['ato_lido'].str.extract(
#         r'\((\d{2}/\d{2}/\d{2})\)'
#     )
def origem(df_relacoes):

    df_relacoes['ato_origem'] = (
        df_relacoes['ato_lido']
        .str.extract(
            r'Referente ao evento\s+(.*?)\(',
            expand=False
        )
    )

    df_relacoes['data_origem'] = (
        df_relacoes['ato_lido']
        .str.extract(
            r'\((\d{2}/\d{2}/\d{2})\)',
            expand=False
        )
    )

    return df_relacoes
# def canais_disponiveis(row):

#     canais = []

#     if row['tem_advogado']:
#         canais.append('advogado')

#     if row['domicilio_cnj']:
#         canais.append('domicilio_cnj')

#     if pd.notna(row['email']):
#         canais.append('email')

#     return ', '.join(canais)
def canais_disponiveis(row):

    canais = []

    if row['tem_advogado']:
        canais.append('advogado')

    if row['domicilio_cnj']:
        canais.append('domicilio_cnj')

    if row['recebe_intimacao_email']:
        canais.append('email_autorizado')

    elif pd.notna(row['email']):
        canais.append('email_cadastrado')

    if pd.notna(row['tel']):
        canais.append('telefone')

    return ', '.join(canais)


def lista_canais_disponiveis(row):

    canais = []

    if row['tem_advogado']:
        canais.append('advogado')

    if row['domicilio_cnj']:
        canais.append('domicilio_cnj')

    if row['recebe_intimacao_email']:
        canais.append('email_autorizado')

    elif pd.notna(row['email']):
        canais.append('email_cadastrado')

    if pd.notna(row['tel']):
        canais.append('telefone')

    return canais


def status_comunicacao(row):

    if row['tem_advogado']:
        return 'alta_advogado'

    if row['domicilio_cnj']:
        return 'alta_domicilio_cnj'

    if row['recebe_intimacao_email']:
        return 'alta_email_autorizado'

    if pd.notna(row['email']):
        return 'media_email_cadastrado'

    return 'baixa_sem_canal_eletronico'

# def status_comunicacao(row):

#     canais = row['canais_disponiveis']

#     if not canais:
#         return 'baixa'

#     if all(x in canais for x in ['advogado', 'domicilio_cnj', 'email']):
#         return 'muito_alta'

#     if 'advogado' in canais and 'domicilio_cnj' in canais:
#         return 'alta_adv_djen'

#     if 'domicilio_cnj' in canais and 'email' in canais:
#         return 'alta_djen_email'

#     if 'advogado' in canais:
#         return 'media_advogado'

#     if 'domicilio_cnj' in canais:
#         return 'media_djen'

#     if 'email' in canais:
#         return 'media_email'

#     return 'baixa'

# def status_processo(processo_ok, autores_ok, acusados_ok):
#     if processo_ok:
#         return 'automatizar'

#     if autores_ok and not acusados_ok:
#         return 'pendencia_promovido'

#     if acusados_ok and not autores_ok:
#         return 'pendencia_promovente'

#     return 'pendencia_geral'
def status_processo(autores_ok, acusados_ok):

    if autores_ok and acusados_ok:
        return 'automatizar'

    if not autores_ok and acusados_ok:
        return 'autor_pendente'

    if autores_ok and not acusados_ok:
        return 'reu_pendente'

    return 'ambos_pendentes'


def normalizar_nome(x):
    if pd.isna(x):
        return None

    x = x.lower().strip()
    x = re.sub(r'\(rev\.\s*arg\.?\)', '', x, flags=re.I)
    x = re.sub(r'\s+', ' ', x)
    return x

def marcar_revelia(nome):
    if pd.isna(nome):
        return False
    return bool(re.search(r'\(rev\.\s*arg\.?\)', nome, re.I))

def status_processo(df_partes):

    autores_ok = df_partes.loc[
        df_partes['papel'] == 'PROMOVENTE',
        'habilitada_receber'
    ].all()

    acusados_ok = df_partes.loc[
        df_partes['papel'] == 'PROMOVIDO',
        'habilitada_receber'
    ].all()

    if autores_ok and acusados_ok:
        return True, 'automatizar'

    if autores_ok and not acusados_ok:
        return False, 'autor_pendente'

    if not autores_ok and acusados_ok:
        return False, 'reu_pendente'

    return False, 'ambos_pendentes'

padrao_revelia = re.compile(r'\(rev\.\s*arg\.?\)', re.I)

def tratar_parte(parte):
    nome_original = parte['nome']
    nome_norm_original = parte.get('nome_normalizado', nome_original)

    revelia = bool(padrao_revelia.search(nome_original))

    return {
        **parte,
        "revelia": revelia,
        "nome_limpo": padrao_revelia.sub("", nome_original).strip(),
        "nome_normalizado_limpo": padrao_revelia.sub("", nome_norm_original).strip()
    }

In [14]:
def fisicos_expedidos(df):

    mask = df['ato'].str.contains(
        r'mandado assinado|ofício assinado|carta assinado',
        case=False,
        na=False
    )

    return df[mask].copy()

def fisicos_retorno(df):

    mask = df['ato'].str.contains(
        r'mandado devolvido|ofício juntado|juntada de ar',
        case=False,
        na=False
    )

    return df[mask].copy()

In [15]:
pasta = Path("C:\\Users\\igusilva\\OneDrive - Tribunal de Justiça do Estado da Bahia\\Área de Trabalho\\assets\\apps\\vitoria_secret\\udemy\\data_science\\nlp_spacy\\processos_movs_json")

In [16]:
arquivos = list(pasta.glob('*.json'))

print(len(arquivos))

43

In [21]:
partes_processos = {}
for arquivo in pasta.glob("*.json"):
    processo = arquivo.stem

    # print("Lendo:", arquivo)

    try:

        with open(arquivo, "r", encoding="utf-8") as f:
            dados = json.load(f)
            partes = [tratar_parte(p) for p in dados['partes']]
            df_atos = pd.DataFrame(dados['movimentacoes'])
            df_partes = pd.DataFrame(partes)

            print(df_atos[
                df_atos['ato'].str.contains(
                    r'mandado|ofício|ar',
                    case=False,
                    na=False
                )
            ][['evento', 'ato', 'data_texto']])
           
    except Exception as e:

        print("ERRO:", e)

   evento                                                ato data_texto
0      82  Intimação expedido(a) (P/ Advgs. de PAYOUT PAG...   02/06/26
1      81  Intimação expedido(a) (P/ Advgs. de DANILO AUG...   02/06/26
2      72  Intimação expedido(a) (P/ Advgs. de DANILO AUG...   01/06/26
3      62  Intimação lido(a) (Para TV VINHOS LTDA) em 11/...   17/05/26
4      61  Intimação lido(a) (Para PAYOUT PAGAMENTOS INTE...   09/05/26
5      60  Intimação expedido(a) Para TV VINHOS LTDA *Ref...   28/04/26
6      58  Intimação expedido(a) (Para PAYOUT PAGAMENTOS ...   28/04/26
7      49  Intimação expedido(a) (P/ Advgs. de DANILO AUG...   17/04/26
8      37  Intimação expedido(a) (P/ Advgs. de DANILO AUG...   20/02/26
9      33  Audiência de Conciliação Realizada (Telepresen...   19/02/26
11     28  Intimação lido(a) (Para TV VINHOS LTDA) em 05/...   14/02/26
13     25  Intimação lido(a) (Para PAYOUT PAGAMENTOS INTE...   03/02/26
14     24            Citação expedido(a) Para TV VINHOS LTDA   26/01/26
15     23  Citação expedido(a) Para PAYOUT PAGAMENTOS INT...   26/01/26
16     17  Intimação expedido(a) Para TV VINHOS LTDA *Ref...   23/01/26
17     14  Intimação expedido(a) (Para PAYOUT PAGAMENTOS ...   21/01/26
18     13  Intimação expedido(a) (P/ Advgs. de DANILO AUG...   21/01/26
19      9            Citação expedido(a) Para TV VINHOS LTDA   15/01/26
20      7  Citação expedido(a) (Para PAYOUT PAGAMENTOS IN...   15/01/26
21      6  Intimação lido(a) (Para DANILO AUGUSTO E ARAUJ...   15/01/26
   evento                                                ato data_texto
0     258  Disponibilização no Diário da Justiça Eletrôni...   12/05/26
1     257  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   11/05/26
3     247  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   24/04/26
4     246  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   24/04/26
5     238  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   16/04/26
6     237  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   16/04/26
7     230  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   01/04/26
8     223  Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...   20/03/26
9     219  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   09/03/26
10    218  Intimação expedido(a) (Para AMIL ASSISTENCIA M...   09/03/26
11    217  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   09/03/26
12    209  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   25/02/26
13    205  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   23/01/26
14    198  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   12/11/25
15    191  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   31/10/25
16    182  Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...   21/10/25
17    180  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   14/10/25
18    174  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   10/10/25
19    173  Intimação expedido(a) (Para AMIL ASSISTENCIA M...   10/10/25
20    172  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   10/10/25
21    159  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   01/10/25
22    152  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   26/09/25
23    144  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   22/09/25
24    138  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   21/09/25
25    124  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   09/09/25
26    123  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   09/09/25
27    121  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   09/09/25
28    120  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   09/09/25
29    111  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   08/09/25
30    110  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   08/09/25
31    103  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   27/08/25
32    102  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   27/08/25
33     96  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   18/08/25
34     90  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   12/08/25
35     89  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   12/08/25
36     71  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   16/06/25
37     70  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   16/06/25
38     64  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   04/06/25
39     63  Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...   04/06/25
41     45  Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...   20/05/25
42     41  Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...   17/05/25
43     40  Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...   17/05/25
47     27  Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...   07/03/25
48     26  Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...   07/03/25
49     25  Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...   18/02/25
50     24  Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...   18/02/25
54     12  Intimação expedido(a) (Para AMIL ASSISTENCIA M...   07/02/25
56      7  Citação expedido(a) Para AMIL ASSISTENCIA MEDI...   06/02/25
57      6  Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...   06/02/25
   evento                                                ato data_texto
0     166  Intimação expedido(a) (P/ Advgs. de EDILEIDE D...   19/09/25
1     146  Intimação expedido(a) (P/ Advgs. de EDILEIDE D...   25/07/25
2     118  Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...   31/10/24
4     114  Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...   24/10/24
6      93  Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...   11/06/24
8      30  Intimação lido(a) (Para LARBELO MOVEIS) em 10/...   16/05/23
9      29  Intimação expedido(a) Para LARBELO MOVEIS *Ref...   19/04/23
10     19  Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...   22/03/23
13     11      Citação lido(a) P/ LARBELO MOVEIS em 08/03/23   15/03/23
14      9            Citação expedido(a) Para LARBELO MOVEIS   23/02/23
15      5  Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...   16/02/23
  evento                                                ato data_texto
0     45  Intimação expedido(a) Para CLAUDEMIR NASCIMENT...   04/05/26
1     40  Audiência Preliminar Realizada (Telepresencial...   29/04/26
2     35  Intimação lido(a) (Para Núcleo de Atuação MP P...   10/04/26
3     32  Intimação lido(a) (Para Núcleo de Atuação MP P...   07/04/26
5     23  Audiência Preliminar Não Realizada (Telepresen...   26/03/26
7     14  Devolução sem Leitura De Intimação expedida em...   06/03/26
8     13  Intimação lido(a) (Para Núcleo de Atuação MP P...   07/03/26
9     12  Intimação expedido(a) Para CLAUDEMIR NASCIMENT...   25/02/26
   evento                                                ato data_texto
0     180  Intimação expedido(a) (P/ Advgs. de BANCO BRAD...   03/06/26
1     171  Intimação expedido(a) (P/ Advgs. de BANCO BRAD...   01/04/26
2     152  Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...   30/04/24
3     151  Intimação lido(a) (Para BANCO BRADESCO FINANCI...   25/04/24
5     149  Intimação expedido(a) (P/ Advgs. de MARIA LUCI...   17/04/24
6     140  Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...   09/03/24
7     139  Intimação lido(a) (Para BANCO BRADESCO FINANCI...   06/03/24
9     137  Intimação expedido(a) (P/ Advgs. de MARIA LUCI...   27/02/24
10    123  Intimação lido(a) (Para BANCO BRADESCO FINANCI...   20/09/23
12    107  Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...   25/07/23
13    106  Intimação lido(a) (Para BANCO BRADESCO FINANCI...   21/07/23
15    103  Intimação expedido(a) (P/ Advgs. de MARIA LUCI...   14/07/23
16     95  Intimação lido(a) (Para BANCO BRADESCO FINANCI...   23/06/23
18     83  Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...   13/09/22
19     79  Intimação lido(a) (Para BANCO BRADESCO FINANCI...   05/09/22
21     74  Intimação expedido(a) (P/ Advgs. de MARIA LUCI...   02/09/22
23     63  Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...   01/09/22
24     62  Intimação expedido(a) (P/ Advgs. de MARIA LUCI...   31/08/22
25     51  Intimação lido(a) (Para BANCO BRADESCO FINANCI...   18/07/22
28     44  Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...   11/07/22
29     43  Intimação expedido(a) (P/ Advgs. de MARIA LUCI...   11/07/22
30     35  Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...   21/06/22
31     34  Intimação lido(a) (Para BANCO BRADESCO FINANCI...   10/06/22
33     32  Intimação expedido(a) (P/ Advgs. de MARIA LUCI...   08/06/22
35     24  Intimação realizada em Cartório/Audiência/Tele...   25/04/22
36     23  Intimação realizada em Cartório/Audiência/Tele...   25/04/22
38     14  Citação lido(a) P/ BANCO BRADESCO FINANCIAMENT...   26/03/22
39     13  Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...   24/03/22
40     11  Intimação expedido(a) (P/ Advgs. de MARIA LUCI...   17/03/22
41      7  Citação expedido(a) Para BANCO BRADESCO FINANC...   15/03/22
42      6  Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...   15/03/22
  evento                                                ato data_texto
0     40  Intimação expedido(a) (P/ Advgs. de PAULO CESA...   14/05/26
1     32  Intimação expedido(a) (P/ Advgs. de AZUL LINHA...   24/04/26
2     31  Intimação expedido(a) (P/ Advgs. de PAULO CESA...   24/04/26
3     21  Intimação expedido(a) (P/ Advgs. de PAULO CESA...   16/04/26
4     16  Audiência de Conciliação Realizada (Telepresen...   13/04/26
6      6  Citação expedido(a) (Para AZUL LINHAS AEREAS B...   12/03/26
7      5  Intimação lido(a) (Para PAULO CESAR AGUIAR NET...   12/03/26
   evento                                                ato data_texto
0     112  Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...   08/05/26
1     108  Intimação expedido(a) (P/ Advgs. de BANCO SANT...   27/04/26
2     107  Intimação expedido(a) (Para BRUNO HENRIQUE GOM...   27/04/26
3     103  Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...   20/03/26
4      97  Disponibilização no Diário da Justiça Eletrôni...   09/03/26
5      96  Intimação expedido(a) (P/ Advgs. de BANCO SANT...   09/03/26
6      95  Intimação expedido(a) (Para BRUNO HENRIQUE GOM...   09/03/26
8      78  Intimação expedido(a) (P/ Advgs. de BANCO SANT...   11/12/25
9      72  Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...   18/11/25
10     70  Intimação expedido(a) (P/ Advgs. de BANCO SANT...   10/11/25
11     66  Intimação expedido(a) (P/ Advgs. de BANCO SANT...   07/11/25
12     65  Intimação expedido(a) (Para BRUNO HENRIQUE GOM...   07/11/25
13     49  Intimação expedido(a) (P/ Advgs. de BANCO SANT...   10/06/25
14     38  Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...   20/05/25
15     36  Intimação lido(a) (Para BANCO SANTANDER BRASIL...   06/05/25
16     35  Intimação expedido(a) Para BRUNO HENRIQUE GOME...   05/05/25
20     17  Citação expedido(a) Para BANCO SANTANDER BRASI...   27/03/25
21      9  Citação expedido(a) (Para BANCO SANTANDER BRAS...   21/03/25
22      6  Citação expedido(a) (Para BANCO SANTANDER BRAS...   21/03/25
  evento                                                ato data_texto
1     20  Audiência de Conciliação Realizada (Telepresen...   07/05/26
2     18          Citação expedido(a) Para BANCO MASTER S A   13/04/26
3     13  Disponibilização no Diário da Justiça Eletrôni...   08/04/26
4     12  Intimação expedido(a) (P/ Advgs. de JOSE HILTO...   08/04/26
6      7  Citação expedido(a) (Para BANCO MASTER S A) Se...   07/04/26
7      6  Intimação lido(a) (Para JOSE HILTON MATOS DOS ...   07/04/26
   evento                                                ato data_texto
0     133  Intimação expedido(a) (P/ Advgs. de TIAGO GOME...   20/03/26
1     126  Audiência de Conciliação Realizada (Telepresen...   27/02/26
2     121  Intimação expedido(a) (P/ Advgs. de TIAGO GOME...   27/01/26
3     120  Intimação expedido(a) (P/ Advgs. de DIOGLEIRY ...   27/01/26
4     114  Audiência de Conciliação Realizada (Telepresen...   27/01/26
5     106  Intimação expedido(a) (P/ Advgs. de DIOGLEIRY ...   26/01/26
6      95  Intimação expedido(a) (P/ Advgs. de DIOGLEIRY ...   19/01/26
7      93  Intimação expedido(a) (P/ Advgs. de TIAGO GOME...   19/01/26
8      80  Intimação expedido(a) (P/ Advgs. de TIAGO GOME...   11/12/25
9      79  Intimação expedido(a) (P/ Advgs. de DIOGLEIRY ...   11/12/25
10     66  Disponibilização no Diário da Justiça Eletrôni...   02/12/25
11     65  Disponibilização no Diário da Justiça Eletrôni...   02/12/25
12     63  Intimação expedido(a) (P/ Advgs. de TIAGO GOME...   02/12/25
13     62  Intimação expedido(a) (P/ Advgs. de DIOGLEIRY ...   02/12/25
14     59  Intimação expedido(a) (P/ Advgs. de TIAGO GOME...   02/12/25
15     58  Intimação expedido(a) (P/ Advgs. de DIOGLEIRY ...   02/12/25
17     50  Intimação expedido(a) (P/ Advgs. de TIAGO GOME...   04/11/25
18     25  Intimação expedido(a) (P/ Advgs. de TIAGO GOME...   07/07/25
19     24  Intimação expedido(a) (P/ Advgs. de DIOGLEIRY ...   07/07/25
   evento                                                ato data_texto
0      56  Devolução sem Leitura De Intimação expedida em...   17/04/26
1      54  Devolução sem Leitura De Intimação expedida em...   19/01/26
2      53  Intimação expedido(a) Para ASSOCIACAO DOS APOS...   13/03/26
3      49  Intimação expedido(a) Para ASSOCIACAO DOS APOS...   15/12/25
4      46  Intimação expedido(a) (P/ Advgs. de LUIZ ANTON...   15/12/25
5      32  Intimação expedido(a) (P/ Advgs. de LUIZ ANTON...   01/09/25
6      26  Devolução sem Leitura De Intimação expedida em...   17/07/25
7      25  Intimação expedido(a) Para ASSOCIACAO DOS APOS...   07/07/25
8      18  Intimação lido(a) (Para LUIZ ANTONIO DE ANDRAD...   14/05/25
12      8  Citação expedido(a) Para ASSOCIACAO DOS APOSEN...   02/04/25
13      5  Intimação lido(a) (Para LUIZ ANTONIO DE ANDRAD...   02/04/25
   evento                                                ato data_texto
0     246  Intimação lido(a) (Para NU PAGAMENTOS S A INST...   05/05/26
1     242  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   24/04/26
2     241  Intimação expedido(a) (Para NU PAGAMENTOS S A ...   24/04/26
3     234  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   16/04/26
4     228  Intimação lido(a) (Para NU PAGAMENTOS S A INST...   14/04/26
5     225  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   10/04/26
6     221  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   01/04/26
7     220  Intimação expedido(a) (Para NU PAGAMENTOS S A ...   01/04/26
8     210  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   27/03/26
9     209  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   27/03/26
10    201  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   19/03/26
11    191  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   17/03/26
12    190  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   17/03/26
13    181  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   17/03/26
14    180  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   17/03/26
15    174  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   12/02/26
16    173  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   12/02/26
17    169  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   14/01/26
18    168  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   14/01/26
19    160  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   01/12/25
20    159  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   01/12/25
21    147  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   23/11/25
22    139  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   14/11/25
23    138  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   14/11/25
24    129  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   14/11/25
25    128  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   14/11/25
26    120  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   13/10/25
27    119  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   13/10/25
28    113  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   01/10/25
29    112  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   01/10/25
30    104  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   08/09/25
31    103  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   08/09/25
32     88  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   05/08/25
33     82  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   24/07/25
34     81  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   24/07/25
35     75  Disponibilização no Diário da Justiça Eletrôni...   23/07/25
36     74  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   23/07/25
38     66  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   21/07/25
39     60  Disponibilização no Diário da Justiça Eletrôni...   10/07/25
40     59  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   10/07/25
42     48  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   02/07/25
43     47  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   02/07/25
44     36  Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...   12/06/25
45     35  Intimação expedido(a) (P/ Advgs. de ERICK ERNA...   12/06/25
47     27  Intimação lido(a) (Para ERICK ERNANDES SANDES)...   09/05/25
49     17  Intimação lido(a) (Para NU PAGAMENTOS S A INST...   26/04/25
50     16  Intimação lido(a) (Para ERICK ERNANDES SANDES)...   26/04/25
51     13  Intimação expedido(a) (Para NU PAGAMENTOS S A ...   15/04/25
54      7  Citação expedido(a) (Para NU PAGAMENTOS S A IN...   12/04/25
55      6  Intimação lido(a) (Para ERICK ERNANDES SANDES)...   12/04/25
  evento                                                ato data_texto
0      8  Intimação lido(a) (Para Núcleo de Atuação MP P...   23/05/26
    evento                                                ato data_texto
0      330  Disponibilização no Diário da Justiça Eletrôni...   25/11/25
1      329  Disponibilização no Diário da Justiça Eletrôni...   25/11/25
2      327  Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...   25/11/25
4      324  Intimação expedido(a) (P/ Advgs. de CLUBE DE S...   25/11/25
6      322  Intimação expedido(a) (P/ Advgs. de CLUBE DE S...   25/11/25
..     ...                                                ...        ...
115     15  Citação lido(a) P/ HAPVIDA ASSISTENCIA MEDICA ...   19/05/23
117     11  Citação expedido(a) Para PRIORIZAR CORRETORA D...   08/05/23
118      8  Citação expedido(a) Para HAPVIDA ASSISTENCIA M...   08/05/23
119      7  Citação expedido(a) Para CLUBE DE SAUDE ADMINI...   08/05/23
120      6  Intimação lido(a) (Para SELMA PEREIRA DIAS) em...   08/05/23

[102 rows x 3 columns]
  evento                                                ato data_texto
0     16  Intimação lido(a) (Para GRUPO CASAS BAHIA S A)...   02/06/26
2     11  Intimação expedido(a) (Para GRUPO CASAS BAHIA ...   20/05/26
3      7  Citação expedido(a) (Para GRUPO CASAS BAHIA S ...   20/05/26
4      6  Intimação lido(a) (Para ANDREA CARLA CARDOSO D...   20/05/26
  evento                                                ato data_texto
0     31  Intimação expedido(a) (Para MIDEA INDUSTRIA E ...   03/06/26
1     30  Intimação expedido(a) (P/ Advgs. de MARCELO DA...   03/06/26
2     23  Citação expedido(a) Para MIDEA INDUSTRIA E COM...   29/05/26
3     15  Intimação expedido(a) (P/ Advgs. de MARCELO DA...   26/05/26
4     13  Intimação expedido(a) (Para MIDEA INDUSTRIA E ...   26/05/26
5      6  Citação expedido(a) (Para MIDEA INDUSTRIA E CO...   25/05/26
6      5  Intimação lido(a) (Para MARCELO DANIEL MELO AL...   25/05/26
  evento                                                ato data_texto
0      6  Intimação lido(a) (Para ROGERIO FREITAS CAVALC...   02/06/26
   evento                                                ato data_texto
0      56  Intimação expedido(a) (P/ Advgs. de FLORISVALD...   05/11/25
1      46  Intimação expedido(a) (P/ Advgs. de ASSOCIACAO...   21/08/25
2      38  Intimação expedido(a) (P/ Advgs. de FLORISVALD...   02/08/25
3      28  Intimação expedido(a) (P/ Advgs. de FLORISVALD...   02/07/25
4      21  Citação lido(a) P/ ASSOCIACAO DE APOSENTADOS M...   14/06/25

In [18]:

        
        
abc

NameError: name 'abc' is not defined

In [ ]:
processos = {}
df_relacoes_total = []

for process_json in pasta.glob('*.json'):

    with open(process_json, 'r', encoding='utf-8') as f:
        dados = json.load(f)

    p = process_json.stem

    # =========================
    # MOVIMENTAÇÕES
    # =========================
    df = pd.DataFrame(dados['movimentacoes'])
    processos[p] = df

    df_expedidas = expedidas(df)
    df_lidas = lidas(df)
    df_outros_referenciados = referenciados(df)

    df_expedidas['tipo'] = df_expedidas['ato'].apply(tipo_comunicacao)
    df_lidas['tipo'] = df_lidas['ato'].apply(tipo_comunicacao)

    chave(df_expedidas, df_lidas)
    _relacoes = relacoes(df_expedidas, df_lidas)

    df_relacoes = pd.DataFrame({
        'evento_expedido': _relacoes['evento_expedido'],
        'data_expedicao': _relacoes['data_texto_expedido'],
        'ato_expedido': _relacoes['ato_expedido'],
        'destinatario': _relacoes['destinatario'],
        'meio': _relacoes['meio_real'],
        'canal': _relacoes['meio_comunicacao_expedido'],
        'ato_lido': _relacoes['ato_lido'],
        'data_leitura': _relacoes['data_leitura_str_lido'],
        'evento_lido': _relacoes['evento_lido'],
        'prazo': _relacoes['ato_expedido'].str.extract(r'(\d+\s*dias?)', expand=False)
    })

    df_relacoes = origem(df_relacoes)

    # 🔑 CHAVE ÚNICA GLOBAL
    df_relacoes['key'] = df_relacoes['destinatario'].apply(normalizar_nome)

    # =========================
    # PARTES
    # =========================
    # df_partes = pd.DataFrame(dados['partes'])

    df_partes['key'] = df_partes['nome_normalizado_limpo']#.apply(normalizar_nome)
    df_partes['revelia'] = df_partes['nome'].apply(marcar_revelia)

    df_partes['canais_disponiveis'] = df_partes.apply(canais_disponiveis, axis=1)
    df_partes['canais_disponiveis_lista'] = df_partes.apply(lista_canais_disponiveis, axis=1)

    df_partes['habilitada_receber'] = (
        df_partes['tem_advogado'].fillna(False) |
        df_partes['domicilio_cnj'].fillna(False) |
        df_partes['recebe_intimacao_email'].fillna(False)
    )

    # =========================
    # STATUS PROCESSO
    # =========================
    processo_ok, status = status_processo(df_partes)
    df_relacoes['automatiza'] = status

    # =========================
    # MERGE PARTES ↔ RELAÇÕES
    # =========================
    # df_relacoes = df_relacoes.merge(
    #     df_partes[[
    #         'key',
    #         'revelia',
    #         'email',
    #         'tel',
    #         'habilitada_receber'
    #     ]],
    #     on='key',
    #     how='left'
    # )
    df_relacoes.merge(df_partes, on='key', how='left')

    # =========================
    # CANAIS HISTÓRICOS (CORRETO)
    # =========================
    canais_historicos = (
        df_expedidas.groupby('destinatario')['meio_real']
        .apply(lambda x: ', '.join(sorted(set(filter(pd.notna, x)))))
        .reset_index()
    )

    canais_historicos['key'] = canais_historicos['destinatario'].apply(normalizar_nome)

    df_relacoes = df_relacoes.merge(
        canais_historicos[['key', 'meio_real']],
        on='key',
        how='left'
    )

    df_relacoes = df_relacoes.rename(columns={'meio_real': 'canais_historicos'})

    # =========================
    # CANAL CONFIRMADO (USO REAL)
    # =========================
    canais_confirmados = (
        df_relacoes.groupby('destinatario')['meio']
        .apply(lambda x: ', '.join(sorted(set(filter(pd.notna, x)))))
        .reset_index()
    )

    canais_confirmados['key'] = canais_confirmados['destinatario'].apply(normalizar_nome)

    df_partes = df_partes.merge(
        canais_confirmados[['key', 'meio']],
        on='key',
        how='left'
    )

    df_partes = df_partes.rename(columns={'meio': 'canal_confirmado'})

    # =========================
    # FINAL
    # =========================
    df_relacoes_total.append(df_relacoes)
    # print(
    #     f"Processo: {numero} | "
    #     f"Movimentações: {len(df)}"
    # )
    df_relacoes.drop(['automatiza', 'key'], axis=1, inplace=True)
    display(df_relacoes.set_index('evento_expedido'))
    print(len(df_relacoes))

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
60,28/04/26,Intimação expedido(a) Para TV VINHOS LTDA *Ref...,tv vinhos ltda,pessoal,None,Intimação lido(a) (Para TV VINHOS LTDA) em 11/...,2026-05-11,62,NaN,Ato ordinatório praticado,28/04/26,pessoal
58,28/04/26,Intimação expedido(a) (Para PAYOUT PAGAMENTOS ...,payout pagamentos inteligentes ltda,pessoal,None,Intimação lido(a) (Para PAYOUT PAGAMENTOS INTE...,2026-05-08,61,15 dias,Ato ordinatório praticado,28/04/26,"advogado, pessoal"
14,21/01/26,Intimação expedido(a) (Para PAYOUT PAGAMENTOS ...,payout pagamentos inteligentes ltda,pessoal,None,Intimação lido(a) (Para PAYOUT PAGAMENTOS INTE...,2026-02-02,25,NaN,Intimação à disposição,21/01/26,"advogado, pessoal"

3

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
219,09/03/26,Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...,amil assistencia medica internacional s a,advogado,domicilio_cnj,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,2026-03-19,223,5 dias,Concedida a Medida Liminar,09/03/26,"advogado, pessoal"
218,09/03/26,Intimação expedido(a) (Para AMIL ASSISTENCIA M...,amil assistencia medica internacional s a,pessoal,None,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,2026-03-19,223,5 dias,Concedida a Medida Liminar,09/03/26,"advogado, pessoal"
174,10/10/25,Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...,amil assistencia medica internacional s a,advogado,domicilio_cnj,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,2025-10-20,182,5 dias,Extinta a execução ou o cumprimento da sentença,10/10/25,"advogado, pessoal"
173,10/10/25,Intimação expedido(a) (Para AMIL ASSISTENCIA M...,amil assistencia medica internacional s a,pessoal,None,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,2025-10-20,182,5 dias,Extinta a execução ou o cumprimento da sentença,10/10/25,"advogado, pessoal"
38,06/05/25,Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...,amil assistencia medica internacional s a,advogado,domicilio_cnj,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,2025-05-16,41,10 dias,Julgada procedente a ação,06/05/25,"advogado, pessoal"
37,06/05/25,Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...,raquel lemos de oliveira,advogado,domicilio_cnj,Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...,2025-05-16,40,NaN,Julgada procedente a ação,06/05/25,"advogado, pessoal"
23,17/02/25,Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...,amil assistencia medica internacional s a,advogado,domicilio_cnj,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,2025-03-06,27,10 dias,Intimação à disposição,17/02/25,"advogado, pessoal"
22,17/02/25,Intimação expedido(a) (P/ Advgs. de RAQUEL LEM...,raquel lemos de oliveira,advogado,domicilio_cnj,Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...,2025-03-06,26,10 dias,Intimação à disposição,17/02/25,"advogado, pessoal"

8

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
117,30/10/24,Intimação expedido(a) (P/ Advgs. de EDILEIDE D...,edileide da silva lima,advogado,domicilio_cnj,Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...,2024-10-31,118,10 dias,Intimação à disposição,30/10/24,advogado
113,16/10/24,Intimação expedido(a) (P/ Advgs. de EDILEIDE D...,edileide da silva lima,advogado,domicilio_cnj,Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...,2024-10-24,114,5 dias,Proferido despacho de mero expediente,16/10/24,advogado
87,05/06/24,Intimação expedido(a) (P/ Advgs. de EDILEIDE D...,edileide da silva lima,advogado,domicilio_cnj,Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...,2024-06-11,93,5 dias,Intimação à disposição,05/06/24,advogado
17,22/03/23,Intimação expedido(a) (P/ Advgs. de EDILEIDE D...,edileide da silva lima,advogado,domicilio_cnj,Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...,2023-03-22,19,10 dias,Julgada procedente em parte a ação,22/03/23,advogado

4

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
149,17/04/24,Intimação expedido(a) (P/ Advgs. de MARIA LUCI...,maria lucia teixeira de oliveira,advogado,domicilio_cnj,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,2024-04-29,152,10 dias,Acolhida em parte a impugnação ao cumprimento ...,17/04/24,"advogado, pessoal"
150,17/04/24,Intimação expedido(a) (P/ Advgs. de BANCO BRAD...,banco bradesco financiamentos s a,advogado,domicilio_cnj,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,2024-04-25,151,10 dias,Acolhida em parte a impugnação ao cumprimento ...,17/04/24,"advogado, pessoal"
137,27/02/24,Intimação expedido(a) (P/ Advgs. de MARIA LUCI...,maria lucia teixeira de oliveira,advogado,domicilio_cnj,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,2024-03-08,140,5 dias,Proferido despacho de mero expediente,27/02/24,"advogado, pessoal"
138,27/02/24,Intimação expedido(a) (P/ Advgs. de BANCO BRAD...,banco bradesco financiamentos s a,advogado,domicilio_cnj,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,2024-03-06,139,5 dias,Proferido despacho de mero expediente,27/02/24,"advogado, pessoal"
122,12/09/23,Intimação expedido(a) (P/ Advgs. de BANCO BRAD...,banco bradesco financiamentos s a,advogado,domicilio_cnj,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,2023-09-20,123,10 dias,Intimação à disposição,12/09/23,"advogado, pessoal"
103,14/07/23,Intimação expedido(a) (P/ Advgs. de MARIA LUCI...,maria lucia teixeira de oliveira,advogado,domicilio_cnj,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,2023-07-24,107,NaN,Proferido despacho de mero expediente,14/07/23,"advogado, pessoal"
104,14/07/23,Intimação expedido(a) (P/ Advgs. de BANCO BRAD...,banco bradesco financiamentos s a,advogado,domicilio_cnj,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,2023-07-21,106,NaN,Proferido despacho de mero expediente,14/07/23,"advogado, pessoal"
91,16/06/23,Intimação expedido(a) (P/ Advgs. de BANCO BRAD...,banco bradesco financiamentos s a,advogado,domicilio_cnj,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,2023-06-26,95,15 dias,Intimação à disposição,16/06/23,"advogado, pessoal"
62,31/08/22,Intimação expedido(a) (P/ Advgs. de MARIA LUCI...,maria lucia teixeira de oliveira,advogado,domicilio_cnj,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,2022-09-01,63,5 dias,Intimação à disposição,31/08/22,"advogado, pessoal"
43,11/07/22,Intimação expedido(a) (P/ Advgs. de MARIA LUCI...,maria lucia teixeira de oliveira,advogado,domicilio_cnj,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,2022-07-11,44,5 dias,Juntada de Certidão,11/07/22,"advogado, pessoal"
32,08/06/22,Intimação expedido(a) (P/ Advgs. de MARIA LUCI...,maria lucia teixeira de oliveira,advogado,domicilio_cnj,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,2022-06-20,35,NaN,Intimação à disposição,08/06/22,"advogado, pessoal"
33,08/06/22,Intimação expedido(a) (P/ Advgs. de BANCO BRAD...,banco bradesco financiamentos s a,advogado,domicilio_cnj,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,2022-06-10,34,NaN,Intimação à disposição,08/06/22,"advogado, pessoal"
11,17/03/22,Intimação expedido(a) (P/ Advgs. de MARIA LUCI...,maria lucia teixeira de oliveira,advogado,domicilio_cnj,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,2022-03-24,13,5 dias,Intimação à disposição,17/03/22,"advogado, pessoal"

13

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
107,27/04/26,Intimação expedido(a) (Para BRUNO HENRIQUE GOM...,bruno henrique gomes bezerra,pessoal,None,Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...,2026-05-07,112,5 dias,Intimação à disposição,27/04/26,pessoal
65,07/11/25,Intimação expedido(a) (Para BRUNO HENRIQUE GOM...,bruno henrique gomes bezerra,pessoal,None,Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...,2025-11-17,72,NaN,Documento analisado,07/11/25,pessoal

2

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
15,13/05/25,Intimação expedido(a) (P/ Advgs. de LUIZ ANTON...,luiz antonio de andrade,advogado,domicilio_cnj,Intimação lido(a) (Para LUIZ ANTONIO DE ANDRAD...,2025-05-14,18,NaN,Julgada procedente a ação,13/05/25,advogado

1

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
242,24/04/26,Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...,nu pagamentos s a instituicao de pagamento,advogado,domicilio_cnj,Intimação lido(a) (Para NU PAGAMENTOS S A INST...,2026-05-04,246,15 dias,Proferido despacho de mero expediente,24/04/26,"advogado, pessoal"
241,24/04/26,Intimação expedido(a) (Para NU PAGAMENTOS S A ...,nu pagamentos s a instituicao de pagamento,pessoal,None,Intimação lido(a) (Para NU PAGAMENTOS S A INST...,2026-05-04,246,15 dias,Proferido despacho de mero expediente,24/04/26,"advogado, pessoal"
221,01/04/26,Intimação expedido(a) (P/ Advgs. de NU PAGAMEN...,nu pagamentos s a instituicao de pagamento,advogado,domicilio_cnj,Intimação lido(a) (Para NU PAGAMENTOS S A INST...,2026-04-13,228,5 dias,Proferido despacho de mero expediente,01/04/26,"advogado, pessoal"
220,01/04/26,Intimação expedido(a) (Para NU PAGAMENTOS S A ...,nu pagamentos s a instituicao de pagamento,pessoal,None,Intimação lido(a) (Para NU PAGAMENTOS S A INST...,2026-04-13,228,5 dias,Proferido despacho de mero expediente,01/04/26,"advogado, pessoal"
25,28/04/25,Intimação expedido(a) (P/ Advgs. de ERICK ERNA...,erick ernandes sandes,advogado,domicilio_cnj,Intimação lido(a) (Para ERICK ERNANDES SANDES)...,2025-05-08,27,NaN,Intimação à disposição,28/04/25,"advogado, pessoal"
13,15/04/25,Intimação expedido(a) (Para NU PAGAMENTOS S A ...,nu pagamentos s a instituicao de pagamento,pessoal,None,Intimação lido(a) (Para NU PAGAMENTOS S A INST...,2025-04-25,17,NaN,Ato ordinatório praticado,15/04/25,"advogado, pessoal"
12,15/04/25,Intimação expedido(a) (P/ Advgs. de ERICK ERNA...,erick ernandes sandes,advogado,domicilio_cnj,Intimação lido(a) (Para ERICK ERNANDES SANDES)...,2025-04-25,16,NaN,Ato ordinatório praticado,15/04/25,"advogado, pessoal"

7

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
301,06/08/25,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2025-08-18,314,10 dias,Intimação à disposição,06/08/25,pessoal
221,06/03/25,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros ltda,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2025-03-17,228,15 dias,Intimação à disposição,06/03/25,"advogado, pessoal"
219,06/03/25,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda.,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2025-03-17,227,15 dias,Intimação à disposição,06/03/25,"advogado, pessoal"
220,06/03/25,Intimação expedido(a) (Para HAPVIDA ASSISTENCI...,hapvida assistencia medica s a,pessoal,None,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,2025-03-12,226,15 dias,Intimação à disposição,06/03/25,"advogado, pessoal"
209,24/02/25,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2025-03-06,225,NaN,Transitado em Julgado,24/02/25,pessoal
208,24/02/25,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros ltda,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2025-03-06,224,NaN,Transitado em Julgado,24/02/25,"advogado, pessoal"
207,24/02/25,Intimação expedido(a) (Para HAPVIDA ASSISTENCI...,hapvida assistencia medica s a,pessoal,None,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,2025-03-06,223,NaN,Transitado em Julgado,24/02/25,"advogado, pessoal"
206,24/02/25,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda.,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2025-03-06,222,NaN,Transitado em Julgado,24/02/25,"advogado, pessoal"
193,20/01/25,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2025-01-30,200,15 dias,"Conhecido o recurso de ""parte"" e não-provido",20/01/25,pessoal
192,20/01/25,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros ltda,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2025-01-30,199,15 dias,"Conhecido o recurso de ""parte"" e não-provido",20/01/25,"advogado, pessoal"
191,20/01/25,Intimação expedido(a) (Para HAPVIDA ASSISTENCI...,hapvida assistencia medica s a,pessoal,None,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,2025-01-30,198,15 dias,"Conhecido o recurso de ""parte"" e não-provido",20/01/25,"advogado, pessoal"
190,20/01/25,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda.,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2025-01-30,197,15 dias,"Conhecido o recurso de ""parte"" e não-provido",20/01/25,"advogado, pessoal"
179,20/11/24,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2024-12-02,185,15 dias,Negado seguimento a Recurso,20/11/24,pessoal
178,20/11/24,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros ltda,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2024-12-02,184,15 dias,Negado seguimento a Recurso,20/11/24,"advogado, pessoal"
176,20/11/24,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda.,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2024-12-02,183,15 dias,Negado seguimento a Recurso,20/11/24,"advogado, pessoal"
160,16/10/24,Intimação expedido(a) (Para HAPVIDA ASSISTENCI...,hapvida assistencia medica s a,pessoal,None,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,2024-10-29,167,15 dias,Documento analisado,16/10/24,"advogado, pessoal"
159,16/10/24,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda.,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2024-10-29,166,15 dias,Documento analisado,16/10/24,"advogado, pessoal"
147,14/10/24,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2024-10-24,165,NaN,Transitado em Julgado,14/10/24,pessoal
146,14/10/24,Intimação expedido(a) (Para HAPVIDA ASSISTENCI...,hapvida assistencia medica s a,pessoal,None,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,2024-10-24,164,NaN,Transitado em Julgado,14/10/24,"advogado, pessoal"
145,14/10/24,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros ltda,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2024-10-24,163,NaN,Transitado em Julgado,14/10/24,"advogado, pessoal"
144,14/10/24,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda.,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2024-10-24,162,NaN,Transitado em Julgado,14/10/24,"advogado, pessoal"
128,09/09/24,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2024-09-19,132,15 dias,Embargos de Declaração Não-acolhidos,09/09/24,pessoal
127,09/09/24,Intimação expedido(a) (Para HAPVIDA ASSISTENCI...,hapvida assistencia medica s a,pessoal,None,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,2024-09-19,131,15 dias,Embargos de Declaração Não-acolhidos,09/09/24,"advogado, pessoal"
126,09/09/24,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros ltda,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2024-09-19,130,15 dias,Embargos de Declaração Não-acolhidos,09/09/24,"advogado, pessoal"
125,09/09/24,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda.,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2024-09-19,129,15 dias,Embargos de Declaração Não-acolhidos,09/09/24,"advogado, pessoal"
116,20/08/24,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2024-08-30,120,15 dias,"Conhecido o recurso de ""parte"" e não-provido",20/08/24,pessoal
115,20/08/24,Intimação expedido(a) (Para HAPVIDA ASSISTENCI...,hapvida assistencia medica s.a.,pessoal,None,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,2024-08-30,119,15 dias,"Conhecido o recurso de ""parte"" e não-provido",20/08/24,pessoal
114,20/08/24,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros ltda,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2024-08-30,118,15 dias,"Conhecido o recurso de ""parte"" e não-provido",20/08/24,"advogado, pessoal"
113,20/08/24,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda.,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2024-08-30,117,15 dias,"Conhecido o recurso de ""parte"" e não-provido",20/08/24,"advogado, pessoal"
97,09/07/24,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2024-07-19,98,10 dias,Intimação à disposição,09/07/24,pessoal
91,18/06/24,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros ltda,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2024-06-28,92,2 dias,Intimação à disposição,18/06/24,"advogado, pessoal"
80,22/05/24,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2024-06-03,83,5 dias,Intimação à disposição,22/05/24,"advogado, pessoal"
78,22/05/24,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2024-06-03,82,5 dias,Intimação à disposição,22/05/24,pessoal
71,11/04/24,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2024-04-22,72,10 dias,Documento analisado,11/04/24,pessoal
64,14/03/24,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2024-03-25,68,NaN,Embargos de Declaração Não-acolhidos,14/03/24,"advogado, pessoal"
63,14/03/24,Intimação expedido(a) (Para HAPVIDA ASSISTENCI...,hapvida assistencia medica s.a.,pessoal,None,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,2024-03-25,67,NaN,Embargos de Declaração Não-acolhidos,14/03/24,pessoal
62,14/03/24,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda.,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2024-03-25,66,NaN,Embargos de Declaração Não-acolhidos,14/03/24,"advogado, pessoal"
61,14/03/24,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2024-03-25,65,NaN,Embargos de Declaração Não-acolhidos,14/03/24,pessoal
50,19/10/23,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2023-10-30,51,5 dias,Documento analisado,19/10/23,pessoal
33,17/08/23,Intimação expedido(a) (P/ Advgs. de PRIORIZAR ...,priorizar corretora de seguros,advogado,domicilio_cnj,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,2023-08-28,37,15 dias,Documento analisado,17/08/23,"advogado, pessoal"
32,17/08/23,Intimação expedido(a) (Para HAPVIDA ASSISTENCI...,hapvida assistencia medica ltda,pessoal,None,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,2023-08-28,36,15 dias,Documento analisado,17/08/23,pessoal
31,17/08/23,Intimação expedido(a) (P/ Advgs. de CLUBE DE S...,clube de saude administradora de beneficios ltda,advogado,domicilio_cnj,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,2023-08-28,35,15 dias,Documento analisado,17/08/23,"advogado, pessoal"
30,17/08/23,Intimação expedido(a) (Para SELMA PEREIRA DIAS...,selma pereira dias,pessoal,None,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,2023-08-28,34,15 dias,Documento analisado,17/08/23,pessoal

43

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
11,20/05/26,Intimação expedido(a) (Para GRUPO CASAS BAHIA ...,grupo casas bahia s a,pessoal,None,Intimação lido(a) (Para GRUPO CASAS BAHIA S A)...,2026-06-01,16,5 dias,Ato ordinatório praticado,20/05/26,pessoal

1

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
61,07/07/25,Intimação expedido(a) (Para COMPANHIA DE SEGUR...,companhia de seguros previdencia do sul,pessoal,None,Intimação lido(a) (Para COMPANHIA DE SEGUROS P...,2025-07-17,77,NaN,Intimação para Videoconferência à disposição,07/07/25,"advogado, pessoal"
47,07/07/25,Intimação expedido(a) (Para COMPANHIA DE SEGUR...,companhia de seguros previdencia do sul,pessoal,None,Intimação lido(a) (Para COMPANHIA DE SEGUROS P...,2025-07-17,77,NaN,Intimação para Videoconferência à disposição,07/07/25,"advogado, pessoal"
61,07/07/25,Intimação expedido(a) (Para COMPANHIA DE SEGUR...,companhia de seguros previdencia do sul,pessoal,None,Intimação lido(a) (Para COMPANHIA DE SEGUROS P...,2025-07-17,76,NaN,Intimação à disposição,07/07/25,"advogado, pessoal"
47,07/07/25,Intimação expedido(a) (Para COMPANHIA DE SEGUR...,companhia de seguros previdencia do sul,pessoal,None,Intimação lido(a) (Para COMPANHIA DE SEGUROS P...,2025-07-17,76,NaN,Intimação à disposição,07/07/25,"advogado, pessoal"

4

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
300,21/05/26,Intimação expedido(a) (P/ Advgs. de CAIXA DE A...,caixa de assistencia dos funcionarios do banco...,advogado,domicilio_cnj,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2026-06-01,303,15 dias,Proferido despacho de mero expediente,21/05/26,"advogado, pessoal"
298,21/05/26,Intimação expedido(a) (P/ Advgs. de CAIXA DE A...,caixa de assistencia dos funcionarios do banco...,advogado,domicilio_cnj,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2026-06-01,303,10 dias,Proferido despacho de mero expediente,21/05/26,"advogado, pessoal"
297,21/05/26,Intimação expedido(a) (Para CAIXA DE ASSISTENC...,caixa de assistencia dos funcionarios do banco...,pessoal,None,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2026-06-01,303,10 dias,Proferido despacho de mero expediente,21/05/26,"advogado, pessoal"
252,13/04/26,Intimação expedido(a) (P/ Advgs. de CAIXA DE A...,caixa de assistencia dos funcionarios do banco...,advogado,domicilio_cnj,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2026-04-23,259,5 dias,Decisão de Saneamento e de Organização do Proc...,13/04/26,"advogado, pessoal"
251,13/04/26,Intimação expedido(a) (Para CAIXA DE ASSISTENC...,caixa de assistencia dos funcionarios do banco...,pessoal,None,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2026-04-23,259,5 dias,Decisão de Saneamento e de Organização do Proc...,13/04/26,"advogado, pessoal"
236,31/03/26,Intimação expedido(a) (Para CAIXA DE ASSISTENC...,caixa de assistencia dos funcionarios do banco...,pessoal,None,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2026-04-01,238,5 dias,Intimação à disposição,31/03/26,"advogado, pessoal"
186,19/02/26,Intimação expedido(a) (P/ Advgs. de CAIXA DE A...,caixa de assistencia dos funcionarios do banco...,advogado,domicilio_cnj,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2026-03-02,197,5 dias,Concedida a Medida Liminar,19/02/26,"advogado, pessoal"
185,19/02/26,Intimação expedido(a) (Para CAIXA DE ASSISTENC...,caixa de assistencia dos funcionarios do banco...,pessoal,None,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2026-03-02,197,5 dias,Concedida a Medida Liminar,19/02/26,"advogado, pessoal"
181,19/02/26,Intimação expedido(a) (P/ Advgs. de CAIXA DE A...,caixa de assistencia dos funcionarios do banco...,advogado,domicilio_cnj,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2026-03-02,197,5 dias,Concedida a Medida Liminar,19/02/26,"advogado, pessoal"
46,01/07/25,Intimação expedido(a) (P/ Advgs. de CAIXA DE A...,caixa de assistencia dos funcionarios do banco...,advogado,domicilio_cnj,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2025-07-11,58,3 dias,Concedida a Medida Liminar,01/07/25,"advogado, pessoal"
45,01/07/25,Intimação expedido(a) (Para CAIXA DE ASSISTENC...,caixa de assistencia dos funcionarios do banco...,pessoal,None,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2025-07-11,58,3 dias,Concedida a Medida Liminar,01/07/25,"advogado, pessoal"
25,05/06/25,Intimação expedido(a) (P/ Advgs. de CAIXA DE A...,caixa de assistencia dos funcionarios do banco...,advogado,domicilio_cnj,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2025-06-16,27,2 dias,Proferido despacho de mero expediente,05/06/25,"advogado, pessoal"
24,05/06/25,Intimação expedido(a) (Para CAIXA DE ASSISTENC...,caixa de assistencia dos funcionarios do banco...,pessoal,None,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,2025-06-16,27,2 dias,Proferido despacho de mero expediente,05/06/25,"advogado, pessoal"
13,21/05/25,Disponibilização no Diário da Justiça Eletrôni...,floriza maria sena fernandes,pessoal,domicilio_cnj,Intimação lido(a) (Para FLORIZA MARIA SENA FER...,2025-05-21,5,NaN,Audiência de Conciliação Designada,21/05/25,"advogado, pessoal"
10,21/05/25,Intimação expedido(a) (P/ Advgs. de FLORIZA MA...,floriza maria sena fernandes,advogado,domicilio_cnj,Intimação lido(a) (Para FLORIZA MARIA SENA FER...,2025-05-21,5,NaN,Audiência de Conciliação Designada,21/05/25,"advogado, pessoal"

15

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
22,11/07/25,Intimação expedido(a) Para JOSE ALDSON FRANCA ...,jose aldson franca mina,pessoal,None,Intimação lido(a) (Para JOSE ALDSON FRANCA MIN...,2025-07-17,26,NaN,Julgada procedente em parte a ação,11/07/25,pessoal
20,11/07/25,Intimação expedido(a) (P/ Advgs. de GJT PAULO ...,gjt paulo afonso aluguel de equipamentos ltda,advogado,domicilio_cnj,Intimação lido(a) (Para GJT PAULO AFONSO ALUGU...,2025-07-21,25,10 dias,Julgada procedente em parte a ação,11/07/25,"advogado, pessoal"
19,11/07/25,Intimação expedido(a) (Para GJT PAULO AFONSO A...,gjt paulo afonso aluguel de equipamentos ltda,pessoal,None,Intimação lido(a) (Para GJT PAULO AFONSO ALUGU...,2025-07-21,25,10 dias,Julgada procedente em parte a ação,11/07/25,"advogado, pessoal"
17,11/07/25,Intimação expedido(a) (P/ Advgs. de GJT PAULO ...,gjt paulo afonso aluguel de equipamentos ltda,advogado,domicilio_cnj,Intimação lido(a) (Para GJT PAULO AFONSO ALUGU...,2025-07-21,25,10 dias,Julgada procedente em parte a ação,11/07/25,"advogado, pessoal"

4

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
157,12/05/25,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2025-05-12,158,5 dias,Intimação à disposição,12/05/25,"advogado, pessoal"
142,03/12/24,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2024-12-13,143,5 dias,Documento analisado,03/12/24,"advogado, pessoal"
138,25/11/24,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2024-12-02,139,5 dias,Intimação à disposição,25/11/24,"advogado, pessoal"
127,01/10/24,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2024-10-01,128,5 dias,Intimação à disposição,01/10/24,"advogado, pessoal"
95,24/04/24,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2024-05-06,96,15 dias,Documento analisado,24/04/24,"advogado, pessoal"
83,26/03/24,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2024-04-05,86,10 dias,Julgada procedente em parte a ação,26/03/24,"advogado, pessoal"
82,26/03/24,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2024-03-27,85,10 dias,Julgada procedente em parte a ação,26/03/24,"advogado, pessoal"
71,21/11/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-12-01,75,NaN,Intimação para Videoconferência à disposição,21/11/23,"advogado, pessoal"
66,21/11/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-12-01,75,NaN,Intimação para Videoconferência à disposição,21/11/23,"advogado, pessoal"
71,21/11/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-12-01,74,NaN,Proferido despacho de mero expediente,21/11/23,"advogado, pessoal"
66,21/11/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-12-01,74,NaN,Proferido despacho de mero expediente,21/11/23,"advogado, pessoal"
70,21/11/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-11-23,73,NaN,Intimação para Videoconferência à disposição,21/11/23,"advogado, pessoal"
65,21/11/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-11-23,73,NaN,Intimação para Videoconferência à disposição,21/11/23,"advogado, pessoal"
70,21/11/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-11-21,67,NaN,Proferido despacho de mero expediente,21/11/23,"advogado, pessoal"
65,21/11/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-11-21,67,NaN,Proferido despacho de mero expediente,21/11/23,"advogado, pessoal"
56,06/11/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-11-16,59,NaN,Intimação para Videoconferência à disposição,06/11/23,"advogado, pessoal"
55,06/11/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-11-06,58,NaN,Intimação para Videoconferência à disposição,06/11/23,"advogado, pessoal"
46,03/10/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-10-16,51,NaN,Intimação para Videoconferência à disposição,03/10/23,"advogado, pessoal"
39,03/10/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-10-16,51,NaN,Intimação para Videoconferência à disposição,03/10/23,"advogado, pessoal"
46,03/10/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-10-16,50,NaN,Intimação para Videoconferência à disposição,03/10/23,"advogado, pessoal"
39,03/10/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-10-16,50,NaN,Intimação para Videoconferência à disposição,03/10/23,"advogado, pessoal"
45,03/10/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-10-05,49,NaN,Intimação para Videoconferência à disposição,03/10/23,"advogado, pessoal"
38,03/10/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-10-05,49,NaN,Intimação para Videoconferência à disposição,03/10/23,"advogado, pessoal"
45,03/10/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-10-05,48,NaN,Intimação para Videoconferência à disposição,03/10/23,"advogado, pessoal"
38,03/10/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-10-05,48,NaN,Intimação para Videoconferência à disposição,03/10/23,"advogado, pessoal"
24,24/08/23,Intimação expedido(a) (P/ Advgs. de INSTITUTO ...,instituto em belleza aracaju ltda,advogado,domicilio_cnj,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,2023-08-25,27,NaN,Intimação para Videoconferência à disposição,24/08/23,"advogado, pessoal"
23,24/08/23,Intimação expedido(a) (P/ Advgs. de SANDRA PAT...,sandra patricia restrepo pontes,advogado,domicilio_cnj,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,2023-08-24,26,NaN,Intimação para Videoconferência à disposição,24/08/23,"advogado, pessoal"

27

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
11,13/06/25,Intimação expedido(a) (P/ Advgs. de KAMILLA SO...,kamilla souza gomes da costa,advogado,domicilio_cnj,Intimação lido(a) (Para KAMILLA SOUZA GOMES DA...,2025-06-13,6,5 dias,Audiência de Conciliação Designada,13/06/25,advogado

1

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
41,01/09/25,Intimação expedido(a) Para JERSON UBIRATAN DA ...,jerson ubiratan da silva barros,pessoal,None,Intimação lido(a) (Para JERSON UBIRATAN DA SIL...,2025-09-05,57,NaN,Intimação à disposição,01/09/25,pessoal

1

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
258,28/04/26,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2026-04-29,259,NaN,Autos entregues em carga ao destino,28/04/26,
235,07/04/26,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2026-04-13,246,NaN,Autos entregues em carga ao destino,07/04/26,
233,07/04/26,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2026-04-13,246,NaN,Autos entregues em carga ao destino,07/04/26,
216,15/12/25,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2026-01-21,218,NaN,Autos entregues em carga ao destino,15/12/25,

4

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
28,14/01/25,Intimação expedido(a) (P/ Advgs. de VOLTZ MOTO...,voltz motors do brasil comercio de motocicleta...,advogado,domicilio_cnj,Intimação lido(a) (Para VOLTZ MOTORS DO BRASIL...,2025-01-24,30,10 dias,Intimação à disposição,14/01/25,"advogado, pessoal"
27,14/01/25,Intimação expedido(a) (P/ Advgs. de HEVITON OL...,heviton oliveira rodrigues,advogado,domicilio_cnj,Intimação lido(a) (Para HEVITON OLIVEIRA RODRI...,2025-01-24,29,10 dias,Intimação à disposição,14/01/25,"advogado, pessoal"

2

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
60,10/06/24,Intimação expedido(a) (P/ Advgs. de ROBSON DE ...,robson de oliveira silva,advogado,domicilio_cnj,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-06-20,61,15 dias,Intimação à disposição,10/06/24,"advogado, pessoal"
48,25/04/24,Intimação expedido(a) (P/ Advgs. de ROBSON DE ...,robson de oliveira silva,advogado,domicilio_cnj,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-05-06,51,10 dias,Julgada procedente em parte a ação,25/04/24,"advogado, pessoal"
47,25/04/24,Intimação expedido(a) (P/ Advgs. de FABIANA DO...,fabiana dos santos silva gomes marmoraria,advogado,domicilio_cnj,Intimação lido(a) (Para FABIANA DOS SANTOS SIL...,2024-04-25,50,10 dias,Julgada procedente em parte a ação,25/04/24,advogado
33,06/03/24,Intimação expedido(a) Para ROBSON DE OLIVEIRA ...,robson de oliveira silva,pessoal,None,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-03-18,44,NaN,Intimação para Videoconferência à disposição,06/03/24,"advogado, pessoal"
32,06/03/24,Intimação expedido(a) Para ROBSON DE OLIVEIRA ...,robson de oliveira silva,pessoal,None,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-03-18,44,NaN,Intimação para Videoconferência à disposição,06/03/24,"advogado, pessoal"
31,06/03/24,Intimação expedido(a) Para ROBSON DE OLIVEIRA ...,robson de oliveira silva,pessoal,None,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-03-18,44,NaN,Intimação para Videoconferência à disposição,06/03/24,"advogado, pessoal"
33,06/03/24,Intimação expedido(a) Para ROBSON DE OLIVEIRA ...,robson de oliveira silva,pessoal,None,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-03-18,42,NaN,Intimação para Videoconferência à disposição,06/03/24,"advogado, pessoal"
32,06/03/24,Intimação expedido(a) Para ROBSON DE OLIVEIRA ...,robson de oliveira silva,pessoal,None,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-03-18,42,NaN,Intimação para Videoconferência à disposição,06/03/24,"advogado, pessoal"
31,06/03/24,Intimação expedido(a) Para ROBSON DE OLIVEIRA ...,robson de oliveira silva,pessoal,None,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-03-18,42,NaN,Intimação para Videoconferência à disposição,06/03/24,"advogado, pessoal"
33,06/03/24,Intimação expedido(a) Para ROBSON DE OLIVEIRA ...,robson de oliveira silva,pessoal,None,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-03-18,40,NaN,Proferido despacho de mero expediente,06/03/24,"advogado, pessoal"
32,06/03/24,Intimação expedido(a) Para ROBSON DE OLIVEIRA ...,robson de oliveira silva,pessoal,None,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-03-18,40,NaN,Proferido despacho de mero expediente,06/03/24,"advogado, pessoal"
31,06/03/24,Intimação expedido(a) Para ROBSON DE OLIVEIRA ...,robson de oliveira silva,pessoal,None,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,2024-03-18,40,NaN,Proferido despacho de mero expediente,06/03/24,"advogado, pessoal"
26,06/03/24,Intimação expedido(a) (P/ Advgs. de FABIANA DO...,fabiana dos santos silva gomes marmoraria,advogado,domicilio_cnj,Intimação lido(a) (Para FABIANA DOS SANTOS SIL...,2024-03-06,35,NaN,Intimação para Videoconferência à disposição,06/03/24,advogado
21,06/03/24,Intimação expedido(a) (P/ Advgs. de FABIANA DO...,fabiana dos santos silva gomes marmoraria,advogado,domicilio_cnj,Intimação lido(a) (Para FABIANA DOS SANTOS SIL...,2024-03-06,35,NaN,Intimação para Videoconferência à disposição,06/03/24,advogado
26,06/03/24,Intimação expedido(a) (P/ Advgs. de FABIANA DO...,fabiana dos santos silva gomes marmoraria,advogado,domicilio_cnj,Intimação lido(a) (Para FABIANA DOS SANTOS SIL...,2024-03-06,34,NaN,Proferido despacho de mero expediente,06/03/24,advogado
21,06/03/24,Intimação expedido(a) (P/ Advgs. de FABIANA DO...,fabiana dos santos silva gomes marmoraria,advogado,domicilio_cnj,Intimação lido(a) (Para FABIANA DOS SANTOS SIL...,2024-03-06,34,NaN,Proferido despacho de mero expediente,06/03/24,advogado

16

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
71,06/02/26,Intimação expedido(a) (P/ Advgs. de BANCO BRAD...,banco bradesco s a,advogado,domicilio_cnj,Intimação lido(a) (Para BANCO BRADESCO S A) em...,2026-02-19,81,15 dias,Proferido despacho de mero expediente,06/02/26,"advogado, pessoal"
70,06/02/26,Intimação expedido(a) (Para BANCO BRADESCO S A...,banco bradesco s a,pessoal,None,Intimação lido(a) (Para BANCO BRADESCO S A) em...,2026-02-19,81,15 dias,Proferido despacho de mero expediente,06/02/26,"advogado, pessoal"
13,14/10/25,Intimação expedido(a) (Para BANCO BRADESCO S A...,banco bradesco s a,pessoal,None,Intimação lido(a) (Para BANCO BRADESCO S A) em...,2025-10-24,20,10 dias,Intimação à disposição,14/10/25,"advogado, pessoal"
12,14/10/25,Intimação expedido(a) (P/ Advgs. de WENDEL COR...,wendel cordeiro marques,advogado,domicilio_cnj,Intimação lido(a) (Para WENDEL CORDEIRO MARQUE...,2025-10-14,6,10 dias,Audiência de Conciliação Designada,14/10/25,advogado

4

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
101,15/12/25,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2026-01-21,103,NaN,Documento analisado,15/12/25,
88,20/10/25,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2025-10-21,91,NaN,Intimação para Videoconferência à disposição,20/10/25,
67,09/07/25,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2025-07-16,68,NaN,Documento analisado,09/07/25,
16,04/12/23,Intimação expedido(a) Para WILSON OLIVEIRA DA ...,wilson oliveira da silva,pessoal,None,Intimação lido(a) (Para WILSON OLIVEIRA DA SIL...,2023-12-19,18,NaN,Intimação para Videoconferência à disposição,04/12/23,pessoal

4

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
13,24/10/25,Intimação expedido(a) (Para BANCO BRADESCO FIN...,banco bradesco financiamentos s a,pessoal,None,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,2025-11-03,22,NaN,Intimação à disposição,24/10/25,"advogado, pessoal"
12,24/10/25,Intimação expedido(a) (P/ Advgs. de MARIA JOSE...,maria jose bezerra,advogado,domicilio_cnj,Intimação lido(a) (Para MARIA JOSE BEZERRA) em...,2025-10-24,6,10 dias,Audiência de Conciliação Designada,24/10/25,advogado

2

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

Empty DataFrame
Columns: [data_expedicao, ato_expedido, destinatario, meio, canal, ato_lido, data_leitura, evento_lido, prazo, ato_origem, data_origem, canais_historicos]
Index: []

0

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
33,01/04/25,Intimação expedido(a) (P/ Advgs. de EDMILSON L...,edmilson lopes cabral,advogado,domicilio_cnj,Intimação lido(a) (Para EDMILSON LOPES CABRAL)...,2025-04-01,34,5 dias,Intimação à disposição,01/04/25,advogado
29,26/02/25,Intimação expedido(a) (P/ Advgs. de PREVEBENE ...,prevebene administradora de beneficios e promo...,advogado,domicilio_cnj,Intimação lido(a) (Para PREVEBENE ADMINISTRADO...,2025-03-10,30,15 dias,Proferido despacho de mero expediente,26/02/25,"advogado, pessoal"
20,09/12/24,Intimação expedido(a) (P/ Advgs. de PREVEBENE ...,prevebene administradora de beneficios e promo...,advogado,domicilio_cnj,Intimação lido(a) (Para PREVEBENE ADMINISTRADO...,2024-12-19,22,NaN,Intimação à disposição,09/12/24,"advogado, pessoal"
19,09/12/24,Intimação expedido(a) (P/ Advgs. de EDMILSON L...,edmilson lopes cabral,advogado,domicilio_cnj,Intimação lido(a) (Para EDMILSON LOPES CABRAL)...,2024-12-09,21,NaN,Intimação à disposição,09/12/24,advogado

4

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
26,13/04/25,Intimação expedido(a) (Para TRANSPORTE COLETIV...,transporte coletivo brasil ltda,pessoal,None,Intimação lido(a) (Para TRANSPORTE COLETIVO BR...,2025-04-23,27,15 dias,Proferido despacho de mero expediente,13/04/25,pessoal
15,14/01/25,Intimação expedido(a) (P/ Advgs. de ADAILTON P...,adailton pereira da silva,advogado,domicilio_cnj,Intimação lido(a) (Para ADAILTON PEREIRA DA SI...,2025-01-24,16,10 dias,Intimação à disposição,14/01/25,advogado

2

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
77,15/12/25,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2026-01-21,79,NaN,Autos entregues em carga ao destino,15/12/25,
64,07/10/25,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2025-10-09,65,NaN,Documento analisado,07/10/25,
35,12/08/25,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2025-08-14,40,NaN,Autos entregues em carga ao destino,12/08/25,

3

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
24,02/03/26,Intimação expedido(a) P/ Núcleo de Atuação MP ...,núcleo de atuação mp paulo afonso,None,None,Intimação lido(a) (Para Núcleo de Atuação MP P...,2026-03-06,29,NaN,Intimação para Videoconferência à disposição,02/03/26,
11,12/01/26,Intimação expedido(a) Para CICERO ALENCAR DA S...,cicero alencar da silva,pessoal,None,Intimação lido(a) (Para CICERO ALENCAR DA SILV...,2026-01-21,14,NaN,Intimação para Videoconferência à disposição,12/01/26,pessoal

2

,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
evento_expedido,,,,,,,,,,,,
17,17/12/18,Intimação expedido(a) (P/ Advgs. de OI MOVEL S...,oi movel s a sociedade empresaria em recuperac...,advogado,domicilio_cnj,Intimação lido(a) (Para OI MOVEL S A SOCIEDADE...,2019-01-21,20,NaN,Intimação à disposição,17/12/18,"advogado, pessoal"
16,17/12/18,Intimação expedido(a) (P/ Advgs. de SEVERINO A...,severino alves de oliveira lima,advogado,domicilio_cnj,Intimação lido(a) (Para SEVERINO ALVES DE OLIV...,2019-01-21,19,NaN,Intimação à disposição,17/12/18,advogado

2

In [ ]:
df_final_relacoes = pd.concat(df_relacoes_total, ignore_index=True)
display(df_final_relacoes.head())
df_final_relacoes.columns

,evento_expedido,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,canais_historicos
0,60,28/04/26,Intimação expedido(a) Para TV VINHOS LTDA *Ref...,tv vinhos ltda,pessoal,None,Intimação lido(a) (Para TV VINHOS LTDA) em 11/...,2026-05-11,62,NaN,Ato ordinatório praticado,28/04/26,pessoal
1,58,28/04/26,Intimação expedido(a) (Para PAYOUT PAGAMENTOS ...,payout pagamentos inteligentes ltda,pessoal,None,Intimação lido(a) (Para PAYOUT PAGAMENTOS INTE...,2026-05-08,61,15 dias,Ato ordinatório praticado,28/04/26,"advogado, pessoal"
2,14,21/01/26,Intimação expedido(a) (Para PAYOUT PAGAMENTOS ...,payout pagamentos inteligentes ltda,pessoal,None,Intimação lido(a) (Para PAYOUT PAGAMENTOS INTE...,2026-02-02,25,NaN,Intimação à disposição,21/01/26,"advogado, pessoal"
3,219,09/03/26,Intimação expedido(a) (P/ Advgs. de AMIL ASSIS...,amil assistencia medica internacional s a,advogado,domicilio_cnj,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,2026-03-19,223,5 dias,Concedida a Medida Liminar,09/03/26,"advogado, pessoal"
4,218,09/03/26,Intimação expedido(a) (Para AMIL ASSISTENCIA M...,amil assistencia medica internacional s a,pessoal,None,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,2026-03-19,223,5 dias,Concedida a Medida Liminar,09/03/26,"advogado, pessoal"

Index(['evento_expedido', 'data_expedicao', 'ato_expedido', 'destinatario',
       'meio', 'canal', 'ato_lido', 'data_leitura', 'evento_lido', 'prazo',
       'ato_origem', 'data_origem', 'canais_historicos'],
      dtype='object')

In [ ]:
for numero, df in processos.items():
    # df.drop('ato_normalizado')
    
    display(df[df['data_leitura_str'].notnull()])
    # display(df.drop(columns=[['ato_normalizado', 'data_obj']], axis=1))
    print(
        f"Processo: {numero} | "
        f"Movimentações: {len(df)}"
    )

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
3,62,Intimação lido(a) (Para TV VINHOS LTDA) em 11/...,intimação lido(a) (para tv vinhos ltda) em 11/...,17/05/26,2026-05-17,2026-05-11,28/04/26,ECT,,intimacao,None,lida,tv vinhos ltda
4,61,Intimação lido(a) (Para PAYOUT PAGAMENTOS INTE...,intimação lido(a) (para payout pagamentos inte...,09/05/26,2026-05-09,2026-05-08,28/04/26,SISTEMA CNJ,,intimacao,None,lida,payout pagamentos inteligentes ltda
10,30,Citação lido(a) P/ PAYOUT PAGAMENTOS INTELIGEN...,citação lido(a) p/ payout pagamentos inteligen...,16/02/26,2026-02-16,2026-02-04,None,ECT,,citacao,None,lida,payout pagamentos inteligentes ltda em 04/02/26
11,28,Intimação lido(a) (Para TV VINHOS LTDA) em 05/...,intimação lido(a) (para tv vinhos ltda) em 05/...,14/02/26,2026-02-14,2026-02-05,21/01/26,ECT,,intimacao,None,lida,tv vinhos ltda
12,26,Citação lido(a) P/ TV VINHOS LTDA em 05/02/26,citação lido(a) p/ tv vinhos ltda em 05/02/26,14/02/26,2026-02-14,2026-02-05,None,ECT,,citacao,None,lida,tv vinhos ltda em 05/02/26
13,25,Intimação lido(a) (Para PAYOUT PAGAMENTOS INTE...,intimação lido(a) (para payout pagamentos inte...,03/02/26,2026-02-03,2026-02-02,21/01/26,SISTEMA CNJ,,intimacao,None,lida,payout pagamentos inteligentes ltda
21,6,Intimação lido(a) (Para DANILO AUGUSTO E ARAUJ...,intimação lido(a) (para danilo augusto e arauj...,15/01/26,2026-01-15,2026-01-15,15/01/26,SISTEMA CNJ,,intimacao,None,lida,danilo augusto e araujo franca

Processo: processo_0000084-87.2026.8.05.0191 | Movimentações: 22

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
8,223,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,intimação lido(a) (para amil assistencia medic...,20/03/26,2026-03-20,2026-03-19,09/03/26,SISTEMA CNJ,,intimacao,None,lida,amil assistencia medica internacional s a
16,182,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,intimação lido(a) (para amil assistencia medic...,21/10/25,2025-10-21,2025-10-20,10/10/25,SISTEMA CNJ,,intimacao,None,lida,amil assistencia medica internacional s a
42,41,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,intimação lido(a) (para amil assistencia medic...,17/05/25,2025-05-17,2025-05-16,06/05/25,SISTEMA CNJ,,intimacao,None,lida,amil assistencia medica internacional s a
43,40,Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...,intimação lido(a) (para raquel lemos de olivei...,17/05/25,2025-05-17,2025-05-16,06/05/25,SISTEMA CNJ,,intimacao,None,lida,raquel lemos de oliveira
47,27,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,intimação lido(a) (para amil assistencia medic...,07/03/25,2025-03-07,2025-03-06,17/02/25,SISTEMA CNJ,,intimacao,None,lida,amil assistencia medica internacional s a
48,26,Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...,intimação lido(a) (para raquel lemos de olivei...,07/03/25,2025-03-07,2025-03-06,17/02/25,SISTEMA CNJ,,intimacao,None,lida,raquel lemos de oliveira
49,25,Intimação lido(a) (Para AMIL ASSISTENCIA MEDIC...,intimação lido(a) (para amil assistencia medic...,18/02/25,2025-02-18,2025-02-17,06/02/25,SISTEMA CNJ,,intimacao,None,lida,amil assistencia medica internacional s a
50,24,Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...,intimação lido(a) (para raquel lemos de olivei...,18/02/25,2025-02-18,2025-02-17,06/02/25,SISTEMA CNJ,,intimacao,None,lida,raquel lemos de oliveira
53,13,Citação lido(a) P/ Representante: AMIL ASSISTE...,citação lido(a) p/ representante: amil assiste...,07/02/25,2025-02-07,2025-02-07,None,Tulio Godoy Gomes Salles Rosa,,citacao,None,lida,representante: amil assistencia medica interna...
57,6,Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEI...,intimação lido(a) (para raquel lemos de olivei...,06/02/25,2025-02-06,2025-02-06,06/02/25,SISTEMA CNJ,,intimacao,None,lida,raquel lemos de oliveira

Processo: processo_0000443-71.2025.8.05.0191 | Movimentações: 58

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
2,118,Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...,intimação lido(a) (para edileide da silva lima...,31/10/24,2024-10-31,2024-10-31,30/10/24,LEANA BEZERRA GOMES EVANGELISTA,,intimacao,None,lida,edileide da silva lima
4,114,Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...,intimação lido(a) (para edileide da silva lima...,24/10/24,2024-10-24,2024-10-24,16/10/24,LEANA BEZERRA GOMES EVANGELISTA,,intimacao,None,lida,edileide da silva lima
6,93,Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...,intimação lido(a) (para edileide da silva lima...,11/06/24,2024-06-11,2024-06-11,05/06/24,LEANA BEZERRA GOMES EVANGELISTA,,intimacao,None,lida,edileide da silva lima
8,30,Intimação lido(a) (Para LARBELO MOVEIS) em 10/...,intimação lido(a) (para larbelo moveis) em 10/...,16/05/23,2023-05-16,2023-05-10,17/04/23,ECT,,intimacao,None,lida,larbelo moveis
10,19,Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...,intimação lido(a) (para edileide da silva lima...,22/03/23,2023-03-22,2023-03-22,22/03/23,LEANA BEZERRA GOMES EVANGELISTA,,intimacao,None,lida,edileide da silva lima
13,11,Citação lido(a) P/ LARBELO MOVEIS em 08/03/23,citação lido(a) p/ larbelo moveis em 08/03/23,15/03/23,2023-03-15,2023-03-08,None,ECT,,citacao,None,lida,larbelo moveis em 08/03/23
15,5,Intimação lido(a) (Para EDILEIDE DA SILVA LIMA...,intimação lido(a) (para edileide da silva lima...,16/02/23,2023-02-16,2023-02-16,16/02/23,SISTEMA CNJ,,intimacao,None,lida,edileide da silva lima

Processo: processo_0000485-91.2023.8.05.0191 | Movimentações: 16

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
2,35,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,10/04/26,2026-04-10,2026-04-09,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
3,32,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,07/04/26,2026-04-07,2026-04-06,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
7,14,Devolução sem Leitura De Intimação expedida em...,devolução sem leitura de intimação expedida em...,06/03/26,2026-03-06,2026-02-25,24/02/26,ECT,,intimacao,None,expedida,claudemir nascimento da silva
8,13,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,07/03/26,2026-03-07,2026-03-06,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso

Processo: processo_0000508-32.2026.8.05.0191 | Movimentações: 11

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
2,152,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,intimação lido(a) (para maria lucia teixeira d...,30/04/24,2024-04-30,2024-04-29,17/04/24,SISTEMA CNJ,,intimacao,None,lida,maria lucia teixeira de oliveira
3,151,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,intimação lido(a) (para banco bradesco financi...,25/04/24,2024-04-25,2024-04-25,17/04/24,FERNANDO AUGUSTO DE FARIA CORBO,,intimacao,None,lida,banco bradesco financiamentos s a
6,140,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,intimação lido(a) (para maria lucia teixeira d...,09/03/24,2024-03-09,2024-03-08,27/02/24,SISTEMA CNJ,,intimacao,None,lida,maria lucia teixeira de oliveira
7,139,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,intimação lido(a) (para banco bradesco financi...,06/03/24,2024-03-06,2024-03-06,27/02/24,FERNANDO AUGUSTO DE FARIA CORBO,,intimacao,None,lida,banco bradesco financiamentos s a
10,123,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,intimação lido(a) (para banco bradesco financi...,20/09/23,2023-09-20,2023-09-20,12/09/23,FERNANDO AUGUSTO DE FARIA CORBO,,intimacao,None,lida,banco bradesco financiamentos s a
12,107,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,intimação lido(a) (para maria lucia teixeira d...,25/07/23,2023-07-25,2023-07-24,14/07/23,SISTEMA CNJ,,intimacao,None,lida,maria lucia teixeira de oliveira
13,106,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,intimação lido(a) (para banco bradesco financi...,21/07/23,2023-07-21,2023-07-21,14/07/23,FERNANDO AUGUSTO DE FARIA CORBO,,intimacao,None,lida,banco bradesco financiamentos s a
16,95,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,intimação lido(a) (para banco bradesco financi...,23/06/23,2023-06-23,2023-06-26,16/06/23,FERNANDO AUGUSTO DE FARIA CORBO,,intimacao,None,lida,banco bradesco financiamentos s a
18,83,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,intimação lido(a) (para maria lucia teixeira d...,13/09/22,2022-09-13,2022-09-12,02/09/22,SISTEMA CNJ,,intimacao,None,expedida,maria lucia teixeira de oliveira
19,79,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,intimação lido(a) (para banco bradesco financi...,05/09/22,2022-09-05,2022-09-05,02/09/22,FERNANDO AUGUSTO DE FARIA CORBO,,intimacao,None,expedida,banco bradesco financiamentos s a
23,63,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,intimação lido(a) (para maria lucia teixeira d...,01/09/22,2022-09-01,2022-09-01,31/08/22,KALYF SANTOS ALMEIDA,,intimacao,None,lida,maria lucia teixeira de oliveira
25,51,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,intimação lido(a) (para banco bradesco financi...,18/07/22,2022-07-18,2022-07-18,15/07/22,FERNANDO AUGUSTO DE FARIA CORBO,,intimacao,None,expedida,banco bradesco financiamentos s a
28,44,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,intimação lido(a) (para maria lucia teixeira d...,11/07/22,2022-07-11,2022-07-11,11/07/22,KALYF SANTOS ALMEIDA,,intimacao,None,lida,maria lucia teixeira de oliveira
30,35,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,intimação lido(a) (para maria lucia teixeira d...,21/06/22,2022-06-21,2022-06-20,08/06/22,SISTEMA CNJ,,intimacao,None,lida,maria lucia teixeira de oliveira
31,34,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,intimação lido(a) (para banco bradesco financi...,10/06/22,2022-06-10,2022-06-10,08/06/22,FERNANDO AUGUSTO DE FARIA CORBO,,intimacao,None,lida,banco bradesco financiamentos s a
38,14,Citação lido(a) P/ BANCO BRADESCO FINANCIAMENT...,citação lido(a) p/ banco bradesco financiament...,26/03/22,2022-03-26,2022-03-28,None,SISTEMA CNJ,,citacao,None,lida,banco bradesco financiamentos s a em 28/03/22 ...
39,13,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,intimação lido(a) (para maria lucia teixeira d...,24/03/22,2022-03-24,2022-03-24,17/03/22,KALYF SANTOS ALMEIDA,,intimacao,None,lida,maria lucia teixeira de oliveira
42,6,Intimação lido(a) (Para MARIA LUCIA TEIXEIRA D...,intimação lido(a) (para maria lucia teixeira d...,15/03/22,2022-03-15,2022-03-15,15/03/22,SISTEMA CNJ,,intimacao,None,lida,maria lucia teixeira de oliveira

Processo: processo_0000554-60.2022.8.05.0191 | Movimentações: 43

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
5,9,Citação lido(a) P/ AZUL LINHAS AEREAS BRASILEI...,citação lido(a) p/ azul linhas aereas brasilei...,13/03/26,2026-03-13,2026-03-13,None,SISTEMA CNJ,,citacao,None,lida,azul linhas aereas brasileiras s a em 13/03/26...
7,5,Intimação lido(a) (Para PAULO CESAR AGUIAR NET...,intimação lido(a) (para paulo cesar aguiar net...,12/03/26,2026-03-12,2026-03-12,12/03/26,SISTEMA CNJ,,intimacao,None,lida,paulo cesar aguiar neto

Processo: processo_0000686-78.2026.8.05.0191 | Movimentações: 8

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,112,Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...,intimação lido(a) (para bruno henrique gomes b...,08/05/26,2026-05-08,2026-05-07,27/04/26,SISTEMA CNJ,,intimacao,None,lida,bruno henrique gomes bezerra
3,103,Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...,intimação lido(a) (para bruno henrique gomes b...,20/03/26,2026-03-20,2026-03-19,09/03/26,SISTEMA CNJ,,intimacao,None,expedida,bruno henrique gomes bezerra
9,72,Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...,intimação lido(a) (para bruno henrique gomes b...,18/11/25,2025-11-18,2025-11-17,07/11/25,SISTEMA CNJ,,intimacao,None,lida,bruno henrique gomes bezerra
14,38,Intimação lido(a) (Para BRUNO HENRIQUE GOMES B...,intimação lido(a) (para bruno henrique gomes b...,20/05/25,2025-05-20,2025-05-09,05/05/25,ECT,,intimacao,None,expedida,bruno henrique gomes bezerra
15,36,Intimação lido(a) (Para BANCO SANTANDER BRASIL...,intimação lido(a) (para banco santander brasil...,06/05/25,2025-05-06,2025-05-06,05/05/25,PAULO ROBERTO JOAQUIM DOS REIS,,intimacao,None,expedida,banco santander brasil s a
19,20,Citação lido(a) P/ BANCO SANTANDER BRASIL S A ...,citação lido(a) p/ banco santander brasil s a ...,23/04/25,2025-04-23,2025-04-01,None,ECT,,citacao,None,lida,banco santander brasil s a em 01/04/25

Processo: processo_0000971-08.2025.8.05.0191 | Movimentações: 23

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,22,Citação lido(a) P/ BANCO MASTER S A em 29/04/26,citação lido(a) p/ banco master s a em 29/04/26,09/05/26,2026-05-09,2026-04-29,None,ECT,,citacao,None,lida,banco master s a em 29/04/26
7,6,Intimação lido(a) (Para JOSE HILTON MATOS DOS ...,intimação lido(a) (para jose hilton matos dos ...,07/04/26,2026-04-07,2026-04-07,07/04/26,SISTEMA CNJ,,intimacao,None,lida,jose hilton matos dos santos

Processo: processo_0000977-78.2026.8.05.0191 | Movimentações: 8

Empty DataFrame
Columns: [evento, ato, ato_normalizado, data_texto, data_obj, data_leitura_str, data_referencia_str, autor, observacao, categoria, meio_comunicacao, situacao_comunicacao, destinatario]
Index: []

Processo: processo_0001116-64.2025.8.05.0191 | Movimentações: 20

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,56,Devolução sem Leitura De Intimação expedida em...,devolução sem leitura de intimação expedida em...,17/04/26,2026-04-17,2026-03-13,13/03/26,ECT,,intimacao,None,expedida,associacao dos aposentados e pensionistas naci...
1,54,Devolução sem Leitura De Intimação expedida em...,devolução sem leitura de intimação expedida em...,19/01/26,2026-01-19,2025-12-15,15/12/25,ECT,,intimacao,None,expedida,associacao dos aposentados e pensionistas naci...
6,26,Devolução sem Leitura De Intimação expedida em...,devolução sem leitura de intimação expedida em...,17/07/25,2025-07-17,2025-07-07,07/07/25,ECT,,intimacao,None,expedida,associacao dos aposentados e pensionistas naci...
8,18,Intimação lido(a) (Para LUIZ ANTONIO DE ANDRAD...,intimação lido(a) (para luiz antonio de andrad...,14/05/25,2025-05-14,2025-05-14,13/05/25,RAYANE MAYARA DE LIMA,,intimacao,None,lida,luiz antonio de andrade
11,9,Citação lido(a) P/ ASSOCIACAO DOS APOSENTADOS ...,citação lido(a) p/ associacao dos aposentados ...,23/04/25,2025-04-23,2025-04-08,None,ECT,,citacao,None,lida,associacao dos aposentados e pensionistas naci...
13,5,Intimação lido(a) (Para LUIZ ANTONIO DE ANDRAD...,intimação lido(a) (para luiz antonio de andrad...,02/04/25,2025-04-02,2025-04-02,02/04/25,SISTEMA CNJ,,intimacao,None,lida,luiz antonio de andrade

Processo: processo_0001131-33.2025.8.05.0191 | Movimentações: 14

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,246,Intimação lido(a) (Para NU PAGAMENTOS S A INST...,intimação lido(a) (para nu pagamentos s a inst...,05/05/26,2026-05-05,2026-05-04,24/04/26,SISTEMA CNJ,,intimacao,None,lida,nu pagamentos s a instituicao de pagamento
4,228,Intimação lido(a) (Para NU PAGAMENTOS S A INST...,intimação lido(a) (para nu pagamentos s a inst...,14/04/26,2026-04-14,2026-04-13,01/04/26,SISTEMA CNJ,,intimacao,None,lida,nu pagamentos s a instituicao de pagamento
47,27,Intimação lido(a) (Para ERICK ERNANDES SANDES)...,intimação lido(a) (para erick ernandes sandes)...,09/05/25,2025-05-09,2025-05-08,28/04/25,SISTEMA CNJ,,intimacao,None,lida,erick ernandes sandes
49,17,Intimação lido(a) (Para NU PAGAMENTOS S A INST...,intimação lido(a) (para nu pagamentos s a inst...,26/04/25,2025-04-26,2025-04-25,15/04/25,SISTEMA CNJ,,intimacao,None,lida,nu pagamentos s a instituicao de pagamento
50,16,Intimação lido(a) (Para ERICK ERNANDES SANDES)...,intimação lido(a) (para erick ernandes sandes)...,26/04/25,2025-04-26,2025-04-25,15/04/25,SISTEMA CNJ,,intimacao,None,lida,erick ernandes sandes
53,8,Citação lido(a) P/ NU PAGAMENTOS S A INSTITUIC...,citação lido(a) p/ nu pagamentos s a instituic...,14/04/25,2025-04-14,2025-04-14,None,SISTEMA CNJ,,citacao,None,lida,nu pagamentos s a instituicao de pagamento em ...
55,6,Intimação lido(a) (Para ERICK ERNANDES SANDES)...,intimação lido(a) (para erick ernandes sandes)...,12/04/25,2025-04-12,2025-04-12,12/04/25,SISTEMA CNJ,,intimacao,None,lida,erick ernandes sandes

Processo: processo_0001306-27.2025.8.05.0191 | Movimentações: 56

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,8,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,23/05/26,2026-05-23,2026-05-22,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso

Processo: processo_0001334-58.2026.8.05.0191 | Movimentações: 2

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
7,314,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,19/08/25,2025-08-19,2025-08-18,06/08/25,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
17,261,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,24/04/25,2025-04-24,2025-04-22,11/04/25,SISTEMA CNJ,,intimacao,None,expedida,priorizar corretora de seguros ltda
18,260,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,24/04/25,2025-04-24,2025-04-22,11/04/25,SISTEMA CNJ,,intimacao,None,expedida,clube de saude administradora de beneficios ltda.
19,259,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,23/04/25,2025-04-23,2025-04-22,08/04/25,SISTEMA CNJ,,intimacao,None,expedida,selma pereira dias
20,255,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,14/04/25,2025-04-14,2025-04-14,11/04/25,IGOR MACEDO FACO,,intimacao,None,expedida,hapvida assistencia medica s a
27,228,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,18/03/25,2025-03-18,2025-03-17,06/03/25,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros ltda
28,227,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,18/03/25,2025-03-18,2025-03-17,06/03/25,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda.
29,226,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,12/03/25,2025-03-12,2025-03-12,06/03/25,SISTEMA CNJ,,intimacao,None,lida,hapvida assistencia medica s a
30,225,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,07/03/25,2025-03-07,2025-03-06,24/02/25,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
31,224,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,07/03/25,2025-03-07,2025-03-06,24/02/25,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros ltda
32,223,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,07/03/25,2025-03-07,2025-03-06,24/02/25,SISTEMA CNJ,,intimacao,None,lida,hapvida assistencia medica s a
33,222,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,07/03/25,2025-03-07,2025-03-06,24/02/25,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda.
41,200,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,31/01/25,2025-01-31,2025-01-30,20/01/25,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
42,199,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,31/01/25,2025-01-31,2025-01-30,20/01/25,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros ltda
43,198,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,31/01/25,2025-01-31,2025-01-30,20/01/25,SISTEMA CNJ,,intimacao,None,lida,hapvida assistencia medica s a
44,197,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,31/01/25,2025-01-31,2025-01-30,20/01/25,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda.
49,185,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,03/12/24,2024-12-03,2024-12-02,20/11/24,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
50,184,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,03/12/24,2024-12-03,2024-12-02,20/11/24,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros ltda
51,183,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,03/12/24,2024-12-03,2024-12-02,20/11/24,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda.
56,167,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,30/10/24,2024-10-30,2024-10-29,16/10/24,SISTEMA CNJ,,intimacao,None,lida,hapvida assistencia medica s a
57,166,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,30/10/24,2024-10-30,2024-10-29,16/10/24,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda.
58,165,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,25/10/24,2024-10-25,2024-10-24,14/10/24,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
59,164,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,25/10/24,2024-10-25,2024-10-24,14/10/24,SISTEMA CNJ,,intimacao,None,lida,hapvida assistencia medica s a
60,163,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,25/10/24,2024-10-25,2024-10-24,14/10/24,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros ltda
61,162,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,25/10/24,2024-10-25,2024-10-24,14/10/24,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda.
68,132,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,20/09/24,2024-09-20,2024-09-19,09/09/24,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
69,131,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,20/09/24,2024-09-20,2024-09-19,09/09/24,SISTEMA CNJ,,intimacao,None,lida,hapvida assistencia medica s a
70,130,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,20/09/24,2024-09-20,2024-09-19,09/09/24,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros ltda
71,129,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,20/09/24,2024-09-20,2024-09-19,09/09/24,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda.
76,120,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,31/08/24,2024-08-31,2024-08-30,20/08/24,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
77,119,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,31/08/24,2024-08-31,2024-08-30,20/08/24,SISTEMA CNJ,,intimacao,None,lida,hapvida assistencia medica s.a.
78,118,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,31/08/24,2024-08-31,2024-08-30,20/08/24,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros ltda
79,117,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,31/08/24,2024-08-31,2024-08-30,20/08/24,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda.
84,98,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,20/07/24,2024-07-20,2024-07-19,09/07/24,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
86,92,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,29/06/24,2024-06-29,2024-06-28,18/06/24,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros ltda
88,83,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,04/06/24,2024-06-04,2024-06-03,22/05/24,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros
89,82,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,04/06/24,2024-06-04,2024-06-03,22/05/24,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
92,72,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,23/04/24,2024-04-23,2024-04-22,11/04/24,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
94,68,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,26/03/24,2024-03-26,2024-03-25,14/03/24,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros
95,67,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,26/03/24,2024-03-26,2024-03-25,14/03/24,SISTEMA CNJ,,intimacao,None,lida,hapvida assistencia medica s.a.
96,66,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,26/03/24,2024-03-26,2024-03-25,14/03/24,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda.
97,65,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,26/03/24,2024-03-26,2024-03-25,14/03/24,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
103,51,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,31/10/23,2023-10-31,2023-10-30,19/10/23,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
105,37,Intimação lido(a) (Para PRIORIZAR CORRETORA DE...,intimação lido(a) (para priorizar corretora de...,29/08/23,2023-08-29,2023-08-28,17/08/23,SISTEMA CNJ,,intimacao,None,lida,priorizar corretora de seguros
106,36,Intimação lido(a) (Para HAPVIDA ASSISTENCIA ME...,intimação lido(a) (para hapvida assistencia me...,29/08/23,2023-08-29,2023-08-28,17/08/23,SISTEMA CNJ,,intimacao,None,lida,hapvida assistencia medica ltda
107,35,Intimação lido(a) (Para CLUBE DE SAUDE ADMINIS...,intimação lido(a) (para clube de saude adminis...,29/08/23,2023-08-29,2023-08-28,17/08/23,SISTEMA CNJ,,intimacao,None,lida,clube de saude administradora de beneficios ltda
108,34,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,29/08/23,2023-08-29,2023-08-28,17/08/23,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias
114,16,Citação lido(a) P/ PRIORIZAR CORRETORA DE SEGU...,citação lido(a) p/ priorizar corretora de segu...,31/05/23,2023-05-31,2023-05-24,None,ECT,,citacao,None,lida,priorizar corretora de seguros em 24/05/23
115,15,Citação lido(a) P/ HAPVIDA ASSISTENCIA MEDICA ...,citação lido(a) p/ hapvida assistencia medica ...,19/05/23,2023-05-19,2023-05-19,None,SISTEMA CNJ,,citacao,None,lida,hapvida assistencia medica ltda em 19/05/23 ob...
116,13,Citação lido(a) P/ Representante: CLUBE DE SAU...,citação lido(a) p/ representante: clube de sau...,11/05/23,2023-05-11,2023-05-11,None,LUCIANA MIRA PALMA,,citacao,None,lida,representante: clube de saude administradora d...
120,6,Intimação lido(a) (Para SELMA PEREIRA DIAS) em...,intimação lido(a) (para selma pereira dias) em...,08/05/23,2023-05-08,2023-05-08,08/05/23,SISTEMA CNJ,,intimacao,None,lida,selma pereira dias

Processo: processo_0001340-70.2023.8.05.0191 | Movimentações: 121

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,16,Intimação lido(a) (Para GRUPO CASAS BAHIA S A)...,intimação lido(a) (para grupo casas bahia s a)...,02/06/26,2026-06-02,2026-06-01,20/05/26,SISTEMA CNJ,,intimacao,None,lida,grupo casas bahia s a
1,12,Citação lido(a) P/ GRUPO CASAS BAHIA S A em 20...,citação lido(a) p/ grupo casas bahia s a em 20...,20/05/26,2026-05-20,2026-05-20,None,SISTEMA CNJ,,citacao,None,lida,grupo casas bahia s a em 20/05/26 obs: leitura...
4,6,Intimação lido(a) (Para ANDREA CARLA CARDOSO D...,intimação lido(a) (para andrea carla cardoso d...,20/05/26,2026-05-20,2026-05-20,20/05/26,SISTEMA CNJ,,intimacao,None,lida,andrea carla cardoso de brito silva

Processo: processo_0001463-63.2026.8.05.0191 | Movimentações: 5

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
6,5,Intimação lido(a) (Para MARCELO DANIEL MELO AL...,intimação lido(a) (para marcelo daniel melo al...,25/05/26,2026-05-25,2026-05-25,25/05/26,SISTEMA CNJ,,intimacao,None,lida,marcelo daniel melo alencar

Processo: processo_0001518-14.2026.8.05.0191 | Movimentações: 7

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,6,Intimação lido(a) (Para ROGERIO FREITAS CAVALC...,intimação lido(a) (para rogerio freitas cavalc...,02/06/26,2026-06-02,2026-06-02,02/06/26,SISTEMA CNJ,,intimacao,None,lida,rogerio freitas cavalcanti

Processo: processo_0001618-66.2026.8.05.0191 | Movimentações: 1

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
4,21,Citação lido(a) P/ ASSOCIACAO DE APOSENTADOS M...,citação lido(a) p/ associacao de aposentados m...,14/06/25,2025-06-14,2025-05-23,None,ECT,,citacao,None,lida,associacao de aposentados mutualista para bene...
7,12,Intimação lido(a) (Para FLORISVALDO CARVALHO L...,intimação lido(a) (para florisvaldo carvalho l...,16/05/25,2025-05-16,2025-05-16,15/05/25,LEANA BEZERRA GOMES EVANGELISTA,,intimacao,None,expedida,florisvaldo carvalho lima
11,6,Intimação lido(a) (Para FLORISVALDO CARVALHO L...,intimação lido(a) (para florisvaldo carvalho l...,13/05/25,2025-05-13,2025-05-13,13/05/25,SISTEMA CNJ,,intimacao,None,lida,florisvaldo carvalho lima

Processo: processo_0001665-74.2025.8.05.0191 | Movimentações: 12

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
2,6,Intimação lido(a) (Para MARIA DO SOCORRO LIMA ...,intimação lido(a) (para maria do socorro lima ...,08/06/26,2026-06-08,2026-06-08,08/06/26,SISTEMA CNJ,,intimacao,None,lida,maria do socorro lima santos

Processo: processo_0001666-25.2026.8.05.0191 | Movimentações: 3

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
50,77,Intimação lido(a) (Para COMPANHIA DE SEGUROS P...,intimação lido(a) (para companhia de seguros p...,18/07/25,2025-07-18,2025-07-17,07/07/25,SISTEMA CNJ,,intimacao,None,lida,companhia de seguros previdencia do sul
51,76,Intimação lido(a) (Para COMPANHIA DE SEGUROS P...,intimação lido(a) (para companhia de seguros p...,18/07/25,2025-07-18,2025-07-17,07/07/25,SISTEMA CNJ,,intimacao,None,lida,companhia de seguros previdencia do sul
52,73,Intimação lido(a) (Para COMPANHIA DE SEGUROS P...,intimação lido(a) (para companhia de seguros p...,08/07/25,2025-07-08,2025-07-07,13/05/25,SISTEMA CNJ,,intimacao,None,lida,companhia de seguros previdencia do sul
71,17,Citação lido(a) P/ MONGERAL AEGON SEGUROS E PR...,citação lido(a) p/ mongeral aegon seguros e pr...,16/05/25,2025-05-16,2025-05-16,None,SISTEMA CNJ,,citacao,None,lida,mongeral aegon seguros e previdencia s/a em 16...
72,16,Citação lido(a) P/ Representante: COMPANHIA DE...,citação lido(a) p/ representante: companhia de...,15/05/25,2025-05-15,2025-05-15,None,BRUNO HENRIQUE DE OLIVEIRA VANDERLEI,,citacao,None,lida,representante: companhia de seguros previdenci...
73,15,Citação lido(a) P/ ASPECIR UNIAO SEGURADORA em...,citação lido(a) p/ aspecir uniao seguradora em...,15/05/25,2025-05-15,2025-05-15,None,SISTEMA CNJ,,citacao,None,lida,aspecir uniao seguradora em 15/05/25 obs: leit...
74,12,Citação lido(a) P/ UNIMED SEGURADORA S/A em 13...,citação lido(a) p/ unimed seguradora s/a em 13...,13/05/25,2025-05-13,2025-05-13,None,SISTEMA CNJ,,citacao,None,lida,unimed seguradora s/a em 13/05/25 obs: leitura...
79,6,Intimação lido(a) (Para JOSE CARLOS DO NASCIME...,intimação lido(a) (para jose carlos do nascime...,13/05/25,2025-05-13,2025-05-13,13/05/25,SISTEMA CNJ,,intimacao,None,lida,jose carlos do nascimento

Processo: processo_0001670-96.2025.8.05.0191 | Movimentações: 80

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,5,Intimação lido(a) (Para EDUARDO PEREIRA DOS SA...,intimação lido(a) (para eduardo pereira dos sa...,08/06/26,2026-06-08,2026-06-08,08/06/26,SISTEMA CNJ,,intimacao,None,lida,eduardo pereira dos santos alves

Processo: processo_0001673-17.2026.8.05.0191 | Movimentações: 1

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
1,10,Citação lido(a) P/ SHPS TECNOLOGIA E SERVICOS ...,citação lido(a) p/ shps tecnologia e servicos ...,11/06/26,2026-06-11,2026-06-11,None,SISTEMA CNJ,,citacao,None,lida,shps tecnologia e servicos ltda em 11/06/26 ob...
3,6,Intimação lido(a) (Para RAFAELA DANTAS SANTANA...,intimação lido(a) (para rafaela dantas santana...,10/06/26,2026-06-10,2026-06-10,10/06/26,SISTEMA CNJ,,intimacao,None,lida,rafaela dantas santana

Processo: processo_0001711-29.2026.8.05.0191 | Movimentações: 4

Empty DataFrame
Columns: [evento, ato, ato_normalizado, data_texto, data_obj, data_leitura_str, data_referencia_str, autor, observacao, categoria, meio_comunicacao, situacao_comunicacao, destinatario]
Index: []

Processo: processo_0001740-16.2025.8.05.0191 | Movimentações: 3

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
2,303,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,intimação lido(a) (para caixa de assistencia d...,02/06/26,2026-06-02,2026-06-01,21/05/26,SISTEMA CNJ,,intimacao,None,lida,caixa de assistencia dos funcionarios do banco...
13,259,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,intimação lido(a) (para caixa de assistencia d...,24/04/26,2026-04-24,2026-04-23,13/04/26,SISTEMA CNJ,,intimacao,None,lida,caixa de assistencia dos funcionarios do banco...
14,255,Intimação lido(a) (Para FLORIZA MARIA SENA FER...,intimação lido(a) (para floriza maria sena fer...,19/04/26,2026-04-19,2026-04-09,31/03/26,ECT,,intimacao,None,expedida,floriza maria sena fernandes
18,238,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,intimação lido(a) (para caixa de assistencia d...,01/04/26,2026-04-01,2026-04-01,31/03/26,SISTEMA CNJ,,intimacao,None,lida,caixa de assistencia dos funcionarios do banco...
27,197,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,intimação lido(a) (para caixa de assistencia d...,03/03/26,2026-03-03,2026-03-02,19/02/26,SISTEMA CNJ,,intimacao,None,lida,caixa de assistencia dos funcionarios do banco...
55,58,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,intimação lido(a) (para caixa de assistencia d...,12/07/25,2025-07-12,2025-07-11,01/07/25,SISTEMA CNJ,,intimacao,None,lida,caixa de assistencia dos funcionarios do banco...
63,27,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,intimação lido(a) (para caixa de assistencia d...,17/06/25,2025-06-17,2025-06-16,05/06/25,SISTEMA CNJ,,intimacao,None,lida,caixa de assistencia dos funcionarios do banco...
66,16,Intimação lido(a) (Para CAIXA DE ASSISTENCIA D...,intimação lido(a) (para caixa de assistencia d...,03/06/25,2025-06-03,2025-06-02,21/05/25,SISTEMA CNJ,,intimacao,None,expedida,caixa de assistencia dos funcionarios do banco...
67,15,Citação lido(a) P/ CAIXA DE ASSISTENCIA DOS FU...,citação lido(a) p/ caixa de assistencia dos fu...,29/05/25,2025-05-29,2025-05-29,None,SISTEMA CNJ,,citacao,None,lida,caixa de assistencia dos funcionarios do banco...
73,5,Intimação lido(a) (Para FLORIZA MARIA SENA FER...,intimação lido(a) (para floriza maria sena fer...,21/05/25,2025-05-21,2025-05-21,21/05/25,SISTEMA CNJ,,intimacao,None,lida,floriza maria sena fernandes

Processo: processo_0001781-80.2025.8.05.0191 | Movimentações: 74

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
2,52,Intimação lido(a) (Para JOSE ALDSON FRANCA MIN...,intimação lido(a) (para jose aldson franca min...,27/09/25,2025-09-27,2025-09-12,04/09/25,ECT,,intimacao,None,lida,jose aldson franca mina
7,26,Intimação lido(a) (Para JOSE ALDSON FRANCA MIN...,intimação lido(a) (para jose aldson franca min...,26/07/25,2025-07-26,2025-07-17,11/07/25,ECT,,intimacao,None,lida,jose aldson franca mina
8,25,Intimação lido(a) (Para GJT PAULO AFONSO ALUGU...,intimação lido(a) (para gjt paulo afonso alugu...,22/07/25,2025-07-22,2025-07-21,11/07/25,SISTEMA CNJ,,intimacao,None,lida,gjt paulo afonso aluguel de equipamentos ltda
14,10,Citação lido(a) P/ JOSE ALDSON FRANCA MINA em ...,citação lido(a) p/ jose aldson franca mina em ...,21/06/25,2025-06-21,2025-06-12,None,ECT,,citacao,None,lida,jose aldson franca mina em 12/06/25
16,5,Intimação lido(a) (Para GJT PAULO AFONSO ALUGU...,intimação lido(a) (para gjt paulo afonso alugu...,06/06/25,2025-06-06,2025-06-06,06/06/25,SISTEMA CNJ,,intimacao,None,lida,gjt paulo afonso aluguel de equipamentos ltda

Processo: processo_0001980-05.2025.8.05.0191 | Movimentações: 17

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
6,158,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,12/05/25,2025-05-12,2025-05-12,12/05/25,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
8,143,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,intimação lido(a) (para instituto em belleza a...,14/12/24,2024-12-14,2024-12-13,03/12/24,SISTEMA CNJ,,intimacao,None,lida,instituto em belleza aracaju ltda
10,139,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,02/12/24,2024-12-02,2024-12-02,25/11/24,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
12,128,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,01/10/24,2024-10-01,2024-10-01,01/10/24,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
14,104,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,11/07/24,2024-07-11,2024-07-11,10/07/24,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
16,96,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,intimação lido(a) (para instituto em belleza a...,07/05/24,2024-05-07,2024-05-06,24/04/24,SISTEMA CNJ,,intimacao,None,lida,instituto em belleza aracaju ltda
18,86,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,intimação lido(a) (para instituto em belleza a...,06/04/24,2024-04-06,2024-04-05,26/03/24,SISTEMA CNJ,,intimacao,None,lida,instituto em belleza aracaju ltda
19,85,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,27/03/24,2024-03-27,2024-03-27,26/03/24,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
23,75,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,intimação lido(a) (para instituto em belleza a...,02/12/23,2023-12-02,2023-12-01,21/11/23,SISTEMA CNJ,,intimacao,None,lida,instituto em belleza aracaju ltda
24,74,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,intimação lido(a) (para instituto em belleza a...,02/12/23,2023-12-02,2023-12-01,21/11/23,SISTEMA CNJ,,intimacao,None,lida,instituto em belleza aracaju ltda
25,73,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,23/11/23,2023-11-23,2023-11-23,21/11/23,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
28,67,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,21/11/23,2023-11-21,2023-11-21,21/11/23,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
31,59,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,intimação lido(a) (para instituto em belleza a...,17/11/23,2023-11-17,2023-11-16,06/11/23,SISTEMA CNJ,,intimacao,None,lida,instituto em belleza aracaju ltda
32,58,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,06/11/23,2023-11-06,2023-11-06,06/11/23,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
35,51,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,intimação lido(a) (para instituto em belleza a...,17/10/23,2023-10-17,2023-10-16,03/10/23,SISTEMA CNJ,,intimacao,None,lida,instituto em belleza aracaju ltda
36,50,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,intimação lido(a) (para instituto em belleza a...,17/10/23,2023-10-17,2023-10-16,03/10/23,SISTEMA CNJ,,intimacao,None,lida,instituto em belleza aracaju ltda
37,49,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,05/10/23,2023-10-05,2023-10-05,03/10/23,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
38,48,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,05/10/23,2023-10-05,2023-10-05,03/10/23,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
43,27,Intimação lido(a) (Para INSTITUTO EM BELLEZA A...,intimação lido(a) (para instituto em belleza a...,25/08/23,2023-08-25,2023-08-25,24/08/23,MARCIO GUSTAVO PEREIRA LIMA,,intimacao,None,lida,instituto em belleza aracaju ltda
44,26,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,24/08/23,2023-08-24,2023-08-24,24/08/23,ALBERTO DE ABREU SIQUEIRA,,intimacao,None,lida,sandra patricia restrepo pontes
50,9,Citação lido(a) P/ INSTITUTO EM BELLEZA ARACAJ...,citação lido(a) p/ instituto em belleza aracaj...,04/08/23,2023-08-04,2023-07-31,None,ECT,,citacao,None,lida,instituto em belleza aracaju ltda em 31/07/23
52,5,Intimação lido(a) (Para SANDRA PATRICIA RESTRE...,intimação lido(a) (para sandra patricia restre...,18/07/23,2023-07-18,2023-07-18,18/07/23,SISTEMA CNJ,,intimacao,None,lida,sandra patricia restrepo pontes

Processo: processo_0002009-26.2023.8.05.0191 | Movimentações: 53

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
18,60,Citação lido(a) P/ PAULO AFONSO CURSOS TECNICO...,citação lido(a) p/ paulo afonso cursos tecnico...,26/07/25,2025-07-26,2025-07-18,None,ECT,,citacao,None,lida,paulo afonso cursos tecnicos ltda em 18/07/25
31,6,Intimação lido(a) (Para KAMILLA SOUZA GOMES DA...,intimação lido(a) (para kamilla souza gomes da...,13/06/25,2025-06-13,2025-06-13,13/06/25,SISTEMA CNJ,,intimacao,None,lida,kamilla souza gomes da costa

Processo: processo_0002041-60.2025.8.05.0191 | Movimentações: 32

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
14,11,Citação lido(a) P/ PKL ONE PARTICIPACOES S.A. ...,citação lido(a) p/ pkl one participacoes s.a. ...,14/07/25,2025-07-14,2025-07-14,None,SISTEMA CNJ,,citacao,None,lida,pkl one participacoes s.a. em 14/07/25 obs: le...
15,10,Citação lido(a) P/ BANCO MASTER S A em 14/07/2...,citação lido(a) p/ banco master s a em 14/07/2...,14/07/25,2025-07-14,2025-07-14,None,SISTEMA CNJ,,citacao,None,lida,banco master s a em 14/07/25 obs: leitura real...
18,6,Intimação lido(a) (Para ALESSANDRO DA SILVA FE...,intimação lido(a) (para alessandro da silva fe...,14/07/25,2025-07-14,2025-07-14,14/07/25,SISTEMA CNJ,,intimacao,None,lida,alessandro da silva feitosa

Processo: processo_0002352-51.2025.8.05.0191 | Movimentações: 19

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
1,60,Intimação lido(a) (Para JERSON UBIRATAN DA SIL...,intimação lido(a) (para jerson ubiratan da sil...,05/10/25,2025-10-05,2025-09-19,12/09/25,ECT,,intimacao,None,lida,jerson ubiratan da silva barros
2,57,Intimação lido(a) (Para JERSON UBIRATAN DA SIL...,intimação lido(a) (para jerson ubiratan da sil...,18/09/25,2025-09-18,2025-09-05,01/09/25,ECT,,intimacao,None,lida,jerson ubiratan da silva barros
11,9,Citação lido(a) P/ JERSON UBIRATAN DA SILVA BA...,citação lido(a) p/ jerson ubiratan da silva ba...,01/08/25,2025-08-01,2025-07-24,None,ECT,,citacao,None,lida,jerson ubiratan da silva barros em 24/07/25
13,4,Intimação lido(a) (Para CONDOMINIO RESIDENCIAL...,intimação lido(a) (para condominio residencial...,18/07/25,2025-07-18,2025-07-18,18/07/25,SISTEMA CNJ,,intimacao,None,lida,condominio residencial brisas do lago

Processo: processo_0002428-75.2025.8.05.0191 | Movimentações: 14

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,273,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,16/05/26,2026-05-16,2026-05-15,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
7,259,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,29/04/26,2026-04-29,2026-04-29,28/04/26,LUCIANA ESPINHEIRA DA COSTA KHOURY,,intimacao,None,lida,núcleo de atuação mp paulo afonso
9,255,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,24/04/26,2026-04-24,2026-04-23,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
10,250,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,18/04/26,2026-04-18,2026-04-17,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
12,246,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,13/04/26,2026-04-13,2026-04-13,07/04/26,FERNANDO ROGERIO PESSOA VILA NOVA FILHO,,intimacao,None,lida,núcleo de atuação mp paulo afonso
17,218,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,15/01/26,2026-01-15,2026-01-21,15/12/25,DANIELE COCHRANE SANTIAGO DANTAS CORDEIRO,,intimacao,None,lida,núcleo de atuação mp paulo afonso
19,213,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,13/12/25,2025-12-13,2025-12-12,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
21,198,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,14/11/25,2025-11-14,2025-11-13,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
24,154,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,16/08/25,2025-08-16,2025-08-15,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
26,136,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,01/08/25,2025-08-01,2025-07-31,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
27,135,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,01/08/25,2025-08-01,2025-07-31,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
32,108,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,12/07/25,2025-07-12,2025-07-11,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
34,98,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,26/06/25,2025-06-26,2025-06-25,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
38,79,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,01/02/25,2025-02-01,2025-01-31,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
40,75,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,06/12/24,2024-12-06,2024-12-05,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
42,70,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,04/10/24,2024-10-04,2024-10-03,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
44,64,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,06/08/24,2024-08-06,2024-08-05,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
46,59,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,19/04/24,2024-04-19,2024-04-18,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
49,46,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,15/12/23,2023-12-15,2023-12-14,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
51,42,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,25/11/23,2023-11-25,2023-11-24,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
52,37,Devolução sem Leitura De Intimação expedida em...,devolução sem leitura de intimação expedida em...,08/11/23,2023-11-08,2023-10-05,05/10/23,ECT,,intimacao,None,expedida,claudio jorge fontes da fonseca
54,18,Devolução sem Leitura De Intimação expedida em...,devolução sem leitura de intimação expedida em...,24/10/23,2023-10-24,2023-10-05,05/10/23,ECT,,intimacao,None,expedida,paulo henrique da silva vasconcelos
55,17,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,17/10/23,2023-10-17,2023-10-16,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso

Processo: processo_0002784-41.2023.8.05.0191 | Movimentações: 60

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
16,30,Intimação lido(a) (Para VOLTZ MOTORS DO BRASIL...,intimação lido(a) (para voltz motors do brasil...,27/01/25,2025-01-27,2025-01-24,14/01/25,SISTEMA CNJ,,intimacao,None,lida,voltz motors do brasil comercio de motocicleta...
17,29,Intimação lido(a) (Para HEVITON OLIVEIRA RODRI...,intimação lido(a) (para heviton oliveira rodri...,27/01/25,2025-01-27,2025-01-24,14/01/25,SISTEMA CNJ,,intimacao,None,lida,heviton oliveira rodrigues
24,8,Citação lido(a) P/ VOLTZ MOTORS DO BRASIL COME...,citação lido(a) p/ voltz motors do brasil come...,10/09/24,2024-09-10,2024-09-10,None,SISTEMA CNJ,,citacao,None,lida,voltz motors do brasil comercio de motocicleta...
26,5,Intimação lido(a) (Para HEVITON OLIVEIRA RODRI...,intimação lido(a) (para heviton oliveira rodri...,28/08/24,2024-08-28,2024-08-28,28/08/24,SISTEMA CNJ,,intimacao,None,lida,heviton oliveira rodrigues

Processo: processo_0002914-94.2024.8.05.0191 | Movimentações: 27

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
3,61,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,intimação lido(a) (para robson de oliveira sil...,21/06/24,2024-06-21,2024-06-20,10/06/24,SISTEMA CNJ,,intimacao,None,lida,robson de oliveira silva
5,51,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,intimação lido(a) (para robson de oliveira sil...,07/05/24,2024-05-07,2024-05-06,25/04/24,SISTEMA CNJ,,intimacao,None,lida,robson de oliveira silva
6,50,Intimação lido(a) (Para FABIANA DOS SANTOS SIL...,intimação lido(a) (para fabiana dos santos sil...,25/04/24,2024-04-25,2024-04-25,25/04/24,WAGNER LIMA DOS SANTOS,,intimacao,None,lida,fabiana dos santos silva gomes marmoraria
9,44,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,intimação lido(a) (para robson de oliveira sil...,24/03/24,2024-03-24,2024-03-18,06/03/24,ECT,,intimacao,None,lida,robson de oliveira silva
10,42,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,intimação lido(a) (para robson de oliveira sil...,24/03/24,2024-03-24,2024-03-18,06/03/24,ECT,,intimacao,None,lida,robson de oliveira silva
11,40,Intimação lido(a) (Para ROBSON DE OLIVEIRA SIL...,intimação lido(a) (para robson de oliveira sil...,24/03/24,2024-03-24,2024-03-18,06/03/24,ECT,,intimacao,None,lida,robson de oliveira silva
13,35,Intimação lido(a) (Para FABIANA DOS SANTOS SIL...,intimação lido(a) (para fabiana dos santos sil...,06/03/24,2024-03-06,2024-03-06,06/03/24,WAGNER LIMA DOS SANTOS,,intimacao,None,lida,fabiana dos santos silva gomes marmoraria
14,34,Intimação lido(a) (Para FABIANA DOS SANTOS SIL...,intimação lido(a) (para fabiana dos santos sil...,06/03/24,2024-03-06,2024-03-06,06/03/24,WAGNER LIMA DOS SANTOS,,intimacao,None,lida,fabiana dos santos silva gomes marmoraria
23,8,Citação lido(a) P/ ROBSON DE OLIVEIRA SILVA em...,citação lido(a) p/ robson de oliveira silva em...,25/11/23,2023-11-25,2023-11-17,None,ECT,,citacao,None,lida,robson de oliveira silva em 17/11/23
25,4,Intimação lido(a) (Para FABIANA DOS SANTOS SIL...,intimação lido(a) (para fabiana dos santos sil...,01/11/23,2023-11-01,2023-11-01,01/11/23,SISTEMA CNJ,,intimacao,None,lida,fabiana dos santos silva gomes marmoraria

Processo: processo_0003074-56.2023.8.05.0191 | Movimentações: 26

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
1,81,Intimação lido(a) (Para BANCO BRADESCO S A) em...,intimação lido(a) (para banco bradesco s a) em...,20/02/26,2026-02-20,2026-02-19,06/02/26,SISTEMA CNJ,,intimacao,None,lida,banco bradesco s a
9,36,Citação lido(a) P/ BANCO BRADESCO S A em 30/10/25,citação lido(a) p/ banco bradesco s a em 30/10/25,25/11/25,2025-11-25,2025-10-30,None,ECT,,citacao,None,lida,banco bradesco s a em 30/10/25
13,20,Intimação lido(a) (Para BANCO BRADESCO S A) em...,intimação lido(a) (para banco bradesco s a) em...,25/10/25,2025-10-25,2025-10-24,14/10/25,SISTEMA CNJ,,intimacao,None,lida,banco bradesco s a
18,6,Intimação lido(a) (Para WENDEL CORDEIRO MARQUE...,intimação lido(a) (para wendel cordeiro marque...,14/10/25,2025-10-14,2025-10-14,14/10/25,SISTEMA CNJ,,intimacao,None,lida,wendel cordeiro marques

Processo: processo_0003363-18.2025.8.05.0191 | Movimentações: 19

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
1,117,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,07/02/26,2026-02-07,2026-02-06,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
3,103,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,20/01/26,2026-01-20,2026-01-21,15/12/25,FERNANDO ROGERIO PESSOA VILA NOVA FILHO,,intimacao,None,lida,núcleo de atuação mp paulo afonso
6,91,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,21/10/25,2025-10-21,2025-10-21,20/10/25,FERNANDO ROGERIO PESSOA VILA NOVA FILHO,,intimacao,None,lida,núcleo de atuação mp paulo afonso
8,80,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,26/09/25,2025-09-26,2025-09-25,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
10,68,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,16/07/25,2025-07-16,2025-07-16,09/07/25,FERNANDO ROGERIO PESSOA VILA NOVA FILHO,,intimacao,None,lida,núcleo de atuação mp paulo afonso
12,61,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,08/07/25,2025-07-08,2025-07-07,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
14,46,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,05/11/24,2024-11-05,2024-11-04,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
16,42,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,24/09/24,2024-09-24,2024-09-23,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
18,18,Intimação lido(a) (Para WILSON OLIVEIRA DA SIL...,intimação lido(a) (para wilson oliveira da sil...,28/12/23,2023-12-28,2023-12-19,04/12/23,ECT,,intimacao,None,lida,wilson oliveira da silva
19,17,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,15/12/23,2023-12-15,2023-12-14,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso

Processo: processo_0003383-77.2023.8.05.0191 | Movimentações: 22

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
10,7,Citação lido(a) P/ EDITORA E DISTRIBUIDORA EDU...,citação lido(a) p/ editora e distribuidora edu...,24/10/25,2025-10-24,2025-10-24,None,SISTEMA CNJ,,citacao,None,lida,editora e distribuidora educacional s a em 24/...
12,4,Intimação lido(a) (Para LUANY GABRIELY BARBOZA...,intimação lido(a) (para luany gabriely barboza...,23/10/25,2025-10-23,2025-10-23,23/10/25,SISTEMA CNJ,,intimacao,None,lida,luany gabriely barboza dos santos

Processo: processo_0003484-46.2025.8.05.0191 | Movimentações: 13

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
10,5,Intimação lido(a) (Para LUIZ RICARDO DA SILVA ...,intimação lido(a) (para luiz ricardo da silva ...,23/10/25,2025-10-23,2025-10-23,23/10/25,SISTEMA CNJ,,intimacao,None,lida,luiz ricardo da silva santana

Processo: processo_0003485-31.2025.8.05.0191 | Movimentações: 11

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
15,42,Citação lido(a) P/ BANCO BRADESCO FINANCIAMENT...,citação lido(a) p/ banco bradesco financiament...,05/12/25,2025-12-05,2025-11-12,None,ECT,,citacao,None,lida,banco bradesco financiamentos s a em 12/11/25
20,22,Intimação lido(a) (Para BANCO BRADESCO FINANCI...,intimação lido(a) (para banco bradesco financi...,04/11/25,2025-11-04,2025-11-03,24/10/25,SISTEMA CNJ,,intimacao,None,lida,banco bradesco financiamentos s a
26,6,Intimação lido(a) (Para MARIA JOSE BEZERRA) em...,intimação lido(a) (para maria jose bezerra) em...,24/10/25,2025-10-24,2025-10-24,24/10/25,SISTEMA CNJ,,intimacao,None,lida,maria jose bezerra

Processo: processo_0003496-60.2025.8.05.0191 | Movimentações: 27

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
5,29,Intimação lido(a) (Para CAMILA FERNADES DE ARA...,intimação lido(a) (para camila fernades de ara...,05/12/25,2025-12-05,2025-11-06,30/10/25,ECT,,intimacao,None,lida,camila fernades de araujo

Processo: processo_0003540-79.2025.8.05.0191 | Movimentações: 9

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
21,8,Citação lido(a) P/ Representante: EMPRESA BAIA...,citação lido(a) p/ representante: empresa baia...,12/11/25,2025-11-12,2025-11-12,None,ELISANGELA DE QUEIROZ FERNANDES BRITO,,citacao,None,lida,representante: empresa baiana de aguas e sanea...
23,4,Intimação lido(a) (Para ENIVALDA AUREA DE MATO...,intimação lido(a) (para enivalda aurea de mato...,11/11/25,2025-11-11,2025-11-11,11/11/25,SISTEMA CNJ,,intimacao,None,lida,enivalda aurea de matos

Processo: processo_0003704-44.2025.8.05.0191 | Movimentações: 24

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
3,34,Intimação lido(a) (Para EDMILSON LOPES CABRAL)...,intimação lido(a) (para edmilson lopes cabral)...,01/04/25,2025-04-01,2025-04-01,01/04/25,BRUNA PEREIRA DE SOUZA SILVA,,intimacao,None,lida,edmilson lopes cabral
5,30,Intimação lido(a) (Para PREVEBENE ADMINISTRADO...,intimação lido(a) (para prevebene administrado...,11/03/25,2025-03-11,2025-03-10,26/02/25,SISTEMA CNJ,,intimacao,None,lida,prevebene administradora de beneficios e promo...
7,22,Intimação lido(a) (Para PREVEBENE ADMINISTRADO...,intimação lido(a) (para prevebene administrado...,20/12/24,2024-12-20,2024-12-19,09/12/24,SISTEMA CNJ,,intimacao,None,lida,prevebene administradora de beneficios e promo...
8,21,Intimação lido(a) (Para EDMILSON LOPES CABRAL)...,intimação lido(a) (para edmilson lopes cabral)...,09/12/24,2024-12-09,2024-12-09,09/12/24,BRUNA PEREIRA DE SOUZA SILVA,,intimacao,None,lida,edmilson lopes cabral
12,8,Citação lido(a) P/ PREVEBENE ADMINISTRADORA DE...,citação lido(a) p/ prevebene administradora de...,04/11/24,2024-11-04,2024-11-04,None,SISTEMA CNJ,,citacao,None,lida,prevebene administradora de beneficios e promo...
14,5,Intimação lido(a) (Para EDMILSON LOPES CABRAL)...,intimação lido(a) (para edmilson lopes cabral)...,03/11/24,2024-11-03,2024-11-03,03/11/24,SISTEMA CNJ,,intimacao,None,lida,edmilson lopes cabral

Processo: processo_0003806-03.2024.8.05.0191 | Movimentações: 15

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
2,27,Intimação lido(a) (Para TRANSPORTE COLETIVO BR...,intimação lido(a) (para transporte coletivo br...,24/04/25,2025-04-24,2025-04-23,13/04/25,SISTEMA CNJ,,intimacao,None,lida,transporte coletivo brasil ltda
4,16,Intimação lido(a) (Para ADAILTON PEREIRA DA SI...,intimação lido(a) (para adailton pereira da si...,27/01/25,2025-01-27,2025-01-24,14/01/25,SISTEMA CNJ,,intimacao,None,lida,adailton pereira da silva
7,8,Citação lido(a) P/ TRANSPORTE COLETIVO BRASIL ...,citação lido(a) p/ transporte coletivo brasil ...,15/11/24,2024-11-15,2024-11-18,None,SISTEMA CNJ,,citacao,None,lida,transporte coletivo brasil ltda em 18/11/24 ob...
9,5,Intimação lido(a) (Para ADAILTON PEREIRA DA SI...,intimação lido(a) (para adailton pereira da si...,04/11/24,2024-11-04,2024-11-04,04/11/24,SISTEMA CNJ,,intimacao,None,lida,adailton pereira da silva

Processo: processo_0003821-69.2024.8.05.0191 | Movimentações: 10

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,112,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,31/03/26,2026-03-31,2026-03-30,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
3,94,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,07/02/26,2026-02-07,2026-02-06,None,SISTEMA CNJ,,intimacao,mandado,lida,núcleo de atuação mp paulo afonso
5,79,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,20/01/26,2026-01-20,2026-01-21,15/12/25,FERNANDO ROGERIO PESSOA VILA NOVA FILHO,,intimacao,None,lida,núcleo de atuação mp paulo afonso
7,74,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,04/11/25,2025-11-04,2025-11-03,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
10,65,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,09/10/25,2025-10-09,2025-10-09,07/10/25,FERNANDO ROGERIO PESSOA VILA NOVA FILHO,,intimacao,None,lida,núcleo de atuação mp paulo afonso
12,61,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,03/10/25,2025-10-03,2025-10-02,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
14,40,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,14/08/25,2025-08-14,2025-08-14,12/08/25,FERNANDO ROGERIO PESSOA VILA NOVA FILHO,,intimacao,None,lida,núcleo de atuação mp paulo afonso
16,24,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,23/04/25,2025-04-23,2025-04-22,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso
19,16,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,29/11/24,2024-11-29,2024-11-28,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso

Processo: processo_0004024-31.2024.8.05.0191 | Movimentações: 21

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
1,29,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,06/03/26,2026-03-06,2026-03-06,02/03/26,FERNANDO ROGERIO PESSOA VILA NOVA FILHO,,intimacao,None,lida,núcleo de atuação mp paulo afonso
4,14,Intimação lido(a) (Para CICERO ALENCAR DA SILV...,intimação lido(a) (para cicero alencar da silv...,06/02/26,2026-02-06,2026-01-21,12/01/26,ECT,,intimacao,None,lida,cicero alencar da silva
5,13,Intimação lido(a) (Para Núcleo de Atuação MP P...,intimação lido(a) (para núcleo de atuação mp p...,23/01/26,2026-01-23,2026-01-22,None,SISTEMA CNJ,,intimacao,None,lida,núcleo de atuação mp paulo afonso

Processo: processo_0004152-17.2025.8.05.0191 | Movimentações: 8

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
0,20,Intimação lido(a) (Para OI MOVEL S A SOCIEDADE...,intimação lido(a) (para oi movel s a sociedade...,21/01/19,2019-01-21,2019-01-21,17/12/18,SISTEMA CNJ,,intimacao,None,lida,oi movel s a sociedade empresaria em recuperac...
1,19,Intimação lido(a) (Para SEVERINO ALVES DE OLIV...,intimação lido(a) (para severino alves de oliv...,21/01/19,2019-01-21,2019-01-21,17/12/18,SISTEMA CNJ,,intimacao,None,lida,severino alves de oliveira lima
5,8,Citação lido(a) P/ OI MOVEL S A SOCIEDADE EMPR...,citação lido(a) p/ oi movel s a sociedade empr...,14/11/18,2018-11-14,2018-11-08,None,ECT,,citacao,None,lida,oi movel s a sociedade empresaria em recuperac...
7,4,Intimação lido(a) (Para SEVERINO ALVES DE OLIV...,intimação lido(a) (para severino alves de oliv...,31/10/18,2018-10-31,2018-10-31,31/10/18,SISTEMA CNJ,,intimacao,None,lida,severino alves de oliveira lima

Processo: processo_0007018-42.2018.8.05.0191 | Movimentações: 8

In [ ]:
display(atos_relacionados[p])

NameError: name 'atos_relacionados' is not defined

In [ ]:
for i, j in atos_relacionados.items():
    display(i, j)

NameError: name 'atos_relacionados' is not defined

In [ ]:
abc

NameError: name 'abc' is not defined

In [ ]:
df_relacoes = pd.DataFrame({

    'ato_origem':
        relacoes['ato_origem'],

    'data_origem':
        relacoes['data_origem'],

    'destinatario':
        relacoes['destinatario_lido'],

    'meio':
        relacoes['meio_real'],

    'canal':
        relacoes['meio_comunicacao_expedido'],

    'evento_lido':
        relacoes['evento_lido'],
        'data_leitura':
        relacoes['data_leitura_str_lido'],
     'prazo':
        relacoes['ato_expedido'].str.extract(
            r'(\d+\s*dias?)',
            expand=False
        ),

    'evento_expedido':
        relacoes['evento_expedido'],

    'data_expedicao':
        relacoes['data_texto_expedido'],

   

    'ato_expedido':
        relacoes['ato_expedido'],

    'ato_lido':
        relacoes['ato_lido']
})

TypeError: 'function' object is not subscriptable

In [ ]:
display(df_relacoes)

,evento_expedido,data_expedicao,ato_expedido,destinatario,meio,canal,ato_lido,data_leitura,evento_lido,prazo,ato_origem,data_origem,key,automatiza,canais_historicos
0,17,17/12/18,Intimação expedido(a) (P/ Advgs. de OI MOVEL S...,oi movel s a sociedade empresaria em recuperac...,advogado,domicilio_cnj,Intimação lido(a) (Para OI MOVEL S A SOCIEDADE...,2019-01-21,20,NaN,Intimação à disposição,17/12/18,oi movel s a sociedade empresaria em recuperac...,automatizar,"advogado, pessoal"
1,16,17/12/18,Intimação expedido(a) (P/ Advgs. de SEVERINO A...,severino alves de oliveira lima,advogado,domicilio_cnj,Intimação lido(a) (Para SEVERINO ALVES DE OLIV...,2019-01-21,19,NaN,Intimação à disposição,17/12/18,severino alves de oliveira lima,automatizar,advogado

In [ ]:
for destinatario, grupo in df.groupby('destinatario'):

    grupo = grupo.sort_values('data_obj')
    display(grupo)

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
6,6,Citação expedido(a) Para OI MOVEL S A SOCIEDAD...,citação expedido(a) para oi movel s a sociedad...,31/10/18,2018-10-31,None,None,MARCELO PEREIRA DA SILVAA,,citacao,None,expedida,oi movel s a sociedade empresaria em recuperac...
2,17,Intimação expedido(a) (P/ Advgs. de OI MOVEL S...,intimação expedido(a) (p/ advgs. de oi movel s...,17/12/18,2018-12-17,None,None,IVAN GUEDES DA SILVA,,intimacao,domicilio_cnj,expedida,oi movel s a sociedade empresaria em recuperac...
0,20,Intimação lido(a) (Para OI MOVEL S A SOCIEDADE...,intimação lido(a) (para oi movel s a sociedade...,21/01/19,2019-01-21,2019-01-21,17/12/18,SISTEMA CNJ,,intimacao,None,lida,oi movel s a sociedade empresaria em recuperac...

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
5,8,Citação lido(a) P/ OI MOVEL S A SOCIEDADE EMPR...,citação lido(a) p/ oi movel s a sociedade empr...,14/11/18,2018-11-14,2018-11-08,None,ECT,,citacao,None,lida,oi movel s a sociedade empresaria em recuperac...

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
7,4,Intimação lido(a) (Para SEVERINO ALVES DE OLIV...,intimação lido(a) (para severino alves de oliv...,31/10/18,2018-10-31,2018-10-31,31/10/18,SISTEMA CNJ,,intimacao,None,lida,severino alves de oliveira lima
3,16,Intimação expedido(a) (P/ Advgs. de SEVERINO A...,intimação expedido(a) (p/ advgs. de severino a...,17/12/18,2018-12-17,None,None,IVAN GUEDES DA SILVA,,intimacao,domicilio_cnj,expedida,severino alves de oliveira lima
1,19,Intimação lido(a) (Para SEVERINO ALVES DE OLIV...,intimação lido(a) (para severino alves de oliv...,21/01/19,2019-01-21,2019-01-21,17/12/18,SISTEMA CNJ,,intimacao,None,lida,severino alves de oliveira lima

In [ ]:
lidas = grupo[
    grupo['situacao_comunicacao'] == 'lida'
]
expedidas = grupo[
    grupo['situacao_comunicacao'] == 'expedida'
]

In [ ]:
display(lidas)

,evento,ato,ato_normalizado,data_texto,data_obj,data_leitura_str,data_referencia_str,autor,observacao,categoria,meio_comunicacao,situacao_comunicacao,destinatario
7,4,Intimação lido(a) (Para SEVERINO ALVES DE OLIV...,intimação lido(a) (para severino alves de oliv...,31/10/18,2018-10-31,2018-10-31,31/10/18,SISTEMA CNJ,,intimacao,None,lida,severino alves de oliveira lima
1,19,Intimação lido(a) (Para SEVERINO ALVES DE OLIV...,intimação lido(a) (para severino alves de oliv...,21/01/19,2019-01-21,2019-01-21,17/12/18,SISTEMA CNJ,,intimacao,None,lida,severino alves de oliveira lima

In [ ]:
resultado = []

for _, lido in lidas.iterrows():

    expedido = expedidas[
        (
            expedidas['destinatario']
            == lido['destinatario']
        )
        &
        (
            expedidas['data_obj']
            ==
            pd.to_datetime(
                lido['data_referencia_str'],
                dayfirst=True
            )
        )
    ]

    if len(expedido):

        expedido = expedido.iloc[0]

        resultado.append({

            'destinatario':
                lido['destinatario'],

            'evento_expedido':
                expedido['evento'],

            'evento_lido':
                lido['evento'],

            'data_expedicao':
                expedido['data_obj'],

            'data_leitura':
                lido['data_obj'],

            'meio':
                expedido['meio_comunicacao']
        })

In [ ]:
print(resultado)

[]

In [ ]:
def buscar_relacao_evento(ato):
    
    padrao = re.search(
        # r'Intimação\s+(lido\(a\)|expedido\(a\))'
        # r'\s+(lido\(a\)|expedido\(a\))'
        r'(.+?)\s+(lido\(a\)|expedido\(a\))' #qualquer documento lido ou expedido
        r'.*?\(Para\s+(.*?)\)'
        r'.*?em\s+(\d{2}/\d{2}/\d{2})',
        # r'\(P/\s+Advgs?\.\s+de\s+(.*?)\)',
        # r'.*?\*Referente ao evento\s+(.*?)\((\d{2}/\d{2}/\d{2})\)',
        ato,
        re.I | re.S
    )
    return padrao

In [ ]:
processos = []
for process_json in pasta.glob('*.json'):
    with open(process_json, 'r', encoding='utf-8') as f:
        processo = json.load(f)
        processos.append(processo)
# print(len(processos))
        df = pd.DataFrame(processos['movimentacoes'])
    display(df)

TypeError: list indices must be integers or slices, not str

In [ ]:
def referencia(ato):
    m_referente = re.search(r'\*Referente ao evento\s+(.*?)\((\d{2}/\d{2}/\d{2})\)', ato,re.I)

    if m_referente:
        evento = m_referente.group(1).strip()
        data_referencia = m_referente.group(2)

        print(f'''ref: {evento}
data referência {data_referencia}''')
        print('')
    return m_referente
        # print(data_referencia)
        
def destinatario(ato):

    #advogado
    m_adv = re.search(r'\(P/\s+Advgs?\.\s+de\s+(.*?)\)', ato, re.I)
    if m_adv:
        return {'tipo': 'advogado', 'nome': m_adv.group(1).strip()}
    # Advogado

    # DJEN
    m_djen = re.search(r'\bDJEN\b',ato,re.I)
    if m_djen:
        return {'tipo': 'djen', 'nome': m_djen.group(0).strip()}

    # AR
    m_ar = re.search(r'Juntada\s+de\s+AR',ato,re.I)
    if m_ar:
        return {'tipo': 'ar', 'nome': m_ar.group(0).strip()}
   

    # parte
    m = re.search(r'\(Para\s+(.*?)\)',ato,re.I)

    if m: 
        return {'tipo': 'parte','nome': m.group(1).strip()}

    return None

In [ ]:
eventos_encadeados = []

for processo in processos:

    for mov in processo['movimentacoes']:

        # 1. Precisa ser um evento lido
        rel_lido = buscar_relacao_evento(mov['ato'])

        if not rel_lido:
            continue

        if rel_lido.group(2) != 'lido(a)':
            continue

        destinatario_lido = rel_lido.group(3)

        # 2. Precisa ter referência ao ato origem
        ref = referencia(mov['ato'])

        if not ref:
            continue

        nome_origem = ref.group(1).strip()
        data_origem = ref.group(2)

        # 3. Encontrar o ato origem
        ato_origem = None

        for mov_ref in processo['movimentacoes']:

            if mov_ref['data_texto'] != data_origem:
                continue

            if nome_origem.lower() in mov_ref['ato'].lower():
                ato_origem = mov_ref
                break

        if not ato_origem:
            continue

ref: Ato ordinatório praticado
data referência 28/04/26

ref: Ato ordinatório praticado
data referência 28/04/26

ref: Intimação à disposição
data referência 21/01/26

ref: Intimação à disposição
data referência 21/01/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 15/01/26

ref: Concedida a Medida Liminar
data referência 09/03/26

ref: Extinta a execução ou o cumprimento da sentença
data referência 10/10/25

ref: Julgada procedente a ação
data referência 06/05/25

ref: Julgada procedente a ação
data referência 06/05/25

ref: Intimação à disposição
data referência 17/02/25

ref: Intimação à disposição
data referência 17/02/25

ref: Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA
data referência 06/02/25

ref: Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA
data referência 06/02/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 06/02/25

ref: Intimação à disposição
data referência 30/10/24

ref: Proferido despacho de mero expediente
data referência 16/10/24

ref: Intimação à disposição
data referência 05/06/24

ref: Intimação à disposição
data referência 17/04/23

ref: Julgada procedente em parte a ação
data referência 22/03/23

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 16/02/23

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 12/03/26

ref: Intimação à disposição
data referência 27/04/26

ref: Intimação expedido(a)
data referência 09/03/26

ref: Documento analisado
data referência 07/11/25

ref: Informações prestadas pela autoridade coatora expedido(a)
data referência 05/05/25

ref: Informações prestadas pela autoridade coatora expedido(a)
data referência 05/05/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 07/04/26

ref: Julgada procedente a ação
data referência 13/05/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 02/04/25

ref: Proferido despacho de mero expediente
data referência 24/04/26

ref: Proferido despacho de mero expediente
data referência 01/04/26

ref: Intimação à disposição
data referência 28/04/25

ref: Ato ordinatório praticado
data referência 15/04/25

ref: Ato ordinatório praticado
data referência 15/04/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 12/04/25

ref: Ato ordinatório praticado
data referência 20/05/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 20/05/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 25/05/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 02/06/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 03/06/26

ref: Intimação expedido(a)
data referência 15/05/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 13/05/25

ref: Intimação para Videoconferência à disposição
data referência 07/07/25

ref: Intimação à disposição
data referência 07/07/25

ref: Extinto o processo por Perempção, litispendência ou coisa julgada
data referência 13/05/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 13/05/25

ref: Proferido despacho de mero expediente
data referência 04/09/25

ref: Julgada procedente em parte a ação
data referência 11/07/25

ref: Julgada procedente em parte a ação
data referência 11/07/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 06/06/25

ref: Intimação à disposição
data referência 12/05/25

ref: Documento analisado
data referência 03/12/24

ref: Intimação à disposição
data referência 25/11/24

ref: Intimação à disposição
data referência 01/10/24

ref: Proferido despacho de mero expediente
data referência 10/07/24

ref: Documento analisado
data referência 24/04/24

ref: Julgada procedente em parte a ação
data referência 26/03/24

ref: Julgada procedente em parte a ação
data referência 26/03/24

ref: Intimação para Videoconferência à disposição
data referência 21/11/23

ref: Proferido despacho de mero expediente
data referência 21/11/23

ref: Intimação para Videoconferência à disposição
data referência 21/11/23

ref: Proferido despacho de mero expediente
data referência 21/11/23

ref: Intimação para Videoconferência à disposição
data referência 06/11/23

ref: Intimação para Videoconferência à disposição
data referência 06/11/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 24/08/23

ref: Intimação para Videoconferência à disposição
data referência 24/08/23

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 18/07/23

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 13/06/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 14/07/25

ref: Intimação à disposição
data referência 12/09/25

ref: Intimação à disposição
data referência 01/09/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 18/07/25

ref: Intimação à disposição
data referência 14/01/25

ref: Intimação à disposição
data referência 14/01/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 28/08/24

ref: Intimação à disposição
data referência 10/06/24

ref: Julgada procedente em parte a ação
data referência 25/04/24

ref: Julgada procedente em parte a ação
data referência 25/04/24

ref: Intimação para Videoconferência à disposição
data referência 06/03/24

ref: Intimação para Videoconferência à disposição
data referência 06/03/24

ref: Proferido despacho de mero expediente
data referência 06/03/24

ref: Intimação para Videoconferência à disposição
data referência 06/03/24

ref: Proferido despacho de mero expediente
data referência 06/03/24

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 01/11/23

ref: Proferido despacho de mero expediente
data referência 06/02/26

ref: Intimação à disposição
data referência 14/10/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 14/10/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 23/10/25

ref: Intimação à disposição
data referência 24/10/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 24/10/25

ref: Intimação à disposição
data referência 01/04/25

ref: Proferido despacho de mero expediente
data referência 26/02/25

ref: Intimação à disposição
data referência 09/12/24

ref: Intimação à disposição
data referência 09/12/24

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 03/11/24

ref: Intimação à disposição
data referência 17/12/18

ref: Intimação à disposição
data referência 17/12/18

ref: Audiência  de Conciliação Designada
data referência 31/10/18

In [ ]:
eventos_encadeados = []

for processo in processos:

    for mov_lido in processo['movimentacoes']:

        # 1 - localizar leitura
        rel_lido = buscar_relacao_evento(mov_lido['ato'])

        if not rel_lido:
            continue

        if rel_lido.group(2) != 'lido(a)':
            continue

        destinatario_lido = rel_lido.group(3)

        # 2 - localizar referência
        ref = referencia(mov_lido['ato'])

        if not ref:
            continue

        nome_origem = ref.group(1).strip()
        data_origem = ref.group(2)

        # 3 - localizar ato origem
        ato_origem = next(
            (
                m for m in processo['movimentacoes']
                if m['data_texto'] == data_origem
                and nome_origem.lower() in m['ato'].lower()
            ),
            None
        )

        if not ato_origem:
            continue

        # 4 - localizar expedição correspondente
        evento_expedido = None
        meio_expedido = None

        for mov_exp in processo['movimentacoes']:

            rel_exp = buscar_relacao_evento(mov_exp['ato'])

            if not rel_exp:
                continue

            if rel_exp.group(2) != 'expedido(a)':
                continue

            info_exp = destinatario(mov_exp['ato'])

            if not info_exp:
                continue

            # mesmo destinatário
            if info_exp['nome'] != destinatario_lido:
                continue

            evento_expedido = mov_exp
            meio_expedido = info_exp['tipo']
            break

        # 5 - montar cadeia
        eventos_encadeados.append({
            'ato_origem': ato_origem,
            'evento_expedido': evento_expedido,
            'evento_lido': mov_lido,

            'destinatario': destinatario_lido,

            'meio_expedido': meio_expedido,
            'meio_lido': 'parte',

            'evento_referenciado': nome_origem,
            'data_referencia': data_origem,
        })

ref: Ato ordinatório praticado
data referência 28/04/26

ref: Ato ordinatório praticado
data referência 28/04/26

ref: Intimação à disposição
data referência 21/01/26

ref: Intimação à disposição
data referência 21/01/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 15/01/26

ref: Concedida a Medida Liminar
data referência 09/03/26

ref: Extinta a execução ou o cumprimento da sentença
data referência 10/10/25

ref: Julgada procedente a ação
data referência 06/05/25

ref: Julgada procedente a ação
data referência 06/05/25

ref: Intimação à disposição
data referência 17/02/25

ref: Intimação à disposição
data referência 17/02/25

ref: Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA
data referência 06/02/25

ref: Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA
data referência 06/02/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 06/02/25

ref: Intimação à disposição
data referência 30/10/24

ref: Proferido despacho de mero expediente
data referência 16/10/24

ref: Intimação à disposição
data referência 05/06/24

ref: Intimação à disposição
data referência 17/04/23

ref: Julgada procedente em parte a ação
data referência 22/03/23

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 16/02/23

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 12/03/26

ref: Intimação à disposição
data referência 27/04/26

ref: Intimação expedido(a)
data referência 09/03/26

ref: Documento analisado
data referência 07/11/25

ref: Informações prestadas pela autoridade coatora expedido(a)
data referência 05/05/25

ref: Informações prestadas pela autoridade coatora expedido(a)
data referência 05/05/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 07/04/26

ref: Julgada procedente a ação
data referência 13/05/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 02/04/25

ref: Proferido despacho de mero expediente
data referência 24/04/26

ref: Proferido despacho de mero expediente
data referência 01/04/26

ref: Intimação à disposição
data referência 28/04/25

ref: Ato ordinatório praticado
data referência 15/04/25

ref: Ato ordinatório praticado
data referência 15/04/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 12/04/25

ref: Ato ordinatório praticado
data referência 20/05/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 20/05/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 25/05/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 02/06/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 03/06/26

ref: Intimação expedido(a)
data referência 15/05/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 13/05/25

ref: Intimação para Videoconferência à disposição
data referência 07/07/25

ref: Intimação à disposição
data referência 07/07/25

ref: Extinto o processo por Perempção, litispendência ou coisa julgada
data referência 13/05/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 13/05/25

ref: Proferido despacho de mero expediente
data referência 04/09/25

ref: Julgada procedente em parte a ação
data referência 11/07/25

ref: Julgada procedente em parte a ação
data referência 11/07/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 06/06/25

ref: Intimação à disposição
data referência 12/05/25

ref: Documento analisado
data referência 03/12/24

ref: Intimação à disposição
data referência 25/11/24

ref: Intimação à disposição
data referência 01/10/24

ref: Proferido despacho de mero expediente
data referência 10/07/24

ref: Documento analisado
data referência 24/04/24

ref: Julgada procedente em parte a ação
data referência 26/03/24

ref: Julgada procedente em parte a ação
data referência 26/03/24

ref: Intimação para Videoconferência à disposição
data referência 21/11/23

ref: Proferido despacho de mero expediente
data referência 21/11/23

ref: Intimação para Videoconferência à disposição
data referência 21/11/23

ref: Proferido despacho de mero expediente
data referência 21/11/23

ref: Intimação para Videoconferência à disposição
data referência 06/11/23

ref: Intimação para Videoconferência à disposição
data referência 06/11/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 24/08/23

ref: Intimação para Videoconferência à disposição
data referência 24/08/23

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 18/07/23

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 13/06/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 14/07/25

ref: Intimação à disposição
data referência 12/09/25

ref: Intimação à disposição
data referência 01/09/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 18/07/25

ref: Intimação à disposição
data referência 14/01/25

ref: Intimação à disposição
data referência 14/01/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 28/08/24

ref: Intimação à disposição
data referência 10/06/24

ref: Julgada procedente em parte a ação
data referência 25/04/24

ref: Julgada procedente em parte a ação
data referência 25/04/24

ref: Intimação para Videoconferência à disposição
data referência 06/03/24

ref: Intimação para Videoconferência à disposição
data referência 06/03/24

ref: Proferido despacho de mero expediente
data referência 06/03/24

ref: Intimação para Videoconferência à disposição
data referência 06/03/24

ref: Proferido despacho de mero expediente
data referência 06/03/24

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 01/11/23

ref: Proferido despacho de mero expediente
data referência 06/02/26

ref: Intimação à disposição
data referência 14/10/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 14/10/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 23/10/25

ref: Intimação à disposição
data referência 24/10/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 24/10/25

ref: Intimação à disposição
data referência 01/04/25

ref: Proferido despacho de mero expediente
data referência 26/02/25

ref: Intimação à disposição
data referência 09/12/24

ref: Intimação à disposição
data referência 09/12/24

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 03/11/24

ref: Intimação à disposição
data referência 17/12/18

ref: Intimação à disposição
data referência 17/12/18

ref: Audiência  de Conciliação Designada
data referência 31/10/18

In [ ]:
eventos_encadeados = []

for processo in processos:
    for mov in processo['movimentacoes']:
        if 'lido(a)' in mov['ato']:
            print(f"Ev FILHO :{mov['evento']} - {mov['ato']}")
            evento_relacionado_filho = buscar_relacao_evento(mov['ato'])

            if evento_relacionado_filho:
                data_referencia = referencia(mov['ato']).group(2)
                destinatario_filho = buscar_relacao_evento(mov['ato']).group(3)
                # if not destinatario_filho:
                #     continue
            if data_referencia:
                for mov_ref in processo['movimentacoes']:
                    if mov_ref['data_texto'] == data_referencia:
                        evento_relacionado_pai = buscar_relacao_evento(mov_ref['ato'])
                        mov_pai = mov_ref
                        # dados_evento_pai = buscar_relacao_evento(mov_pai)
                        # if dados_evento_pai:
                        #     print(dados_evento_pai.group(2))
                if mov_pai:
                    evento_relacionado_pai = buscar_relacao_evento(mov_pai['ato'])
                    if evento_relacionado_pai:
                        documento = evento_relacionado_pai.group(1)
                        situacao = evento_relacionado_pai.group(2)
                        destinatario_pai = evento_relacionado_pai.group(3)
                        if not destinatario_pai and destinatario_filho:
                            continue
                        # if documento:# == evento_relacionado_filho.group(1):
                        if destinatario_pai == destinatario_filho:

                            print(f"Ev PAI: Ev:{mov_pai['evento']} - {mov_pai['data_texto']} - {mov_pai['ato']}") 
                            print(f"documento: {documento}")
                            print(f"situacão: {situacao}")
                            print(f"destinatário: {destinatario_pai}")
                            print('')

            if evento_relacionado_filho:
                if evento_relacionado_filho.group(3):
                    print("destinatário:", evento_relacionado_filho.group(3))
                if evento_relacionado_filho.group(1):
                    print("documento:", evento_relacionado_filho.group(1))
                if evento_relacionado_filho.group(2):
                    print("situação:", evento_relacionado_filho.group(2))
                if evento_relacionado_filho.group(4):
                    print("data leitura:", evento_relacionado_filho.group(4))


                else:
                    continue
                
            print('---------------------------------')
            print('')
            # if referencias:
            #     referencia = referencias.group(1)
            #     data_referencia = referencia.group(2)
                
                
                # print(referencia)
                # print(data_referencia)
                # print('---------------------------------')
                # print('')
        #     evento_relacionado = buscar_relacao_evento(mov['ato'])
        #     if not evento_relacionado:
        #         continue
        #     if evento_relacionado.group(4):
        #         data_ato_ref = evento_relacionado.group(4)
        #         for mov_ref in processo["movimentacoes"]:
        #             if mov_ref["data_texto"] == data_ato_ref:
        #                 eventos_pai = mov_ref
        #                 eventos_encadeados.append(eventos_pai)
        #                 eventos_encadeados.append(mov['ato'])
        #                 print(eventos_encadeados)
        #                 print('---------------------------------------------------')
        #                 break
        #     # else: 
        #     #     continue
                
        #     # if evento_relacionado:
        #     #     print("situação:", evento_relacionado.group(1))
        #     #     print("destinatário:", evento_relacionado.group(2))
        #     #     print("data leitura:", evento_relacionado.group(3))
        #     #     print("ato referência:", evento_relacionado.group(4))
        #     #     print("data ato:", evento_relacionado.group(5))
        #     #     print('---------------------------------------------------')

        # #     destinatario_por_adv = re.search(r'P\/\s+Advgs?\.', mov['ato'])
        # #     destinatario_pessoalmente = re.search(r'([A-Z])', mov['ato'])
        # # if destinatario_por_adv:
        # #     print(destinatario_por_adv.group())

        # # if destinatario_pessoalmente:
        # #     print(destinatario_pessoalmente.group())

        # print(mov['evento'])
        # print(mov['ato'])

    # if 'lido' in mov['ato']:
        # destinatario = 
        
        # print(f'DATA:{mov["data_texto"]}')
        # print(f'CAT:{mov["categoria"]}')
    # print(f'SIT:{mov["situacao_comunicacao"]})
    
    # print(f'REF:{mov["data_referencia_str"]})

Ev FILHO :62 - Intimação lido(a) (Para TV VINHOS LTDA) em 11/05/26 *Referente ao evento  Ato ordinatório praticado(28/04/26)
ref: Ato ordinatório praticado
data referência 28/04/26

destinatário: TV VINHOS LTDA
documento: Intimação
situação: lido(a)
data leitura: 11/05/26
---------------------------------

Ev FILHO :61 - Intimação lido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) em 08/05/26 *Referente ao evento  Ato ordinatório praticado(28/04/26)
ref: Ato ordinatório praticado
data referência 28/04/26

destinatário: PAYOUT PAGAMENTOS INTELIGENTES LTDA
documento: Intimação
situação: lido(a)
data leitura: 08/05/26
---------------------------------

Ev FILHO :30 - Citação lido(a) P/ PAYOUT PAGAMENTOS INTELIGENTES LTDA em 04/02/26
---------------------------------

Ev FILHO :28 - Intimação lido(a) (Para TV VINHOS LTDA) em 05/02/26 *Referente ao evento Intimação à disposição(21/01/26)
ref: Intimação à disposição
data referência 21/01/26

destinatário: TV VINHOS LTDA
documento: Intimação
situação: lido(a)
data leitura: 05/02/26
---------------------------------

Ev FILHO :26 - Citação lido(a) P/ TV VINHOS LTDA em 05/02/26
---------------------------------

Ev FILHO :25 - Intimação lido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) em 02/02/26 *Referente ao evento Intimação à disposição(21/01/26)
ref: Intimação à disposição
data referência 21/01/26

destinatário: PAYOUT PAGAMENTOS INTELIGENTES LTDA
documento: Intimação
situação: lido(a)
data leitura: 02/02/26
---------------------------------

Ev FILHO :6 - Intimação lido(a) (Para DANILO AUGUSTO E ARAUJO FRANCA) em 15/01/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(15/01/26)
ref: Audiência de Conciliação Designada (Telepresencial)
data referência 15/01/26

Ev PAI: Ev:6 - 15/01/26 - Intimação lido(a) (Para DANILO AUGUSTO E ARAUJO FRANCA) em 15/01/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(15/01/26)
documento: Intimação
situacão: lido(a)
destinatário: DANILO AUGUSTO E ARAUJO FRANCA

destinatário: DANILO AUGUSTO E ARAUJO FRANCA
documento: Intimação
situação: lido(a)
data leitura: 15/01/26
---------------------------------

Ev FILHO :223 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 19/03/26 *Referente ao evento Concedida a Medida Liminar(09/03/26)
ref: Concedida a Medida Liminar
data referência 09/03/26

destinatário: AMIL ASSISTENCIA MEDICA INTERNACIONAL S A
documento: Intimação
situação: lido(a)
data leitura: 19/03/26
---------------------------------

Ev FILHO :182 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 20/10/25 *Referente ao evento Extinta a execução ou o cumprimento da sentença(10/10/25)
ref: Extinta a execução ou o cumprimento da sentença
data referência 10/10/25

destinatário: AMIL ASSISTENCIA MEDICA INTERNACIONAL S A
documento: Intimação
situação: lido(a)
data leitura: 20/10/25
---------------------------------

Ev FILHO :41 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 16/05/25 *Referente ao evento Julgada procedente a ação(06/05/25)
ref: Julgada procedente a ação
data referência 06/05/25

destinatário: AMIL ASSISTENCIA MEDICA INTERNACIONAL S A
documento: Intimação
situação: lido(a)
data leitura: 16/05/25
---------------------------------

Ev FILHO :40 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 16/05/25 *Referente ao evento Julgada procedente a ação(06/05/25)
ref: Julgada procedente a ação
data referência 06/05/25

destinatário: RAQUEL LEMOS DE OLIVEIRA
documento: Intimação
situação: lido(a)
data leitura: 16/05/25
---------------------------------

Ev FILHO :27 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 06/03/25 *Referente ao evento Intimação à disposição(17/02/25)
ref: Intimação à disposição
data referência 17/02/25

destinatário: AMIL ASSISTENCIA MEDICA INTERNACIONAL S A
documento: Intimação
situação: lido(a)
data leitura: 06/03/25
---------------------------------

Ev FILHO :26 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 06/03/25 *Referente ao evento Intimação à disposição(17/02/25)
ref: Intimação à disposição
data referência 17/02/25

destinatário: RAQUEL LEMOS DE OLIVEIRA
documento: Intimação
situação: lido(a)
data leitura: 06/03/25
---------------------------------

Ev FILHO :25 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 17/02/25 *Referente ao evento Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA(06/02/25)
ref: Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA
data referência 06/02/25

destinatário: AMIL ASSISTENCIA MEDICA INTERNACIONAL S A
documento: Intimação
situação: lido(a)
data leitura: 17/02/25
---------------------------------

Ev FILHO :24 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 17/02/25 *Referente ao evento Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA(06/02/25)
ref: Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA
data referência 06/02/25

Ev PAI: Ev:6 - 06/02/25 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 06/02/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (06/02/25)
documento: Intimação
situacão: lido(a)
destinatário: RAQUEL LEMOS DE OLIVEIRA

destinatário: RAQUEL LEMOS DE OLIVEIRA
documento: Intimação
situação: lido(a)
data leitura: 17/02/25
---------------------------------

Ev FILHO :13 - Citação lido(a) P/ Representante: AMIL ASSISTENCIA MEDICA INTERNACIONAL S A em 07/02/25
Ev PAI: Ev:6 - 06/02/25 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 06/02/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (06/02/25)
documento: Intimação
situacão: lido(a)
destinatário: RAQUEL LEMOS DE OLIVEIRA

---------------------------------

Ev FILHO :6 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 06/02/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (06/02/25)
ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 06/02/25

Ev PAI: Ev:6 - 06/02/25 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 06/02/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (06/02/25)
documento: Intimação
situacão: lido(a)
destinatário: RAQUEL LEMOS DE OLIVEIRA

destinatário: RAQUEL LEMOS DE OLIVEIRA
documento: Intimação
situação: lido(a)
data leitura: 06/02/25
---------------------------------

Ev FILHO :118 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 31/10/24 *Referente ao evento Intimação à disposição(30/10/24)
ref: Intimação à disposição
data referência 30/10/24

destinatário: EDILEIDE DA SILVA LIMA
documento: Intimação
situação: lido(a)
data leitura: 31/10/24
---------------------------------

Ev FILHO :114 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 24/10/24 *Referente ao evento  Proferido despacho de mero expediente(16/10/24)
ref: Proferido despacho de mero expediente
data referência 16/10/24

destinatário: EDILEIDE DA SILVA LIMA
documento: Intimação
situação: lido(a)
data leitura: 24/10/24
---------------------------------

Ev FILHO :93 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 11/06/24 *Referente ao evento Intimação à disposição(05/06/24)
ref: Intimação à disposição
data referência 05/06/24

destinatário: EDILEIDE DA SILVA LIMA
documento: Intimação
situação: lido(a)
data leitura: 11/06/24
---------------------------------

Ev FILHO :30 - Intimação lido(a) (Para LARBELO MOVEIS) em 10/05/23 *Referente ao evento Intimação à disposição(17/04/23)
ref: Intimação à disposição
data referência 17/04/23

destinatário: LARBELO MOVEIS
documento: Intimação
situação: lido(a)
data leitura: 10/05/23
---------------------------------

Ev FILHO :19 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 22/03/23 *Referente ao evento Julgada procedente em parte a ação(22/03/23)
ref: Julgada procedente em parte a ação
data referência 22/03/23

destinatário: EDILEIDE DA SILVA LIMA
documento: Intimação
situação: lido(a)
data leitura: 22/03/23
---------------------------------

Ev FILHO :11 - Citação lido(a) P/ LARBELO MOVEIS em 08/03/23
---------------------------------

Ev FILHO :5 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 16/02/23 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (16/02/23)
ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 16/02/23

Ev PAI: Ev:5 - 16/02/23 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 16/02/23 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (16/02/23)
documento: Intimação
situacão: lido(a)
destinatário: EDILEIDE DA SILVA LIMA

destinatário: EDILEIDE DA SILVA LIMA
documento: Intimação
situação: lido(a)
data leitura: 16/02/23
---------------------------------

Ev FILHO :9 - Citação lido(a) P/ AZUL LINHAS AEREAS BRASILEIRAS S A em 13/03/26 OBS: Leitura realizada via Domicílio Eletrônico
Ev PAI: Ev:5 - 16/02/23 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 16/02/23 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (16/02/23)
documento: Intimação
situacão: lido(a)
destinatário: EDILEIDE DA SILVA LIMA

---------------------------------

Ev FILHO :5 - Intimação lido(a) (Para PAULO CESAR AGUIAR NETO) em 12/03/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(12/03/26)
ref: Audiência de Conciliação Designada (Telepresencial)
data referência 12/03/26

Ev PAI: Ev:5 - 12/03/26 - Intimação lido(a) (Para PAULO CESAR AGUIAR NETO) em 12/03/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(12/03/26)
documento: Intimação
situacão: lido(a)
destinatário: PAULO CESAR AGUIAR NETO

destinatário: PAULO CESAR AGUIAR NETO
documento: Intimação
situação: lido(a)
data leitura: 12/03/26
---------------------------------

Ev FILHO :112 - Intimação lido(a) (Para BRUNO HENRIQUE GOMES BEZERRA) em 07/05/26 *Referente ao evento Intimação à disposição(27/04/26)
ref: Intimação à disposição
data referência 27/04/26

destinatário: BRUNO HENRIQUE GOMES BEZERRA
documento: Intimação
situação: lido(a)
data leitura: 07/05/26
---------------------------------

Ev FILHO :103 - Intimação lido(a) (Para BRUNO HENRIQUE GOMES BEZERRA) em 19/03/26 *Referente ao evento Intimação expedido(a)(09/03/26)
ref: Intimação expedido(a)
data referência 09/03/26

destinatário: BRUNO HENRIQUE GOMES BEZERRA
documento: Intimação
situação: lido(a)
data leitura: 19/03/26
---------------------------------

Ev FILHO :72 - Intimação lido(a) (Para BRUNO HENRIQUE GOMES BEZERRA) em 17/11/25 *Referente ao evento Documento analisado(07/11/25)
ref: Documento analisado
data referência 07/11/25

destinatário: BRUNO HENRIQUE GOMES BEZERRA
documento: Intimação
situação: lido(a)
data leitura: 17/11/25
---------------------------------

Ev FILHO :38 - Intimação lido(a) (Para BRUNO HENRIQUE GOMES BEZERRA) em 09/05/25 *Referente ao evento Informações prestadas pela autoridade coatora expedido(a)(05/05/25)
ref: Informações prestadas pela autoridade coatora expedido(a)
data referência 05/05/25

destinatário: BRUNO HENRIQUE GOMES BEZERRA
documento: Intimação
situação: lido(a)
data leitura: 09/05/25
---------------------------------

Ev FILHO :36 - Intimação lido(a) (Para BANCO SANTANDER BRASIL S A) em 06/05/25 *Referente ao evento Informações prestadas pela autoridade coatora expedido(a)(05/05/25)
ref: Informações prestadas pela autoridade coatora expedido(a)
data referência 05/05/25

destinatário: BANCO SANTANDER BRASIL S A
documento: Intimação
situação: lido(a)
data leitura: 06/05/25
---------------------------------

Ev FILHO :20 - Citação lido(a) P/ BANCO SANTANDER BRASIL S A em 01/04/25
---------------------------------

Ev FILHO :22 - Citação lido(a) P/ BANCO MASTER S A em 29/04/26
---------------------------------

Ev FILHO :6 - Intimação lido(a) (Para JOSE HILTON MATOS DOS SANTOS) em 07/04/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(07/04/26)
ref: Audiência de Conciliação Designada (Telepresencial)
data referência 07/04/26

Ev PAI: Ev:6 - 07/04/26 - Intimação lido(a) (Para JOSE HILTON MATOS DOS SANTOS) em 07/04/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(07/04/26)
documento: Intimação
situacão: lido(a)
destinatário: JOSE HILTON MATOS DOS SANTOS

destinatário: JOSE HILTON MATOS DOS SANTOS
documento: Intimação
situação: lido(a)
data leitura: 07/04/26
---------------------------------

Ev FILHO :18 - Intimação lido(a) (Para LUIZ ANTONIO DE ANDRADE) em 14/05/25 *Referente ao evento Julgada procedente a ação(13/05/25)
ref: Julgada procedente a ação
data referência 13/05/25

destinatário: LUIZ ANTONIO DE ANDRADE
documento: Intimação
situação: lido(a)
data leitura: 14/05/25
---------------------------------

Ev FILHO :9 - Citação lido(a) P/ ASSOCIACAO DOS APOSENTADOS E PENSIONISTAS NACIONAL em 08/04/25
---------------------------------

Ev FILHO :5 - Intimação lido(a) (Para LUIZ ANTONIO DE ANDRADE) em 02/04/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (02/04/25)
ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 02/04/25

Ev PAI: Ev:5 - 02/04/25 - Intimação lido(a) (Para LUIZ ANTONIO DE ANDRADE) em 02/04/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (02/04/25)
documento: Intimação
situacão: lido(a)
destinatário: LUIZ ANTONIO DE ANDRADE

destinatário: LUIZ ANTONIO DE ANDRADE
documento: Intimação
situação: lido(a)
data leitura: 02/04/25
---------------------------------

Ev FILHO :246 - Intimação lido(a) (Para NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) em 04/05/26 *Referente ao evento  Proferido despacho de mero expediente(24/04/26)
ref: Proferido despacho de mero expediente
data referência 24/04/26

destinatário: NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO
documento: Intimação
situação: lido(a)
data leitura: 04/05/26
---------------------------------

Ev FILHO :228 - Intimação lido(a) (Para NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) em 13/04/26 *Referente ao evento  Proferido despacho de mero expediente(01/04/26)
ref: Proferido despacho de mero expediente
data referência 01/04/26

destinatário: NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO
documento: Intimação
situação: lido(a)
data leitura: 13/04/26
---------------------------------

Ev FILHO :27 - Intimação lido(a) (Para ERICK ERNANDES SANDES) em 08/05/25 *Referente ao evento Intimação à disposição(28/04/25)
ref: Intimação à disposição
data referência 28/04/25

destinatário: ERICK ERNANDES SANDES
documento: Intimação
situação: lido(a)
data leitura: 08/05/25
---------------------------------

Ev FILHO :17 - Intimação lido(a) (Para NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) em 25/04/25 *Referente ao evento  Ato ordinatório praticado(15/04/25)
ref: Ato ordinatório praticado
data referência 15/04/25

destinatário: NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO
documento: Intimação
situação: lido(a)
data leitura: 25/04/25
---------------------------------

Ev FILHO :16 - Intimação lido(a) (Para ERICK ERNANDES SANDES) em 25/04/25 *Referente ao evento  Ato ordinatório praticado(15/04/25)
ref: Ato ordinatório praticado
data referência 15/04/25

destinatário: ERICK ERNANDES SANDES
documento: Intimação
situação: lido(a)
data leitura: 25/04/25
---------------------------------

Ev FILHO :8 - Citação lido(a) P/ NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO em 14/04/25 OBS: Leitura realizada via Domicílio Eletrônico
---------------------------------

Ev FILHO :6 - Intimação lido(a) (Para ERICK ERNANDES SANDES) em 12/04/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (12/04/25)
ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 12/04/25

Ev PAI: Ev:6 - 12/04/25 - Intimação lido(a) (Para ERICK ERNANDES SANDES) em 12/04/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (12/04/25)
documento: Intimação
situacão: lido(a)
destinatário: ERICK ERNANDES SANDES

destinatário: ERICK ERNANDES SANDES
documento: Intimação
situação: lido(a)
data leitura: 12/04/25
---------------------------------

Ev FILHO :16 - Intimação lido(a) (Para GRUPO CASAS BAHIA S A) em 01/06/26 *Referente ao evento  Ato ordinatório praticado(20/05/26)
ref: Ato ordinatório praticado
data referência 20/05/26

destinatário: GRUPO CASAS BAHIA S A
documento: Intimação
situação: lido(a)
data leitura: 01/06/26
---------------------------------

Ev FILHO :12 - Citação lido(a) P/ GRUPO CASAS BAHIA S A em 20/05/26 OBS: Leitura realizada via Domicílio Eletrônico
---------------------------------

Ev FILHO :6 - Intimação lido(a) (Para ANDREA CARLA CARDOSO DE BRITO SILVA) em 20/05/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(20/05/26)
ref: Audiência de Conciliação Designada (Telepresencial)
data referência 20/05/26

Ev PAI: Ev:6 - 20/05/26 - Intimação lido(a) (Para ANDREA CARLA CARDOSO DE BRITO SILVA) em 20/05/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(20/05/26)
documento: Intimação
situacão: lido(a)
destinatário: ANDREA CARLA CARDOSO DE BRITO SILVA

destinatário: ANDREA CARLA CARDOSO DE BRITO SILVA
documento: Intimação
situação: lido(a)
data leitura: 20/05/26
---------------------------------

Ev FILHO :5 - Intimação lido(a) (Para MARCELO DANIEL MELO ALENCAR) em 25/05/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(25/05/26)
ref: Audiência de Conciliação Designada (Telepresencial)
data referência 25/05/26

Ev PAI: Ev:5 - 25/05/26 - Intimação lido(a) (Para MARCELO DANIEL MELO ALENCAR) em 25/05/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(25/05/26)
documento: Intimação
situacão: lido(a)
destinatário: MARCELO DANIEL MELO ALENCAR

destinatário: MARCELO DANIEL MELO ALENCAR
documento: Intimação
situação: lido(a)
data leitura: 25/05/26
---------------------------------

Ev FILHO :6 - Intimação lido(a) (Para ROGERIO FREITAS CAVALCANTI) em 02/06/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(02/06/26)
ref: Audiência de Conciliação Designada (Telepresencial)
data referência 02/06/26

Ev PAI: Ev:6 - 02/06/26 - Intimação lido(a) (Para ROGERIO FREITAS CAVALCANTI) em 02/06/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(02/06/26)
documento: Intimação
situacão: lido(a)
destinatário: ROGERIO FREITAS CAVALCANTI

destinatário: ROGERIO FREITAS CAVALCANTI
documento: Intimação
situação: lido(a)
data leitura: 02/06/26
---------------------------------

Ev FILHO :6 - Intimação lido(a) (Para HOMERO MARTINS DA SILVA) em 03/06/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(03/06/26)
ref: Audiência de Conciliação Designada (Telepresencial)
data referência 03/06/26

Ev PAI: Ev:6 - 03/06/26 - Intimação lido(a) (Para HOMERO MARTINS DA SILVA) em 03/06/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(03/06/26)
documento: Intimação
situacão: lido(a)
destinatário: HOMERO MARTINS DA SILVA

destinatário: HOMERO MARTINS DA SILVA
documento: Intimação
situação: lido(a)
data leitura: 03/06/26
---------------------------------

Ev FILHO :21 - Citação lido(a) P/ ASSOCIACAO DE APOSENTADOS MUTUALISTA PARA BENEFICIOS COLETIVOS - AMBEC em 23/05/25
Ev PAI: Ev:6 - 03/06/26 - Intimação lido(a) (Para HOMERO MARTINS DA SILVA) em 03/06/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(03/06/26)
documento: Intimação
situacão: lido(a)
destinatário: HOMERO MARTINS DA SILVA

---------------------------------

Ev FILHO :12 - Intimação lido(a) (Para FLORISVALDO CARVALHO LIMA) em 16/05/25 *Referente ao evento Intimação expedido(a)(15/05/25)
ref: Intimação expedido(a)
data referência 15/05/25

destinatário: FLORISVALDO CARVALHO LIMA
documento: Intimação
situação: lido(a)
data leitura: 16/05/25
---------------------------------

Ev FILHO :6 - Intimação lido(a) (Para FLORISVALDO CARVALHO LIMA) em 13/05/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (13/05/25)

In [ ]:
eventos_encadeados = []

for processo in processos:
    print( 'Processo: ', processo)
    for mov in processo['movimentacoes']:
        # if 'lido(a)' in mov['ato']:
        #     print(f"Ev FILHO :{mov['evento']} - {mov['ato']}")
        evento_relacionado_filho = buscar_relacao_evento(mov['ato'])

        if evento_relacionado_filho:
            data_referencia = referencia(mov['ato']).group(2)
            destinatario_filho = buscar_relacao_evento(mov['ato']).group(3)
            # meio_filho = destinatario(mov['ato'])
            
            # if meio_filho:
            #     print(meio_filho['tipo'])

            if not destinatario_filho:
                continue
        if data_referencia:
            for mov_ref in processo['movimentacoes']:
                if mov_ref['data_texto'] == data_referencia:
                    evento_relacionado_pai = buscar_relacao_evento(mov_ref['ato'])
                    meio_pai = destinatario(mov_ref['ato'])
                    mov_pai = mov_ref
                        # dados_evento_pai = buscar_relacao_evento(mov_pai)
                        # if dados_evento_pai:
                        #     print(dados_evento_pai.group(2))
            if mov_pai:
                evento_relacionado_pai = buscar_relacao_evento(mov_ref['ato'])
                if evento_relacionado_pai:
                    documento = evento_relacionado_pai.group(1)
                    situacao = evento_relacionado_pai.group(2)
                    destinatario_pai = evento_relacionado_pai.group(3)
                    
                    if not destinatario_pai and destinatario_filho:
                        continue
                        # if documento:# == evento_relacionado_filho.group(1):
                    if destinatario_pai == destinatario_filho:

                        print(f"Ev PAI: Ev:{mov_pai['evento']} - {mov_pai['data_texto']} - {mov_pai['ato']}") 
                        print(f"documento: {documento}")
                        print(f"situacão: {situacao}")
                        print(f"destinatário: {destinatario_pai}")
                        if meio_pai:
                            print(f"meio: {meio_pai['tipo']}")
                        print('')

        if evento_relacionado_filho:
            print(f"Ev FILHO: Ev:{mov['evento']} - {mov['data_texto']} - {mov['ato']}") 
            if evento_relacionado_filho.group(3):
                print("destinatário:", evento_relacionado_filho.group(3))
            if evento_relacionado_filho.group(1):
                print("documento:", evento_relacionado_filho.group(1))
            if evento_relacionado_filho.group(2):
                print("situação:", evento_relacionado_filho.group(2))
            if evento_relacionado_filho.group(4):
                print("data leitura:", evento_relacionado_filho.group(4))


            else:
                continue
                
        print('---------------------------------')
        print('')

Processo:  {'partes': [{'nome': 'DANILO AUGUSTO E ARAUJO FRANCA', 'nome_normalizado': 'danilo augusto e araujo franca', 'cpf/cnpj': '891.424.205-63', 'tipo': 'EXEQUENTE', 'papel': 'PROMOVENTE', 'recebe_intimacao_email': False, 'domicilio_cnj': False, 'tem_advogado': True, 'email': 'FRANCA_DANILO@HOTMAIL.COM', 'tel': '71996123344', 'logradouro': 'ENDEREÇO RUA NELSON RODRIGUES DO NASCIMENTO', 'numero': '45', 'complemento': 'PANORAMA', 'bairro': '(CONTATO:', 'cidade': 'PAULO AFONSO', 'uf': 'BA', 'cep': '48605041'}, {'nome': 'PAYOUT PAGAMENTOS INTELIGENTES LTDA(Rev. Arg)', 'nome_normalizado': 'payout pagamentos inteligentes ltda(rev. arg)', 'cpf/cnpj': '57.225.538/0001-11', 'tipo': 'EXECUTADO', 'papel': 'PROMOVIDO', 'recebe_intimacao_email': False, 'domicilio_cnj': True, 'tem_advogado': True, 'email': None, 'tel': None, 'logradouro': 'ENDEREÇO ALAMEDA RIO NEGRO', 'numero': '503', 'complemento': 'ALPHAVILLE CENTRO INDUSTRIAL E EMPRESARIAL ALPHAVILLE', 'bairro': None, 'cidade': 'BARUERI', 'uf': 'SP', 'cep': '06454000'}, {'nome': 'TV VINHOS LTDA(Rev. Arg)', 'nome_normalizado': 'tv vinhos ltda(rev. arg)', 'cpf/cnpj': '63.965.406/0001-29', 'tipo': 'EXECUTADO', 'papel': 'PROMOVIDO', 'recebe_intimacao_email': False, 'domicilio_cnj': False, 'tem_advogado': True, 'email': None, 'tel': None, 'logradouro': 'ENDEREÇO AVENIDA PORTUGAL', 'numero': '1148', 'complemento': 'SALA 2501', 'bairro': 'SETOR MARISTA', 'cidade': 'GOIANIA', 'uf': 'GO', 'cep': '74150030'}], 'movimentacoes': [{'evento': '82', 'ato': 'Intimação expedido(a) (P/ Advgs. de PAYOUT PAGAMENTOS INTELIGENTES LTDA) Sem prazo Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)', 'ato_normalizado': 'intimação expedido(a) (p/ advgs. de payout pagamentos inteligentes ltda) sem prazo aguardando disponibilização no diário da justiça eletrônico nacional - djen (cnj)', 'data_texto': '02/06/26', 'data_obj': '2026-06-02', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'ANTONIO JUVENCIO DA SILVA NETO', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': 'domicilio_cnj', 'situacao_comunicacao': 'expedida', 'destinatario': 'payout pagamentos inteligentes ltda'}, {'evento': '81', 'ato': 'Intimação expedido(a) (P/ Advgs. de DANILO AUGUSTO E ARAUJO FRANCA) Sem prazo Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)', 'ato_normalizado': 'intimação expedido(a) (p/ advgs. de danilo augusto e araujo franca) sem prazo aguardando disponibilização no diário da justiça eletrônico nacional - djen (cnj)', 'data_texto': '02/06/26', 'data_obj': '2026-06-02', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'ANTONIO JUVENCIO DA SILVA NETO', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': 'domicilio_cnj', 'situacao_comunicacao': 'expedida', 'destinatario': 'danilo augusto e araujo franca'}, {'evento': '72', 'ato': 'Intimação expedido(a) (P/ Advgs. de DANILO AUGUSTO E ARAUJO FRANCA) Prazo: 5 dias; Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)', 'ato_normalizado': 'intimação expedido(a) (p/ advgs. de danilo augusto e araujo franca) prazo: 5 dias; aguardando disponibilização no diário da justiça eletrônico nacional - djen (cnj)', 'data_texto': '01/06/26', 'data_obj': '2026-06-01', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'MARTINHO FERRAZ DA NOBREGA JUNIOR', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': 'domicilio_cnj', 'situacao_comunicacao': 'expedida', 'destinatario': 'danilo augusto e araujo franca'}, {'evento': '62', 'ato': 'Intimação lido(a) (Para TV VINHOS LTDA) em 11/05/26 *Referente ao evento  Ato ordinatório praticado(28/04/26)', 'ato_normalizado': 'intimação lido(a) (para tv vinhos ltda) em 11/05/26 *referente ao evento  ato ordinatório praticado(28/04/26)', 'data_texto': '17/05/26', 'data_obj': '2026-05-17', 'data_leitura_str': '2026-05-11', 'data_referencia_str': '28/04/26', 'autor': 'ECT', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'lida', 'destinatario': 'tv vinhos ltda'}, {'evento': '61', 'ato': 'Intimação lido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) em 08/05/26 *Referente ao evento  Ato ordinatório praticado(28/04/26)', 'ato_normalizado': 'intimação lido(a) (para payout pagamentos inteligentes ltda) em 08/05/26 *referente ao evento  ato ordinatório praticado(28/04/26)', 'data_texto': '09/05/26', 'data_obj': '2026-05-09', 'data_leitura_str': '2026-05-08', 'data_referencia_str': '28/04/26', 'autor': 'SISTEMA CNJ', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'lida', 'destinatario': 'payout pagamentos inteligentes ltda'}, {'evento': '60', 'ato': 'Intimação expedido(a) Para TV VINHOS LTDA *Referente ao evento  Ato ordinatório praticado(28/04/26)', 'ato_normalizado': 'intimação expedido(a) para tv vinhos ltda *referente ao evento  ato ordinatório praticado(28/04/26)', 'data_texto': '28/04/26', 'data_obj': '2026-04-28', 'data_leitura_str': None, 'data_referencia_str': '28/04/26', 'autor': 'MARCELO PEREIRA DA SILVAA', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'expedida', 'destinatario': 'tv vinhos ltda'}, {'evento': '58', 'ato': 'Intimação expedido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) Prazo: 15 dias;', 'ato_normalizado': 'intimação expedido(a) (para payout pagamentos inteligentes ltda) prazo: 15 dias;', 'data_texto': '28/04/26', 'data_obj': '2026-04-28', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'ANTONIO JUVENCIO DA SILVA NETO', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'expedida', 'destinatario': 'payout pagamentos inteligentes ltda'}, {'evento': '49', 'ato': 'Intimação expedido(a) (P/ Advgs. de DANILO AUGUSTO E ARAUJO FRANCA) Sem prazo Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)', 'ato_normalizado': 'intimação expedido(a) (p/ advgs. de danilo augusto e araujo franca) sem prazo aguardando disponibilização no diário da justiça eletrônico nacional - djen (cnj)', 'data_texto': '17/04/26', 'data_obj': '2026-04-17', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'IVAN GUEDES DA SILVA', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': 'domicilio_cnj', 'situacao_comunicacao': 'expedida', 'destinatario': 'danilo augusto e araujo franca'}, {'evento': '37', 'ato': 'Intimação expedido(a) (P/ Advgs. de DANILO AUGUSTO E ARAUJO FRANCA) Prazo: 10 dias; Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)', 'ato_normalizado': 'intimação expedido(a) (p/ advgs. de danilo augusto e araujo franca) prazo: 10 dias; aguardando disponibilização no diário da justiça eletrônico nacional - djen (cnj)', 'data_texto': '20/02/26', 'data_obj': '2026-02-20', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'VITORIA YASMIN PEREIRA DE JESUS', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': 'domicilio_cnj', 'situacao_comunicacao': 'expedida', 'destinatario': 'danilo augusto e araujo franca'}, {'evento': '33', 'ato': 'Audiência de Conciliação Realizada (Telepresencial) Conduzida por Juiz MARTINHO FERRAZ DA NOBREGA JUNIOR Realizada em/para 19/02/2026 16:46, PAULO AFONSO', 'ato_normalizado': 'audiência de conciliação realizada (telepresencial) conduzida por juiz martinho ferraz da nobrega junior realizada em/para 19/02/2026 16:46, paulo afonso', 'data_texto': '19/02/26', 'data_obj': '2026-02-19', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'WALKER LOPES RODRIGUES', 'observacao': '', 'categoria': 'audiencia', 'meio_comunicacao': None, 'situacao_comunicacao': 'realizada', 'destinatario': '19/02/2026 16:46, paulo afonso'}, {'evento': '30', 'ato': 'Citação lido(a) P/ PAYOUT PAGAMENTOS INTELIGENTES LTDA em 04/02/26', 'ato_normalizado': 'citação lido(a) p/ payout pagamentos inteligentes ltda em 04/02/26', 'data_texto': '16/02/26', 'data_obj': '2026-02-16', 'data_leitura_str': '2026-02-04', 'data_referencia_str': None, 'autor': 'ECT', 'observacao': '', 'categoria': 'citacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'lida', 'destinatario': 'payout pagamentos inteligentes ltda em 04/02/26'}, {'evento': '28', 'ato': 'Intimação lido(a) (Para TV VINHOS LTDA) em 05/02/26 *Referente ao evento Intimação à disposição(21/01/26)', 'ato_normalizado': 'intimação lido(a) (para tv vinhos ltda) em 05/02/26 *referente ao evento intimação à disposição(21/01/26)', 'data_texto': '14/02/26', 'data_obj': '2026-02-14', 'data_leitura_str': '2026-02-05', 'data_referencia_str': '21/01/26', 'autor': 'ECT', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'lida', 'destinatario': 'tv vinhos ltda'}, {'evento': '26', 'ato': 'Citação lido(a) P/ TV VINHOS LTDA em 05/02/26', 'ato_normalizado': 'citação lido(a) p/ tv vinhos ltda em 05/02/26', 'data_texto': '14/02/26', 'data_obj': '2026-02-14', 'data_leitura_str': '2026-02-05', 'data_referencia_str': None, 'autor': 'ECT', 'observacao': '', 'categoria': 'citacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'lida', 'destinatario': 'tv vinhos ltda em 05/02/26'}, {'evento': '25', 'ato': 'Intimação lido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) em 02/02/26 *Referente ao evento Intimação à disposição(21/01/26)', 'ato_normalizado': 'intimação lido(a) (para payout pagamentos inteligentes ltda) em 02/02/26 *referente ao evento intimação à disposição(21/01/26)', 'data_texto': '03/02/26', 'data_obj': '2026-02-03', 'data_leitura_str': '2026-02-02', 'data_referencia_str': '21/01/26', 'autor': 'SISTEMA CNJ', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'lida', 'destinatario': 'payout pagamentos inteligentes ltda'}, {'evento': '24', 'ato': 'Citação expedido(a) Para TV VINHOS LTDA', 'ato_normalizado': 'citação expedido(a) para tv vinhos ltda', 'data_texto': '26/01/26', 'data_obj': '2026-01-26', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'VALQUIRIO DE SOUZA LIMA', 'observacao': '', 'categoria': 'citacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'expedida', 'destinatario': 'tv vinhos ltda'}, {'evento': '23', 'ato': 'Citação expedido(a) Para PAYOUT PAGAMENTOS INTELIGENTES LTDA', 'ato_normalizado': 'citação expedido(a) para payout pagamentos inteligentes ltda', 'data_texto': '26/01/26', 'data_obj': '2026-01-26', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'VALQUIRIO DE SOUZA LIMA', 'observacao': '', 'categoria': 'citacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'expedida', 'destinatario': 'payout pagamentos inteligentes ltda'}, {'evento': '17', 'ato': 'Intimação expedido(a) Para TV VINHOS LTDA *Referente ao evento Intimação à disposição(21/01/26)', 'ato_normalizado': 'intimação expedido(a) para tv vinhos ltda *referente ao evento intimação à disposição(21/01/26)', 'data_texto': '23/01/26', 'data_obj': '2026-01-23', 'data_leitura_str': None, 'data_referencia_str': '21/01/26', 'autor': 'VALQUIRIO DE SOUZA LIMA', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'expedida', 'destinatario': 'tv vinhos ltda'}, {'evento': '14', 'ato': 'Intimação expedido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) Sem prazo', 'ato_normalizado': 'intimação expedido(a) (para payout pagamentos inteligentes ltda) sem prazo', 'data_texto': '21/01/26', 'data_obj': '2026-01-21', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'VITORIA YASMIN PEREIRA DE JESUS', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'expedida', 'destinatario': 'payout pagamentos inteligentes ltda'}, {'evento': '13', 'ato': 'Intimação expedido(a) (P/ Advgs. de DANILO AUGUSTO E ARAUJO FRANCA) Sem prazo Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)', 'ato_normalizado': 'intimação expedido(a) (p/ advgs. de danilo augusto e araujo franca) sem prazo aguardando disponibilização no diário da justiça eletrônico nacional - djen (cnj)', 'data_texto': '21/01/26', 'data_obj': '2026-01-21', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'VITORIA YASMIN PEREIRA DE JESUS', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': 'domicilio_cnj', 'situacao_comunicacao': 'expedida', 'destinatario': 'danilo augusto e araujo franca'}, {'evento': '9', 'ato': 'Citação expedido(a) Para TV VINHOS LTDA', 'ato_normalizado': 'citação expedido(a) para tv vinhos ltda', 'data_texto': '15/01/26', 'data_obj': '2026-01-15', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'SELMA PEREIRA DIAS', 'observacao': '', 'categoria': 'citacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'expedida', 'destinatario': 'tv vinhos ltda'}, {'evento': '7', 'ato': 'Citação expedido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) Sem prazo', 'ato_normalizado': 'citação expedido(a) (para payout pagamentos inteligentes ltda) sem prazo', 'data_texto': '15/01/26', 'data_obj': '2026-01-15', 'data_leitura_str': None, 'data_referencia_str': None, 'autor': 'SISTEMA CNJ', 'observacao': '', 'categoria': 'citacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'expedida', 'destinatario': 'payout pagamentos inteligentes ltda'}, {'evento': '6', 'ato': 'Intimação lido(a) (Para DANILO AUGUSTO E ARAUJO FRANCA) em 15/01/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(15/01/26)', 'ato_normalizado': 'intimação lido(a) (para danilo augusto e araujo franca) em 15/01/26 *referente ao evento audiência de conciliação designada (telepresencial)(15/01/26)', 'data_texto': '15/01/26', 'data_obj': '2026-01-15', 'data_leitura_str': '2026-01-15', 'data_referencia_str': '15/01/26', 'autor': 'SISTEMA CNJ', 'observacao': '', 'categoria': 'intimacao', 'meio_comunicacao': None, 'situacao_comunicacao': 'lida', 'destinatario': 'danilo augusto e araujo franca'}], 'links': {'movimentar': 'https://projudi.tjba.jus.br/projudi/movimentacao/MovimentarProcessoAvancado?numeroProcesso=41020260144739', 'negociacao': 'https://projudi.tjba.jus.br/projudi/acoes/RemessaNegociacao?numeroProcesso=41020260144739', 'dados_processo': 'https://projudi.tjba.jus.br/projudi/listagens/DadosProcesso?numeroProcesso=41020260144739', 'peticionar': 'https://projudi.tjba.jus.br/projudi/movimentacao/Peticionar?numeroProcesso=41020260144739&ehPeticionar=s', 'alterar_partes': 'https://projudi.tjba.jus.br/projudi/acoes/AlterarPartesProcesso?numeroProcesso=41020260144739'}}
---------------------------------

---------------------------------

---------------------------------

ref: Ato ordinatório praticado
data referência 28/04/26

Ev FILHO: Ev:62 - 17/05/26 - Intimação lido(a) (Para TV VINHOS LTDA) em 11/05/26 *Referente ao evento  Ato ordinatório praticado(28/04/26)
destinatário: TV VINHOS LTDA
documento: Intimação
situação: lido(a)
data leitura: 11/05/26
---------------------------------

ref: Ato ordinatório praticado
data referência 28/04/26

Ev FILHO: Ev:61 - 09/05/26 - Intimação lido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) em 08/05/26 *Referente ao evento  Ato ordinatório praticado(28/04/26)
destinatário: PAYOUT PAGAMENTOS INTELIGENTES LTDA
documento: Intimação
situação: lido(a)
data leitura: 08/05/26
---------------------------------

---------------------------------

---------------------------------

---------------------------------

---------------------------------

---------------------------------

---------------------------------

ref: Intimação à disposição
data referência 21/01/26

Ev FILHO: Ev:28 - 14/02/26 - Intimação lido(a) (Para TV VINHOS LTDA) em 05/02/26 *Referente ao evento Intimação à disposição(21/01/26)
destinatário: TV VINHOS LTDA
documento: Intimação
situação: lido(a)
data leitura: 05/02/26
---------------------------------

---------------------------------

ref: Intimação à disposição
data referência 21/01/26

Ev FILHO: Ev:25 - 03/02/26 - Intimação lido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) em 02/02/26 *Referente ao evento Intimação à disposição(21/01/26)
destinatário: PAYOUT PAGAMENTOS INTELIGENTES LTDA
documento: Intimação
situação: lido(a)
data leitura: 02/02/26
---------------------------------

---------------------------------

---------------------------------

---------------------------------

---------------------------------

---------------------------------

---------------------------------

---------------------------------

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 15/01/26

Ev PAI: Ev:6 - 15/01/26 - Intimação lido(a) (Para DANILO AUGUSTO E ARAUJO FRANCA) em 15/01/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(15/01/26)
documento: Intimação
situacão: lido(a)
destinatário: DANILO AUGUSTO E ARAUJO FRANCA
meio: parte

Ev FILHO: Ev:6 - 15/01/26 - Intimação lido(a) (Para DANILO AUGUSTO E ARAUJO FRANCA) em 15/01/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(15/01/26)
destinatário: DANILO AUGUSTO E ARAUJO FRANCA
documento: Intimação
situação: lido(a)
data leitura: 15/01/26
---------------------------------


In [ ]:
eventos_encadeados = []

for processo in processos:

    for mov in processo["movimentacoes"]:

        # if "lido(a)" not in mov["ato"]:
        #     continue

        evento_relacionado = buscar_relacao_evento(mov["ato"])

        if not evento_relacionado:
            continue

        destinatario = evento_relacionado.group(2)
        data_leitura = evento_relacionado.group(3)
        ato_referencia = evento_relacionado.group(4)
        # data_ato_ref = evento_relacionado.group(5)

        for mov_ref in processo["movimentacoes"]:

            # if (
            #     mov_ref["data_texto"] == data_ato_ref
            #     and ato_referencia.lower() in mov_ref["ato"].lower()
            # ):

            eventos_encadeados.append({
                    "evento_filho": mov["evento"],
                    "ato_filho": mov["ato"],

                    "evento_pai": mov_ref["evento"],
                    "ato_pai": mov_ref["ato"],

                    "destinatario": destinatario,
                    "data_leitura": data_leitura,
                    # "data_referencia": data_ato_ref,
            })
                
            break
# print(eventos_encadeados['evento_pai'])
# print(eventos_encadeados['ato_filho'])

In [ ]:
# for rel in eventos_encadeados:
#     print(
#         f'Evento {rel["evento_filho"]} '
#         f'-> Evento {rel["evento_pai"]}'
#     )

In [ ]:
decisao_sentenca = (
    'Inexistência de bens penhoráveis','Procedência em Parte', 'Procedência', 'Improcedência',
    'Extinção da execução ou do cumprimento da sentença', 'Ausência do autor à audiência', 'Homologada a Transação',
    'Inadmissibilidade do procedimento sumaríssimo', 'Liminar', 'Acolhimento e Embargos de Declaração',
)
for e in eventos_encadeados:
    if e in decisao_sentenca:
        print(f"[FILHO] {e['evento_filho']} | {e['ato_filho']}")
        print(f"[PAI  ] {e['evento_pai']} | {e['ato_pai']}")
        print(f"Destinatário: {e['destinatario']}  | Leitura: {e['data_leitura']}  | Ref: {e['data_referencia']}")
        print("-" * 80)

In [ ]:
padroes_sentenca = (
    'procedente',
    'procedência',
    'improcedente',
    'liminar',
    'extinta a execução',
    'extinto o processo',
    'homologada a transação',
)


for e in eventos_encadeados:
    evento = e['evento_filho'].lower()

    if any(p.lower() in evento for p in padroes_sentenca):
        print(f"[FILHO] {e['evento_filho']} | {e['ato_filho']}")
        print(f"[PAI  ] {e['evento_pai']} | {e['ato_pai']}")
        print(f"Destinatário: {e['destinatario']}")
        print("-" * 80)

In [ ]:
eventos_encadeados = []

for processo in processos:

    for mov in processo["movimentacoes"]:

        if "lido(a)" not in mov["ato"]:
            continue

        evento_relacionado = buscar_relacao_evento(mov["ato"])

        if not evento_relacionado:
            continue

        destinatario = evento_relacionado.group(2)
        data_leitura = evento_relacionado.group(3)
        ato_referencia = evento_relacionado.group(4)
        data_ato_ref = evento_relacionado.group(5)

        for mov_ref in processo["movimentacoes"]:

            if (
                mov_ref["data_texto"] == data_ato_ref
                and ato_referencia.lower() in mov_ref["ato"].lower()
            ):

                eventos_encadeados.append({
                    "evento_filho": mov["evento"],
                    "ato_filho": mov["ato"],

                    "evento_pai": mov_ref["evento"],
                    "ato_pai": mov_ref["ato"],

                    "destinatario": destinatario,
                    "data_leitura": data_leitura,
                    "data_referencia": data_ato_ref,
                })
                
                break
# print(eventos_encadeados['evento_pai'])
# print(eventos_encadeados['ato_filho'])

IndexError: no such group

In [ ]:
for processo in processos:

    for mov_lido in processo['movimentacoes']:

        # 1. Precisa ser uma leitura
        rel_lido = buscar_relacao_evento(mov_lido['ato'])

        if not rel_lido:
            continue

        if rel_lido.group(2) != 'lido(a)':
            continue

        # 2. Precisa ter referência ao evento principal
        ref = referencia(mov_lido['ato'])

        if not ref:
            continue

        nome_evento = ref.group(1)
        data_referencia = ref.group(2)

        destinatario = rel_lido.group(3)

        # 3. Encontrar o evento principal
        evento_principal = next(
            (
                m for m in processo['movimentacoes']
                if m['data_texto'] == data_referencia
            ),
            None
        )

        if not evento_principal:
            continue

        # 4. Encontrar a expedição correspondente
        evento_expedido = None

        for mov_exp in processo['movimentacoes']:

            rel_exp = buscar_relacao_evento(mov_exp['ato'])

            if not rel_exp:
                continue

            if rel_exp.group(2) != 'expedido(a)':
                continue

            if rel_exp.group(3) == destinatario:
                evento_expedido = mov_exp
                break

        # 5. Montar o encadeamento
        eventos_encadeados.append({
            'evento_principal': evento_principal,
            'evento_expedido': evento_expedido,
            'evento_lido': mov_lido,

            'nome_evento': nome_evento,
            'destinatario': destinatario,
            'data_referencia': data_referencia,
            'data_leitura': rel_lido.group(4),
        })

ref: Ato ordinatório praticado
data referência 28/04/26

ref: Ato ordinatório praticado
data referência 28/04/26

ref: Intimação à disposição
data referência 21/01/26

ref: Intimação à disposição
data referência 21/01/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 15/01/26

ref: Concedida a Medida Liminar
data referência 09/03/26

ref: Extinta a execução ou o cumprimento da sentença
data referência 10/10/25

ref: Julgada procedente a ação
data referência 06/05/25

ref: Julgada procedente a ação
data referência 06/05/25

ref: Intimação à disposição
data referência 17/02/25

ref: Intimação à disposição
data referência 17/02/25

ref: Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA
data referência 06/02/25

ref: Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA
data referência 06/02/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 06/02/25

ref: Intimação à disposição
data referência 30/10/24

ref: Proferido despacho de mero expediente
data referência 16/10/24

ref: Intimação à disposição
data referência 05/06/24

ref: Intimação à disposição
data referência 17/04/23

ref: Julgada procedente em parte a ação
data referência 22/03/23

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 16/02/23

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 12/03/26

ref: Intimação à disposição
data referência 27/04/26

ref: Intimação expedido(a)
data referência 09/03/26

ref: Documento analisado
data referência 07/11/25

ref: Informações prestadas pela autoridade coatora expedido(a)
data referência 05/05/25

ref: Informações prestadas pela autoridade coatora expedido(a)
data referência 05/05/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 07/04/26

ref: Julgada procedente a ação
data referência 13/05/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 02/04/25

ref: Proferido despacho de mero expediente
data referência 24/04/26

ref: Proferido despacho de mero expediente
data referência 01/04/26

ref: Intimação à disposição
data referência 28/04/25

ref: Ato ordinatório praticado
data referência 15/04/25

ref: Ato ordinatório praticado
data referência 15/04/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 12/04/25

ref: Ato ordinatório praticado
data referência 20/05/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 20/05/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 25/05/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 02/06/26

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 03/06/26

ref: Intimação expedido(a)
data referência 15/05/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 13/05/25

ref: Intimação para Videoconferência à disposição
data referência 07/07/25

ref: Intimação à disposição
data referência 07/07/25

ref: Extinto o processo por Perempção, litispendência ou coisa julgada
data referência 13/05/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 13/05/25

ref: Proferido despacho de mero expediente
data referência 04/09/25

ref: Julgada procedente em parte a ação
data referência 11/07/25

ref: Julgada procedente em parte a ação
data referência 11/07/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 06/06/25

ref: Intimação à disposição
data referência 12/05/25

ref: Documento analisado
data referência 03/12/24

ref: Intimação à disposição
data referência 25/11/24

ref: Intimação à disposição
data referência 01/10/24

ref: Proferido despacho de mero expediente
data referência 10/07/24

ref: Documento analisado
data referência 24/04/24

ref: Julgada procedente em parte a ação
data referência 26/03/24

ref: Julgada procedente em parte a ação
data referência 26/03/24

ref: Intimação para Videoconferência à disposição
data referência 21/11/23

ref: Proferido despacho de mero expediente
data referência 21/11/23

ref: Intimação para Videoconferência à disposição
data referência 21/11/23

ref: Proferido despacho de mero expediente
data referência 21/11/23

ref: Intimação para Videoconferência à disposição
data referência 06/11/23

ref: Intimação para Videoconferência à disposição
data referência 06/11/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 03/10/23

ref: Intimação para Videoconferência à disposição
data referência 24/08/23

ref: Intimação para Videoconferência à disposição
data referência 24/08/23

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 18/07/23

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 13/06/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 14/07/25

ref: Intimação à disposição
data referência 12/09/25

ref: Intimação à disposição
data referência 01/09/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 18/07/25

ref: Intimação à disposição
data referência 14/01/25

ref: Intimação à disposição
data referência 14/01/25

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 28/08/24

ref: Intimação à disposição
data referência 10/06/24

ref: Julgada procedente em parte a ação
data referência 25/04/24

ref: Julgada procedente em parte a ação
data referência 25/04/24

ref: Intimação para Videoconferência à disposição
data referência 06/03/24

ref: Intimação para Videoconferência à disposição
data referência 06/03/24

ref: Proferido despacho de mero expediente
data referência 06/03/24

ref: Intimação para Videoconferência à disposição
data referência 06/03/24

ref: Proferido despacho de mero expediente
data referência 06/03/24

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 01/11/23

ref: Proferido despacho de mero expediente
data referência 06/02/26

ref: Intimação à disposição
data referência 14/10/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 14/10/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 23/10/25

ref: Intimação à disposição
data referência 24/10/25

ref: Audiência de Conciliação Designada (Telepresencial)
data referência 24/10/25

ref: Intimação à disposição
data referência 01/04/25

ref: Proferido despacho de mero expediente
data referência 26/02/25

ref: Intimação à disposição
data referência 09/12/24

ref: Intimação à disposição
data referência 09/12/24

ref: Audiência  de Conciliação Designada (Telepresencial)
data referência 03/11/24

ref: Intimação à disposição
data referência 17/12/18

ref: Intimação à disposição
data referência 17/12/18

ref: Audiência  de Conciliação Designada
data referência 31/10/18

In [ ]:
for e in eventos_encadeados:

    print(
        f"PRINCIPAL: {e['evento_principal']['evento']} - "
        f"{e['evento_principal']['ato']}"
    )

    if e['evento_expedido']:
        print(
            f"EXPEDIDO : {e['evento_expedido']['evento']} - "
            f"{e['evento_expedido']['ato']}"
        )

    print(
        f"LIDO     : {e['evento_lido']['evento']} - "
        f"{e['evento_lido']['ato']}"
    )

    print('-' * 80)

PRINCIPAL: 60 - Intimação expedido(a) Para TV VINHOS LTDA *Referente ao evento  Ato ordinatório praticado(28/04/26)
LIDO     : 62 - Intimação lido(a) (Para TV VINHOS LTDA) em 11/05/26 *Referente ao evento  Ato ordinatório praticado(28/04/26)
--------------------------------------------------------------------------------
PRINCIPAL: 60 - Intimação expedido(a) Para TV VINHOS LTDA *Referente ao evento  Ato ordinatório praticado(28/04/26)
LIDO     : 61 - Intimação lido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) em 08/05/26 *Referente ao evento  Ato ordinatório praticado(28/04/26)
--------------------------------------------------------------------------------
PRINCIPAL: 14 - Intimação expedido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) Sem prazo
LIDO     : 28 - Intimação lido(a) (Para TV VINHOS LTDA) em 05/02/26 *Referente ao evento Intimação à disposição(21/01/26)
--------------------------------------------------------------------------------
PRINCIPAL: 14 - Intimação expedido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) Sem prazo
LIDO     : 25 - Intimação lido(a) (Para PAYOUT PAGAMENTOS INTELIGENTES LTDA) em 02/02/26 *Referente ao evento Intimação à disposição(21/01/26)
--------------------------------------------------------------------------------
PRINCIPAL: 9 - Citação expedido(a) Para TV VINHOS LTDA
LIDO     : 6 - Intimação lido(a) (Para DANILO AUGUSTO E ARAUJO FRANCA) em 15/01/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(15/01/26)
--------------------------------------------------------------------------------
PRINCIPAL: 219 - Intimação expedido(a) (P/ Advgs. de AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) Prazo: 5 dias; Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)
LIDO     : 223 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 19/03/26 *Referente ao evento Concedida a Medida Liminar(09/03/26)
--------------------------------------------------------------------------------
PRINCIPAL: 174 - Intimação expedido(a) (P/ Advgs. de AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) Prazo: 5 dias; Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)
LIDO     : 182 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 20/10/25 *Referente ao evento Extinta a execução ou o cumprimento da sentença(10/10/25)
--------------------------------------------------------------------------------
PRINCIPAL: 38 - Intimação expedido(a) (P/ Advgs. de AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) Prazo: 10 dias;
LIDO     : 41 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 16/05/25 *Referente ao evento Julgada procedente a ação(06/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 38 - Intimação expedido(a) (P/ Advgs. de AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) Prazo: 10 dias;
LIDO     : 40 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 16/05/25 *Referente ao evento Julgada procedente a ação(06/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 23 - Intimação expedido(a) (P/ Advgs. de AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) Prazo: 10 dias;
LIDO     : 27 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 06/03/25 *Referente ao evento Intimação à disposição(17/02/25)
--------------------------------------------------------------------------------
PRINCIPAL: 23 - Intimação expedido(a) (P/ Advgs. de AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) Prazo: 10 dias;
LIDO     : 26 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 06/03/25 *Referente ao evento Intimação à disposição(17/02/25)
--------------------------------------------------------------------------------
PRINCIPAL: 7 - Citação expedido(a) Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A
LIDO     : 25 - Intimação lido(a) (Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A) em 17/02/25 *Referente ao evento Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA(06/02/25)
--------------------------------------------------------------------------------
PRINCIPAL: 7 - Citação expedido(a) Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A
LIDO     : 24 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 17/02/25 *Referente ao evento Não Concedida a Medida Liminar a RAQUEL LEMOS DE OLIVEIRA(06/02/25)
--------------------------------------------------------------------------------
PRINCIPAL: 7 - Citação expedido(a) Para AMIL ASSISTENCIA MEDICA INTERNACIONAL S A
LIDO     : 6 - Intimação lido(a) (Para RAQUEL LEMOS DE OLIVEIRA) em 06/02/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (06/02/25)
--------------------------------------------------------------------------------
PRINCIPAL: 117 - Intimação expedido(a) (P/ Advgs. de EDILEIDE DA SILVA LIMA) Prazo: 10 dias;
LIDO     : 118 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 31/10/24 *Referente ao evento Intimação à disposição(30/10/24)
--------------------------------------------------------------------------------
PRINCIPAL: 113 - Intimação expedido(a) (P/ Advgs. de EDILEIDE DA SILVA LIMA) Prazo: 5 dias;
LIDO     : 114 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 24/10/24 *Referente ao evento  Proferido despacho de mero expediente(16/10/24)
--------------------------------------------------------------------------------
PRINCIPAL: 87 - Intimação expedido(a) (P/ Advgs. de EDILEIDE DA SILVA LIMA) Prazo: 5 dias;
LIDO     : 93 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 11/06/24 *Referente ao evento Intimação à disposição(05/06/24)
--------------------------------------------------------------------------------
PRINCIPAL: 19 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 22/03/23 *Referente ao evento Julgada procedente em parte a ação(22/03/23)
LIDO     : 19 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 22/03/23 *Referente ao evento Julgada procedente em parte a ação(22/03/23)
--------------------------------------------------------------------------------
PRINCIPAL: 5 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 16/02/23 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (16/02/23)
LIDO     : 5 - Intimação lido(a) (Para EDILEIDE DA SILVA LIMA) em 16/02/23 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (16/02/23)
--------------------------------------------------------------------------------
PRINCIPAL: 6 - Citação expedido(a) (Para AZUL LINHAS AEREAS BRASILEIRAS S A) Sem prazo
LIDO     : 5 - Intimação lido(a) (Para PAULO CESAR AGUIAR NETO) em 12/03/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(12/03/26)
--------------------------------------------------------------------------------
PRINCIPAL: 108 - Intimação expedido(a) (P/ Advgs. de BANCO SANTANDER BRASIL S A) Prazo: 5 dias; Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)
LIDO     : 112 - Intimação lido(a) (Para BRUNO HENRIQUE GOMES BEZERRA) em 07/05/26 *Referente ao evento Intimação à disposição(27/04/26)
--------------------------------------------------------------------------------
PRINCIPAL: 97 - Disponibilização no Diário da Justiça Eletrônico - DJEN Disponibilização no Diário da Justiça Eletrônico em (11/03/26) para BANCO SANTANDER BRASIL S A *Referente ao evento Intimação expedido(a)
LIDO     : 103 - Intimação lido(a) (Para BRUNO HENRIQUE GOMES BEZERRA) em 19/03/26 *Referente ao evento Intimação expedido(a)(09/03/26)
--------------------------------------------------------------------------------
PRINCIPAL: 66 - Intimação expedido(a) (P/ Advgs. de BANCO SANTANDER BRASIL S A) Sem prazo Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)
LIDO     : 72 - Intimação lido(a) (Para BRUNO HENRIQUE GOMES BEZERRA) em 17/11/25 *Referente ao evento Documento analisado(07/11/25)
--------------------------------------------------------------------------------
PRINCIPAL: 35 - Intimação expedido(a) Para BRUNO HENRIQUE GOMES BEZERRA *Referente ao evento Informações prestadas pela autoridade coatora expedido(a)(05/05/25)
LIDO     : 38 - Intimação lido(a) (Para BRUNO HENRIQUE GOMES BEZERRA) em 09/05/25 *Referente ao evento Informações prestadas pela autoridade coatora expedido(a)(05/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 35 - Intimação expedido(a) Para BRUNO HENRIQUE GOMES BEZERRA *Referente ao evento Informações prestadas pela autoridade coatora expedido(a)(05/05/25)
LIDO     : 36 - Intimação lido(a) (Para BANCO SANTANDER BRASIL S A) em 06/05/25 *Referente ao evento Informações prestadas pela autoridade coatora expedido(a)(05/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 7 - Citação expedido(a) (Para BANCO MASTER S A) Sem prazo
LIDO     : 6 - Intimação lido(a) (Para JOSE HILTON MATOS DOS SANTOS) em 07/04/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(07/04/26)
--------------------------------------------------------------------------------
PRINCIPAL: 15 - Intimação expedido(a) (P/ Advgs. de LUIZ ANTONIO DE ANDRADE) Sem prazo
LIDO     : 18 - Intimação lido(a) (Para LUIZ ANTONIO DE ANDRADE) em 14/05/25 *Referente ao evento Julgada procedente a ação(13/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 8 - Citação expedido(a) Para ASSOCIACAO DOS APOSENTADOS E PENSIONISTAS NACIONAL
LIDO     : 5 - Intimação lido(a) (Para LUIZ ANTONIO DE ANDRADE) em 02/04/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (02/04/25)
--------------------------------------------------------------------------------
PRINCIPAL: 242 - Intimação expedido(a) (P/ Advgs. de NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) Prazo: 15 dias; Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)
LIDO     : 246 - Intimação lido(a) (Para NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) em 04/05/26 *Referente ao evento  Proferido despacho de mero expediente(24/04/26)
--------------------------------------------------------------------------------
PRINCIPAL: 221 - Intimação expedido(a) (P/ Advgs. de NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) Prazo: 5 dias; Aguardando disponibilização no Diário da Justiça Eletrônico Nacional - DJEN (CNJ)
LIDO     : 228 - Intimação lido(a) (Para NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) em 13/04/26 *Referente ao evento  Proferido despacho de mero expediente(01/04/26)
--------------------------------------------------------------------------------
PRINCIPAL: 25 - Intimação expedido(a) (P/ Advgs. de ERICK ERNANDES SANDES) Sem prazo
LIDO     : 27 - Intimação lido(a) (Para ERICK ERNANDES SANDES) em 08/05/25 *Referente ao evento Intimação à disposição(28/04/25)
--------------------------------------------------------------------------------
PRINCIPAL: 13 - Intimação expedido(a) (Para NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) Sem prazo
LIDO     : 17 - Intimação lido(a) (Para NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) em 25/04/25 *Referente ao evento  Ato ordinatório praticado(15/04/25)
--------------------------------------------------------------------------------
PRINCIPAL: 13 - Intimação expedido(a) (Para NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) Sem prazo
LIDO     : 16 - Intimação lido(a) (Para ERICK ERNANDES SANDES) em 25/04/25 *Referente ao evento  Ato ordinatório praticado(15/04/25)
--------------------------------------------------------------------------------
PRINCIPAL: 7 - Citação expedido(a) (Para NU PAGAMENTOS S A INSTITUICAO DE PAGAMENTO) Sem prazo
LIDO     : 6 - Intimação lido(a) (Para ERICK ERNANDES SANDES) em 12/04/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (12/04/25)
--------------------------------------------------------------------------------
PRINCIPAL: 12 - Citação lido(a) P/ GRUPO CASAS BAHIA S A em 20/05/26 OBS: Leitura realizada via Domicílio Eletrônico
LIDO     : 16 - Intimação lido(a) (Para GRUPO CASAS BAHIA S A) em 01/06/26 *Referente ao evento  Ato ordinatório praticado(20/05/26)
--------------------------------------------------------------------------------
PRINCIPAL: 12 - Citação lido(a) P/ GRUPO CASAS BAHIA S A em 20/05/26 OBS: Leitura realizada via Domicílio Eletrônico
LIDO     : 6 - Intimação lido(a) (Para ANDREA CARLA CARDOSO DE BRITO SILVA) em 20/05/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(20/05/26)
--------------------------------------------------------------------------------
PRINCIPAL: 6 - Citação expedido(a) (Para MIDEA INDUSTRIA E COMERCIO DO BRASIL LTDA.) Sem prazo
LIDO     : 5 - Intimação lido(a) (Para MARCELO DANIEL MELO ALENCAR) em 25/05/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(25/05/26)
--------------------------------------------------------------------------------
PRINCIPAL: 6 - Intimação lido(a) (Para ROGERIO FREITAS CAVALCANTI) em 02/06/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(02/06/26)
LIDO     : 6 - Intimação lido(a) (Para ROGERIO FREITAS CAVALCANTI) em 02/06/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(02/06/26)
--------------------------------------------------------------------------------
PRINCIPAL: 7 - Citação expedido(a) (Para TIM S A) Sem prazo
LIDO     : 6 - Intimação lido(a) (Para HOMERO MARTINS DA SILVA) em 03/06/26 *Referente ao evento Audiência de Conciliação Designada (Telepresencial)(03/06/26)
--------------------------------------------------------------------------------
PRINCIPAL: 11 - Intimação expedido(a) (P/ Advgs. de FLORISVALDO CARVALHO LIMA) Sem prazo
LIDO     : 12 - Intimação lido(a) (Para FLORISVALDO CARVALHO LIMA) em 16/05/25 *Referente ao evento Intimação expedido(a)(15/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 7 - Citação expedido(a) (Para ASSOCIACAO DE APOSENTADOS MUTUALISTA PARA BENEFICIOS COLETIVOS - AMBEC) Sem prazo
LIDO     : 6 - Intimação lido(a) (Para FLORISVALDO CARVALHO LIMA) em 13/05/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (13/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 61 - Intimação expedido(a) (Para COMPANHIA DE SEGUROS PREVIDENCIA DO SUL) Sem prazo
LIDO     : 77 - Intimação lido(a) (Para COMPANHIA DE SEGUROS PREVIDENCIA DO SUL) em 17/07/25 *Referente ao evento Intimação para Videoconferência à disposição(07/07/25)
--------------------------------------------------------------------------------
PRINCIPAL: 61 - Intimação expedido(a) (Para COMPANHIA DE SEGUROS PREVIDENCIA DO SUL) Sem prazo
LIDO     : 76 - Intimação lido(a) (Para COMPANHIA DE SEGUROS PREVIDENCIA DO SUL) em 17/07/25 *Referente ao evento Intimação à disposição(07/07/25)
--------------------------------------------------------------------------------
PRINCIPAL: 12 - Citação lido(a) P/ UNIMED SEGURADORA S/A em 13/05/25 OBS: Leitura realizada via Domicílio Eletrônico
LIDO     : 73 - Intimação lido(a) (Para COMPANHIA DE SEGUROS PREVIDENCIA DO SUL) em 07/07/25 *Referente ao evento Extinto o processo por Perempção, litispendência ou coisa julgada(13/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 12 - Citação lido(a) P/ UNIMED SEGURADORA S/A em 13/05/25 OBS: Leitura realizada via Domicílio Eletrônico
LIDO     : 6 - Intimação lido(a) (Para JOSE CARLOS DO NASCIMENTO) em 13/05/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (13/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 22 - Intimação expedido(a) Para JOSE ALDSON FRANCA MINA *Referente ao evento Julgada procedente em parte a ação(11/07/25)
LIDO     : 26 - Intimação lido(a) (Para JOSE ALDSON FRANCA MINA) em 17/07/25 *Referente ao evento Julgada procedente em parte a ação(11/07/25)
--------------------------------------------------------------------------------
PRINCIPAL: 22 - Intimação expedido(a) Para JOSE ALDSON FRANCA MINA *Referente ao evento Julgada procedente em parte a ação(11/07/25)
LIDO     : 25 - Intimação lido(a) (Para GJT PAULO AFONSO ALUGUEL DE EQUIPAMENTOS LTDA) em 21/07/25 *Referente ao evento Julgada procedente em parte a ação(11/07/25)
--------------------------------------------------------------------------------
PRINCIPAL: 9 - Citação expedido(a) Para JOSE ALDSON FRANCA MINA
LIDO     : 5 - Intimação lido(a) (Para GJT PAULO AFONSO ALUGUEL DE EQUIPAMENTOS LTDA) em 06/06/25 *Referente ao evento Audiência  de Conciliação Designada (Telepresencial) (06/06/25)
--------------------------------------------------------------------------------
PRINCIPAL: 158 - Intimação lido(a) (Para SANDRA PATRICIA RESTREPO PONTES) em 12/05/25 *Referente ao evento Intimação à disposição(12/05/25)
LIDO     : 158 - Intimação lido(a) (Para SANDRA PATRICIA RESTREPO PONTES) em 12/05/25 *Referente ao evento Intimação à disposição(12/05/25)
--------------------------------------------------------------------------------
PRINCIPAL: 142 - Intimação expedido(a) (P/ Advgs. de INSTITUTO EM BELLEZA ARACAJU LTDA) Prazo: 5 dias;
LIDO     : 143 - Intimação lido(a) (Para INSTITUTO EM BELLEZA ARACAJU LTDA) em 13/12/24 *Referente ao evento Documento analisado(03/12/24)
--------------------------------------------------------------------------------
PRINCIPAL: 138 - Intimação expedido(a) (P/ Advgs. de SANDRA PATRICIA RESTREPO PONTES) Prazo: 5 dias;
LIDO     : 139 - Intimação lido(a) (Para SANDRA PATRICIA RESTREPO PONTES) em 02/12/24 *Referente ao evento Intimação à disposição(25/11/24)
--------------------------------------------------------------------------------
PRINCIPAL: 128 - Intimação lido(a) (Para SANDRA PATRICIA RESTREPO PONTES) em 01/10/24 *Referente ao evento Intimação à disposição(01/10/24)
LIDO     : 128 - Intimação lido(a) (Para SANDRA PATRICIA RESTREPO PONTES) em 01/10/24 *Referente ao evento Intimação à disposição(01/10/24)
--------------------------------------------------------------------------------
PRINCIPAL: 95 - Intimação expedido(a) (P/ Advgs. de INSTITUTO EM BELLEZA ARACAJU LTDA) Prazo: 15 dias;
LIDO     : 96 - Intimação lido(a) (Para INSTITUTO EM BELLEZA ARACAJU LTDA) em 06/05/24 *Referente ao evento Documento analisado(24/04/24)
--------------------------------------------------------------------------------
PRINCIPAL: 83 - Intimação expedido(a) (P/ Advgs. de INSTITUTO EM BELLEZA ARACAJU LTDA) Prazo: 10 dias;
LIDO     : 86 - Intimação lido(a) (Para INSTITUTO EM BELLEZA ARACAJU LTDA) em 05/04/24 *Referente ao evento Julgada procedente em parte a ação(26/03/24)
--------------------------------------------------------------------------------
PRINCIPAL: 83 - Intimação expedido(a) (P/ Advgs. de INSTITUTO EM BELLEZA ARACAJU LTDA) Prazo: 10 dias;
LIDO     : 85 - Intimação lido(a) (Para SANDRA PATRICIA RESTREPO PONTES) em 27/03/24 *Referente ao evento Julgada procedente em parte a ação(26/03/24)
--------------------------------------------------------------------------------
PRINCIPAL: 71 - Intimação expedido(a) (P/ Advgs. de INSTITUTO EM BELLEZA ARACAJU LTDA) Sem prazo
LIDO     : 75 - Intimação lido(a) (Para INSTITUTO EM BELLEZA ARACAJU LTDA) em 01/12/23 *Referente ao evento Intimação para Videoconferência à disposição(21/11/23)
--------------------------------------------------------------------------------
PRINCIPAL: 71 - Intimação expedido(a) (P/ Advgs. de INSTITUTO EM BELLEZA ARACAJU LTDA) Sem prazo
LIDO     : 74 - Intimação lido(a) (Para INSTITUTO EM BELLEZA ARACAJU LTDA) em 01/12/23 *Referente ao evento  Proferido despacho de mero expediente(21/11/23)
--------------------------------------------------------------------------------
PRINCIPAL: 71 - Intimação expedido(a) (P/ Advgs. de INSTITUTO EM BELLEZA ARACAJU LTDA) Sem prazo

In [ ]:
rel_lido = buscar_relacao_evento(mov['ato'])

if not rel_lido:
    continue

if rel_lido.group(2) != 'lido(a)':
    continue

In [ ]:
ato_origem = None

for mov_ref in processo['movimentacoes']:

    if mov_ref['data_texto'] != data_origem:
        continue

    if evento_origem_nome.lower() not in mov_ref['ato'].lower():
        continue

    ato_origem = mov_ref
    break

In [ ]:
processos = {}
atos_relacionados = {}
df_relacoes = pd.DataFrame()
for process_json in pasta.glob('*.json'):
    with open(process_json, 'r', encoding='utf-8') as f:
        dados = json.load(f)
        # padrao_revelia = r'\(rev\.\s*arg\.?\)'
        # partes = dados['partes']
        # nome = dados['partes']['nome']
        # nome = re.sub(padrao_revelia,'',nome,flags=re.I).strip()
        # nome_normalizado = dados['partes']['nome_normalizado']
        # nome_normalizado = re.sub(padrao_revelia,'',nome_normalizado, flags=re.I).strip()
        # revelia = bool(re.search(padrao_revelia, nome, re.I))
        
        df_partes = pd.DataFrame(partes)
        df_partes['nome_normalizado_2'] = df_partes['nome'].apply(normalizar_nome)

        df_partes['canais_disponiveis'] = (df_partes.apply(canais_disponiveis, axis=1))
        df_partes['canais_disponiveis_lista'] = (df_partes.apply(lista_canais_disponiveis, axis=1))
        df_partes['habilitada_receber'] = (df_partes['tem_advogado'].fillna(False) | df_partes['domicilio_cnj'].fillna(False)
                                           | df_partes['recebe_intimacao_email'].fillna(False))
        processo_ok = df_partes['habilitada_receber'].all()
        autores_ok = (df_partes.loc[df_partes['papel'] == 'PROMOVENTE','habilitada_receber'].all())
        autores_pendentes = df_partes[(df_partes['papel'] == 'PROMOVENTE')& (~df_partes['habilitada_receber'])]
        acusados_ok = (df_partes.loc[df_partes['papel'] == 'PROMOVIDO','habilitada_receber'].all())
        acusados_pendentes = df_partes[(df_partes['papel'] == 'PROMOVIDO')& (~df_partes['habilitada_receber'])]
        
        df_partes['all_autors'] = df_partes['papel'] == 'PROMOVENTE' 
        df_partes['all_accused'] = df_partes['papel'] == 'PROMOVIDO'
        # status_processo = True if processo_ok else False
        
        
        
        # pprint(partes_resumo)
        p = process_json.stem
        processos[p] = pd.DataFrame(dados['movimentacoes'])
        df = processos[p]
            
       
        df_expedidas = expedidas(processos[p])
        df_expedidas = expedidas(df)
        print("ANTES")
        print(df_partes.columns.tolist())

        canais_historicos = (df_expedidas.groupby('destinatario')['meio_real'].unique().reset_index())
        canais_historicos['canais_historicos'] = (canais_historicos['meio_real'].apply(
        lambda x: ', '.join(sorted(set(i for i in x if pd.notna(i))))))

        # df_partes['canais_historicos'] = (canais_historicos['meio_real'].apply(lambda x: ', '.join(
        #             sorted(set(i for i in x if pd.notna(i))))))
        
        print(canais_historicos.columns.tolist())

        df_partes = df_partes.merge(canais_historicos[['destinatario', 'canais_historicos']],
                                    left_on='nome_normalizado',right_on='destinatario',how='left')
        print("DEPOIS")
        print(df_partes.columns.tolist())
        # print(df_partes)
        # canais_historicos['canais_historicos'] = (canais_historicos['meio_real'].apply(lambda x: ', '.join(
        #             sorted(set(i for i in x if pd.notna(i))))))
        # print(canais_historicos.head())
        

        df_expedidas['tipo'] = df_expedidas['ato'].apply(tipo_comunicacao)
        df_lidas = lidas(processos[p])
        df_lidas['tipo'] = df_lidas['ato'].apply(tipo_comunicacao)
        
        chave(df_expedidas, df_lidas)
        _relacoes = relacoes(df_expedidas, df_lidas)
        # print(_relacoes.columns.tolist())
        df_relacoes = pd.DataFrame({
            
            'evento_expedido': _relacoes['evento_expedido'],
            'data_expedicao': _relacoes['data_texto_expedido'],
            'ato_expedido': _relacoes['ato_expedido'],
            'destinatario': _relacoes['destinatario'],

            'meio': _relacoes['meio_real'],
            'canal': _relacoes['meio_comunicacao_expedido'],

            'ato_lido': _relacoes['ato_lido'],
            'data_leitura': _relacoes['data_leitura_str_lido'],
            'evento_lido': _relacoes['evento_lido'],

            'prazo': _relacoes['ato_expedido'].str.extract(
                r'(\d+\s*dias?)',
                expand=False
            )
        })
        

        df_relacoes = origem(df_relacoes)
        df_relacoes['destinatario_norm'] = df_relacoes['destinatario'].apply(normalizar_nome)
        df_relacoes['automatiza'] = status_processo(autores_ok, acusados_ok)
        # df_relacoes = df_relacoes.merge(canais_historicos[['destinatario', 'canais_historicos']],
        #                                 on='destinatario',how='left')
        df_relacoes = df_relacoes.merge(
            df_partes[
                [
                    'nome_normalizado',
                    'revelia',
                    # 'domicilio_cnj',
                    # 'recebe_intimacao_email',
                    'email',
                    'canais_historicos',
                    'tel',
                ]
            ],
            left_on='destinatario_norm',
            right_on='nome_normalizado_2',
            how='left'
        )#.drop(columns=['nome_normalizado'], errors='ignore')
        # df_relacoes['canais_disponiveis'] = (df_relacoes.apply(canais_disponiveis, axis=1))
        # df_relacoes['possui_email'] = (df_relacoes['email'].notna())
        canais_confirmados = (df_relacoes.groupby('destinatario')['meio'].unique().reset_index())
        print(df_relacoes.columns.tolist())
        print(df_partes.columns.tolist())
        print(canais_historicos.columns.tolist())
        canais_confirmados['canal_confirmado'] = (canais_confirmados['meio'].apply(lambda x: ', '.join(
            sorted(set(i for i in x if pd.notna(i))))))
        df_partes = df_partes.merge(canais_confirmados[['destinatario', 'canal_confirmado']],
                                    left_on='nome_normalizado',right_on='destinatario',how='left')
        # df_partes = df_partes.merge(canais_confirmados[['destinatario', 'canais_confirmado']],
        #                             left_on='nome_normalizado',right_on='destinatario',how='left')

        # df_relacoes['status_comunicacao'] = df_relacoes.apply(status_comunicacao, axis=1)
        # df_relacoes['automatiza'] = status_processo(autores_ok, acusados_ok)
        # df_relacoes['autores_ok'] = autores_ok
        # df_relacoes['acusados_ok'] = acusados_ok
        # print(df_relacoes[df_relacoes['tem_advogado'].isna()][['destinatario']].drop_duplicates())
        # print(
        #     df_partes[
        #         df_partes['nome_normalizado']
        #         .str.contains('tv vinhos', case=False, na=False)
        #     ]
        # )

        atos_relacionados[p] = df_relacoes
        display(atos_relacionados[p])